### ISSUE TITLE
Move-AzureRmResource throws an error when moving a webapp with an SSL certificate between subscriptions

### ISSUE THREAD

**Issue by alfhenrik** [Azure/azure-powershell#1283]
I am trying to move an Azure Webapp that has an SSL certificate assigned from one subscription to another subscription using:
```
Get-AzureRmResource | ? `
{ `
  $_.ResourceGroupName -eq $resourcegroupname `
} | `
Move-AzureRmResource `
  -DestinationResourceGroupName $resourcegroupname `
  -DestinationSubscriptionId $destinationSubscriptionId
``` 
I am presented with the following confirmation dialog:
![image](https://cloud.githubusercontent.com/assets/1035315/11117344/caca881a-8984-11e5-83ec-5b963144848a.png)

and once I click `Yes` after a while I receive the following error:
```
Move-AzureRmResource : 37 : Resources with identifiers 'Microsoft.Web/certificates/{certthumbprint}' were not found. The tracking Id is '{trackingid}'.
```

When I get the certificate resource using 
```
Get-AzureRmResource | ? `
{ `
  $_.ResourceGroupName -eq $resourcegroupname `
  -and $_.ResourceType -eq "Microsoft.Web/certificates" `
}
```
it's `ResourceId` is 
```
/subscriptions/{subscriptionid}/resourceGroups/{resourcegroupname}/providers/Microsoft.Web/certificates/{certthumbprint}##West US#{resourcegroupname}-WestUSwebspace
```

Are certificates apart of the services that support moving resources? 
Am I doing something wrong in my commands to move the resources?

**Comment by ravbhatnagar** [comment]
Please work with Laveesh to investigate this.

**Comment by ravbhatnagar** [comment]
@alfhenrik - This is a bug on our side. The issue is probably caused by having a # or space in your certificate name. Can you try with a name which does not contain these and see if it fixes your issue?

**Comment by alfhenrik** [comment]
@ravbhatnagar sorry for the late reply, since raising this issue we've moved our SSL away from Azure and into CloudFlare. When importing the certificate to Azure it comes up with `*.ourdomainname.com,ourdomainname.com` as the name so no spaces or `#`.

**Comment by ravbhatnagar** [comment]
@alfhenrik - Are you still running into this issue after moving your SSL to CLoudFlare?

**Comment by alfhenrik** [comment]
I haven't tested it after that, but I'll close this issue and if I run in to the issue again, I'll reopen it.

**Comment by sofipacifico** [comment]
Hello everyone. The issue was resolved? I have a cx with the same case. In advance, thanks!

**Comment by luuksommers** [comment]
Nope, still having the issue:
Resources with identifiers 'Microsoft.Web/certificates/9C770CA30C80A0CA70C6DAC0AC74F619EF6EE61E' were not found. The tracking Id is '0dbc6be8-99f8-45de-a675-c50954f7d01d'. (Code: ResourceNotFound)

**Comment by benperk** [comment]
I saw an issue like this and it seems that the Microsoft.Compute resource provider must be enabled on the source subscription.  HTH

**Comment by Altaf263** [comment]
We are still running into the issues of not able to move resources which contains App Service Plan, app Service, app insights. The error is similar to what has been posted. 
We even tried registering Microsoft.Compute on source subscription. Please let us know if someone has any guidance to resolve the same and wanted to know whether there is any cost involved in registering the Microsoft.Compute.

**Comment by barborico** [comment]
This error may be caused by externally-purchased SSL certificates. According to the [guidelines for moving Azure resources](https://docs.microsoft.com/en-in/azure/azure-resource-manager/resource-group-move-resources#app-service-limitations):

> You can move an App Service Certificate to a new resource group or subscription without any issues. However, if your web app includes an SSL certificate that you purchased externally and uploaded to the app, you must delete the certificate before moving the web app. For example, you can perform the following steps:
> 
> 1. Delete the uploaded certificate from the web app
> 2. Move the web app
> 3. Upload the certificate to the web app

**Comment by Anmolgan81** [comment]
Check if the app service plan does not contain any vnets attached to it, and if yes then move those resources with the vnet

**Comment by dwgray** [comment]
@barborico when I delete the SSL cert from my web app I then get "Cannot move selected combination of resources. The resource: '/subscriptions/[SUBSCRIPTIONID]/resourceGroups/Default-Web-WestUS/providers/Microsoft.Web/certificates/[CERTID]' is missing from the move request. Please select all the resources in the source subscription and resource group so that they can be moved together."  I verified that the cert isn't on the list of resource that is explicitly being moved.  Is there something else I need to do to remove the cert reference?

**Comment by Anmolgan81** [comment]
@dwgray Use the Azure Explorer and search for the existing certificate, delete it by checking the Resource ID. Then Try to Move

**Comment by Altaf263** [comment]
@barborico  +1 for the explanation though i have solved it long back using the same steps. 

@dwgray From where are you trying to delete the cert? I hope you are not unchecking the certificate from the resources being moved assuming it to be deleted.  If there is a certificate attached to app service , We have to navigate to  SSL certificates section and delete the certificate and then we will be able to move the App Service to different resource group.

Note : Make sure that you have the old certificate available or new certificate ready. In our case the new certificate needed lots of approvals so before deleting had to wait for sometime.

**Comment by dwgray** [comment]
@Altaf263 I went to the App Services blade, chose SSL certificates, clicked on the SSL bindings, deleted each of them then clicked on the Private Certificates and deleted each of the certificates (there was a binding for the bare domain name and one for the domain with the www subdomain and there was the current cert and two previous certs).

Then I went to resource groups, chose my web resource group and chose move (to another subscription).  The App Service Plan, the App Service and a bunch of alert rules showed up in the resources to move list, but the none of the certificates did.  So I'm baffled as to why I got the error that it was missing the cert.

And thanks for the heads up on having the cert ready, I've got that covered.

@Anmolgan81 Are you suggesting that I use this tool? https://resources.azure.com/ or something else?  If that's the tool you're referring to, is there some more info somewhere on how to perform a delete using the tool?

**Comment by Anmolgan81** [comment]
@dwgray I dont know about the tools, but its preety straight forward, you just need to look at the resource ID when you try to move the resources, look at the error which you are getting there will be a resource ID there. Get the details from there and goto the Azure storage explorer under Microsoft.certificates (If i am correct), look for the certificate thats causing the error and delete it and then try to move the resources. You will succeed

**Comment by dwgray** [comment]
@Anmolgan81 I'm sorry, I feel like I'm being dense here.  In portal.azure.com which is the default place I use to manage my Azure resources, the only search functionality I am aware of is the search bar at the top - searching for the resource ID there doesn't yield any results.  So I'm looking for guidance as to what you mean when you say "Use the Azure Explorer and search..."  or " goto the Azure storage explore".  Can you give me the next level of detail on those instructions?

**Comment by Anmolgan81** [comment]
Ill expalin this in my upcoming mail


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dwgray** [comment]
I decided to try this again since I haven't found any other options.  When I delete the certificate using the portal (see my detailed steps above), I get this error:  The resource: '/subscriptions/[SUBSCRIPTIONID]/resourceGroups/Default-Web-WestUS/providers/Microsoft.Web/certificates/[CERTID]' is missing from the move request. Please select all the resources in the source subscription and resource group so that they can be moved together. Even though I do not see the certificate anywhere in the portal and it is also not showing up in the Azure resource explorer (https://resources.azure.com).

When I try moving without deleting, I get this error:  Resources with identifiers 'Microsoft.Web/certificates/[CERTIFICATEID]' were not found. 

So it feels like something is holding onto a reference to the certificate even after I've deleted it and its bindings from the app service.

Does anyone have any idea how to diagnose this or anything that I can try to successfully move my app service between subscriptions?  I tried doing the whole process with the service stopped and with it running, with the same results.

**Comment by dwgray** [comment]
Also @Anmolgan81 - If you've got more insight into tools that I can use to diagnose this, I'd really appreciate the help.

**Comment by Anmolgan81** [comment]
@dwgray You mean to say that certificate are not showing in https://resources.azure.com/ ?
did you navigate to certificate reousrce ID inside the https://resources.azure.com/?
If the certificate are not found there as well then I am afraid you should call for MS Support.
They should help you in this case.
