### ISSUE TITLE
'New-AzAksCluster' returning Operation returned an invalid status code 'Forbidden'

### ISSUE THREAD

**Issue by cwash05** [Azure/azure-powershell#13012]
## Description
is this scenario supported?

•	Newly installed Az Powershell module on a machine that has not created a cluster before.
•	Connect to Azure as a Service Principle (SP1).
•	Create a new AKS cluster. 
        o	Specify SP2 in the CLI options.
        o	aksServicePrincipal.json doesn’t exist on disk and does not get created. 

without the aksServicePrincipal.json file I get 
 

|  …             New-AzAksCluster -ResourceGroupName $rgName -Name $name - …

     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

     | Operation returned an invalid status code 'Forbidden'

 
Do you know if this is not supported or we missing something to make it work. 

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

And

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

## Debug output

```

```

## Error output

     |  …             New-AzAksCluster -ResourceGroupName $rgName -Name $name - …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation returned an invalid status code 'Forbidden'

```

```

**Comment by VeryEarly** [comment]
Hi @wyunchi-ms ,
Please take a look

**Comment by wyunchi-ms** [comment]
Hi @cwash05 , thanks for your report!
Could you please provide us some more info so that we can identity the issue easier?
1. What's the cmdlets that you inputed in powershell?
1. What's the permission of the account you logined to the subscription? Does it have the permission to create a service principle?
1. Cound you please provide us the HTTP request and response by add `-Debug` flag in the `New-AzAksCluster` cmdlet?

**Comment by cwash05** [comment]
1. It's a custom cmdlet that basically calls New-AzAksCluster
`New-AzAksCluster -ResourceGroupName $rgName -Name $name -ServicePrincipalIdAndSecret $script:Context.AadUser -NodeCount $nodeCount -SshKeyValue $sshKeyPath`

2. We are logging in as a SP that has contributor role on the subscription.  We are passing a service principal to use in the cluster creation.

3. Files attached. The only difference between the two runs, is that the “acsServicePrincipal.json” file has been manually created and put in place for the “Working.txt” run.

[NotWorking.txt](https://github.com/Azure/azure-powershell/files/5264018/NotWorking.txt)
[Working.txt](https://github.com/Azure/azure-powershell/files/5264019/Working.txt)

**Comment by cwash05** [comment]
Hi @wyunchi-ms any update?

**Comment by wyunchi-ms** [comment]
Hi @cwash05 , I think this issue is fixed by the PR: https://github.com/Azure/azure-powershell/pull/13458, could you install the latest version of `Az.Aks` to verify it?

**Comment by cathalmchale** [comment]
> Hi @cwash05 , I think this issue is fixed by the PR: #13458, could you install the latest version of `Az.Aks` to verify it?

I've tested and it doesn't appear to fix the issue. Looking at the PR, I'm not sure it's for the same scenario at all.

@cwash05 from MS logged this issue from a support request that I raised. The problem is NOT that the SP doesn't exist server side and needs to be created, but rather that you cannot successfully create a new AKS cluster specifying an existing SP because the acsServicePrincipal.json does not exist on disk at all.

So you get a trace log like this:

````
VERBOSE: Cluster does not exist.
VERBOSE: Cluster is new.
VERBOSE: Preparing for deployment of your managed Kubernetes cluster.
VERBOSE: Using location eastus from the resource group DEVTEST-PIVOTCORP-GALWAY-AKS.
VERBOSE: Using DNS name prefix KUB-De444.
VERBOSE: Fetching SSH public key from file C:\dev\pivotts-eu\devops\psmodules\Pivot.AksAdmin\lib\cathal_id_rsa.pub
VERBOSE: No Service Principal found in C:\Users\cathal.mchale\.azure\acsServicePrincipal.json for this subscription. Creating a new Service Principal.
New-AzAksCluster : Operation returned an invalid status code 'Forbidden'
At C:\dev\pivotts-eu\devops\psmodules\Pivot.AksAdmin\Pivot.AksAdmin.psm1:324 char:17
+ ...             New-AzAksCluster -ResourceGroupName $rgName -Name $name ` ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzAksCluster], GraphErrorException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Aks.NewAzureRmAks
````

It's trying to create a new SP server side. That's not what's needed. I have provided the PSCredential that it should use. But the Az.Aks module insists on trying to find that SP in acsServicePrincipal.json first - but the file doesn't exist. So effectively I can never create a new cluster with an existing SP. Bit of a "cart before the horse" or "chicken and egg" type scenario.

**Comment by wyunchi-ms** [comment]
Hi @cathalmchale , thanks for the feedback. I will fix this issue soon.

**Comment by lizbaron** [comment]
I am facing the same issue. Is there an update on when this issue will be fixed? Thank you!

**Comment by erich-wang** [comment]
The issue is fixed in #14033 and will be released around Feb 9.
