### ISSUE TITLE
Get-AzRecoveryServicesBackupProtectionPolicy: 'ProtectedItemsCount' Backup Policy property is always 0

### ISSUE THREAD

**Issue by resartiia** [Azure/azure-powershell#14616]
## Description

Policy object returned by `Get-AzRecoveryServicesBackupProtectionPolicy` always shows `ProtectedItemsCount` as `0`. We checked a few policies, vaults (they definitely have some associated items). The issue is **not** reproducible in **Azure cli**.

## Steps to reproduce

```powershell
> $Policies = Get-AzRecoveryServicesBackupProtectionPolicy -WorkloadType AzureVM -VaultId $Vault.Id
> $Policy = $Policies | Select-Object -First 1
> $Policy | Select ProtectedItemsCount

ProtectedItemsCount
-------------------
                  0
```

## Environment data

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

az version
{
  "azure-cli": "2.15.0",
  "azure-cli-core": "2.15.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

## Module versions

```powershell
Name                                      Version
----                                      -------
Az                                        5.5.0
Az.Accounts                               2.2.6
Az.Accounts                               2.2.5
Az.Advisor                                1.1.1
Az.Aks                                    2.0.2
Az.AnalysisServices                       1.1.4
Az.ApiManagement                          2.2.0
Az.AppConfiguration                       1.0.0
Az.ApplicationInsights                    1.1.0
Az.Automation                             1.4.3
Az.Batch                                  3.1.0
Az.Billing                                2.0.0
Az.Cdn                                    1.6.0
Az.CognitiveServices                      1.8.0
Az.Compute                                4.9.0
Az.ContainerInstance                      1.0.3
Az.ContainerRegistry                      2.2.0
Az.CosmosDB                               1.0.0
Az.DataBoxEdge                            1.1.0
Az.Databricks                             1.1.0
Az.DataFactory                            1.11.3
Az.DataLakeAnalytics                      1.0.2
Az.DataLakeStore                          1.3.0
Az.DataShare                              1.0.0
Az.DeploymentManager                      1.1.0
Az.DesktopVirtualization                  2.1.1
Az.DevTestLabs                            1.0.2
Az.Dns                                    1.1.2
Az.EventGrid                              1.3.0
Az.EventHub                               1.7.1
Az.FrontDoor                              1.7.0
Az.Functions                              2.0.0
Az.HDInsight                              4.2.0
Az.HealthcareApis                         1.2.0
Az.IotHub                                 2.7.2
Az.KeyVault                               3.4.0
Az.Kusto                                  1.0.1
Az.LogicApp                               1.5.0
Az.MachineLearning                        1.1.3
Az.Maintenance                            1.1.0
Az.ManagedServices                        2.0.0
Az.MarketplaceOrdering                    1.0.2
Az.Media                                  1.1.1
Az.Monitor                                2.4.0
Az.Network                                4.6.0
Az.NotificationHubs                       1.1.1
Az.OperationalInsights                    2.3.0
Az.PolicyInsights                         1.4.1
Az.PowerBIEmbedded                        1.1.2
Az.PrivateDns                             1.0.3
Az.RecoveryServices                       4.0.0
Az.RedisCache                             1.4.0
Az.Relay                                  1.0.3
Az.Resources                              3.2.1
Az.ServiceBus                             1.4.1
Az.ServiceFabric                          2.2.2
Az.SignalR                                1.2.0
Az.Sql                                    2.16.0
Az.SqlVirtualMachine                      1.1.0
Az.Storage                                3.3.0
Az.StorageSync                            1.4.0
Az.StreamAnalytics                        1.0.1
Az.Support                                1.0.0
Az.Tools.Predictor                        0.1.0
Az.TrafficManager                         1.0.4
Az.Websites                               2.3.0
```

## Debug output
```
    {
      "type": "Microsoft.RecoveryServices/vaults/backupPolicies",
      "properties": {
        "backupManagementType": "AzureIaasVM",
        "instantRPDetails": {},
        "schedulePolicy": {
          "schedulePolicyType": "SimpleSchedulePolicy",
          "scheduleRunFrequency": "Daily",
          "scheduleRunTimes": [
            "2021-03-01T00:00:00Z"
          ],
          "scheduleWeeklyFrequency": 0
        },
        "retentionPolicy": {
          "retentionPolicyType": "LongTermRetentionPolicy",
          "dailySchedule": {
            "retentionTimes": [
              "2021-03-01T00:00:00Z"
            ],
            "retentionDuration": {
              "count": 31,
              "durationType": "Days"
            }
          },
          "weeklySchedule": {
            "daysOfTheWeek": [
              "Saturday"
            ],
            "retentionTimes": [
              "2021-03-01T00:00:00Z"
            ],
            "retentionDuration": {
              "count": 1,
              "durationType": "Weeks"
            }
          }
        },
        "instantRpRetentionRangeInDays": 2,
        "timeZone": "Eastern Standard Time",
        "protectedItemsCount": 0
      }
    }
  ]
}


DEBUG: Successfully got response from service
DEBUG: Total policies in list: 13
DEBUG: AzureQoSEvent: CommandName - Get-AzRecoveryServicesBackupProtectionPolicy; IsSuccess - True; Duration - 00:00:00.8886322
DEBUG: Finish sending metric.
DEBUG: 4:16:23 PM - GetAzureRmRecoveryServicesBackupProtectionPolicy end processing.
```

**Comment by mepand** [comment]
Thanks @resartiia for the feedback. Looping @hiaga for further analysis.

**Comment by adityabalaji-msft** [comment]
Thank you for reaching out. We are looking to get this fix in by mid July

**Comment by adityabalaji-msft** [comment]
@resartiia: PR for the fix has been merged (for PS). You can check if this scenario works in the latest PS version

**Comment by resartiia** [comment]
Hi Team,

I've installed the latest Az _6.3.0_ as well as the very latest Az.RecoverySevices _4.5.0_ ( I removed all old modules to make sure no conflict). I still see the same behavior. Is that only me having this issue? 

```
~ ❯ Get-Module Az.* -ListAvailable | Select Name, Version

Name                     Version
----                     -------
Az.Accounts              2.5.2
Az.Advisor               1.1.1
Az.Aks                   2.3.0
Az.AnalysisServices      1.1.4
Az.ApiManagement         2.2.0
Az.AppConfiguration      1.0.0
Az.ApplicationInsights   1.2.0
Az.Automation            1.7.0
Az.Batch                 3.1.0
Az.Billing               2.0.0
Az.Cdn                   1.7.1
Az.CognitiveServices     1.9.0
Az.Compute               4.16.0
Az.ContainerInstance     2.1.0
Az.ContainerRegistry     2.2.3
Az.CosmosDB              1.3.0
Az.DataBoxEdge           1.1.0
Az.Databricks            1.1.0
Az.DataFactory           1.13.1
Az.DataLakeAnalytics     1.0.2
Az.DataLakeStore         1.3.0
Az.DataShare             1.0.0
Az.DeploymentManager     1.1.0
Az.DesktopVirtualization 3.0.0
Az.DevTestLabs           1.0.2
Az.Dns                   1.1.2
Az.EventGrid             1.3.0
Az.EventHub              1.8.0
Az.FrontDoor             1.8.0
Az.Functions             3.1.0
Az.HDInsight             4.3.0
Az.HealthcareApis        1.3.1
Az.IotHub                2.7.3
Az.KeyVault              3.4.5
Az.Kusto                 2.0.0
Az.LogicApp              1.5.0
Az.MachineLearning       1.1.3
Az.Maintenance           1.1.1
Az.ManagedServices       2.0.0
Az.MarketplaceOrdering   1.0.2
Az.Media                 1.1.1
Az.Migrate               1.1.0
Az.Monitor               2.7.0
Az.Network               4.10.0
Az.NotificationHubs      1.1.1
Az.OperationalInsights   2.3.0
Az.PolicyInsights        1.4.1
Az.PowerBIEmbedded       1.1.2
Az.PrivateDns            1.0.3
Az.RecoveryServices      4.5.0
Az.RedisCache            1.5.0
Az.RedisEnterpriseCache  1.0.0
Az.Relay                 1.0.3
Az.ResourceMover         1.0.0
Az.Resources             4.3.0
Az.Security              1.0.0
Az.SecurityInsights      1.0.0
Az.ServiceBus            1.5.0
Az.ServiceFabric         3.0.1
Az.SignalR               1.3.0
Az.Sql                   3.4.1
Az.SqlVirtualMachine     1.1.0
Az.Storage               3.10.0
Az.StorageSync           1.5.0
Az.StreamAnalytics       2.0.0
Az.Support               1.0.0
Az.Tools.Predictor       0.1.0
Az.TrafficManager        1.0.4
Az.Websites              2.8.1
```
Here I'm just getting the property of all policies in the vault. 
```
~ ❯  $Policies    = Get-AzRecoveryServicesBackupProtectionPolicy -WorkloadType AzureVM -VaultId $Vault.Id                                                                      
~ ❯ $Policies.ProtectedItemsCount
0
0
0
0
0
0
0
0
0
0
0
0
0
0                                                                                                                                                                              15:29:21
~ ❯
```

**Comment by hiaga** [comment]
Hi @resartiia can you please run **Get-AzRecoveryServicesBackupProtectionPolicy** command with **-Debug** parameter.. I think the  possibility is you are getting 0 count being returned from backend. If so, we'll check with our backend team

**Comment by resartiia** [comment]
Hi @hiaga 

I was able to get the item counts but in a different way. It works when you try to get the number of items with `-Name` and `-VaultId` parameters:

Example:
```
~ ❯ Get-AzRecoveryServicesBackupProtectionPolicy -Name 'policyName' -VaultId $vault.ID | select *

SnapshotRetentionInDays : 2
ProtectedItemsCount     : 17
```
However, when you try to get for all policies at the same time, you get 0 (for all returned policies).

```
~ ❯ Get-AzRecoveryServicesBackupProtectionPolicy -WorkloadType AzureVM -VaultId $vault.ID | select *

SnapshotRetentionInDays : 2
ProtectedItemsCount     : 0
...
```
Not a big deal and it will require an extra pipeline. But maybe something to fix for the future (if that's related to the PowerShell module anyhow).

**Comment by adityabalaji-msft** [comment]
Thanks for the clarification. Closing this issue for now. We will take the above as a feature request and track internally

**Comment by bwarren18** [comment]
This is still an issue as of 12/20/2022 with Az 9.2.0.  
The Graph API and REST API also always return 0 for the ProtectedItemsCount.
https://learn.microsoft.com/en-us/rest/api/backup/backup-policies/list?tabs=HTTP

KQL:
```
  RecoveryServicesResources
  | where type == 'microsoft.recoveryservices/vaults/backuppolicies'
  | where subscriptionId == 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
  | where properties.backupManagementType == 'AzureIaasVM'
    "
```
