### ISSUE TITLE
New-Az*Deployment fails when bicep emits a warning

### ISSUE THREAD

**Issue by alex-frankel** [Azure/azure-powershell#14651]
we emit the “Cannot retrieve the dynamic parameters…” error if there is a warning in bicep. We should only fail the deployment if bicep emits an error.

https://gitch.solutions/2021/03/25/azure-bicep-cannot-retrieve-the-dynamic-parameters-for-the-cmdlet/

cc @BethanyZhou @anthony-c-martin

**Comment by anthony-c-martin** [comment]
Some implementation notes:

* You should be able to use the [exit code of the CLI command](https://github.com/Azure/bicep/blob/4857aeffbc7f68d588b765f8e4b70356fca4fae9/src/Bicep.Cli/Program.cs#L134) to verify success/failure. If the exit code is 0, the command succeeded. If the exit code is != 0, the command failed.

Unless I'm mistaken, the "warning" stream is purely a Powershell concept which doesn't have an equivalent standard stream. We only have a choice between stdout and stderr - so we emit both warnings and errors using stderr.

**Comment by alex-frankel** [comment]
If I'm reading this right, then we should always attempt deployment if the exit code is 0, even though we may still emit warnings to stderr. Is that right?

**Comment by anthony-c-martin** [comment]
> If I'm reading this right, then we should always attempt deployment if the exit code is 0, even though we may still emit warnings to stderr. Is that right?

Yup, exactly.

**Comment by BethanyZhou** [comment]
This issue has been fixed in #14668, thanks. Please help to verify when the next release is available on S185(04/13).

**Comment by Kris-Turk** [comment]
Tested and confirmed resolved. Although there is a new API version in the for that same resource which I still get the error.  

Microsoft.Network/privateEndpoints@2020-11-01

If I compile to a JSON and deploy the JSON can deploy with out a problem

**Comment by alex-frankel** [comment]
Do you have the latest version of bicep installed? I am not seeing that with bicep v0.3.255

**Comment by Kris-Turk** [comment]
> Do you have the latest version of bicep installed? I am not seeing that with bicep v0.3.255

👍 That fixed it mate (I know you're not surprised :P) Thanks for resolving everything so quickly. Loving BicepLang
