### ISSUE TITLE
Unable to update Azure Powershell to v1.1.0

### ISSUE THREAD

**Issue by Vijayaraghavanl** [Azure/azure-powershell#1672]
I am unable to update to v1.1.0. I used Webinstaller and selected the "Microsoft Azure Powershell" and installed. Installation completes successfully but "Add" button for "Microsoft Azure Powershell" remains highlighted instead of showing as "Installed".

When I run the below command to determine the Azure Powershell version it shows the version as "1.0.3".
(Get-Module -ListAvailable | Where-Object{ $_.Name -eq 'Azure' }) | Select Version, Name, Author, PowerShellVersion  | Format-List

Version           : 1.0.3
Name              : Azure
Author            : Microsoft Corporation
PowerShellVersion : 3.0

What do I need to do to update to newer version?

I have run Webinstaller as an admin.
Uninstalled Webinstaller and reinstalled.
I have tried rebooting my pc.

No luck.

**Comment by markcowl** [comment]
@Vijayaraghavanl 'Azure' is just one module installed by the microsoft azure powershell installer and 1.0.3 is the version of the azure module that ships with 1.1.0.  Thanks for reporting the issue with the 'add' button - you should not be able to add this install again after installing it, the install will eb a no-op

**Comment by haocs** [comment]
@Vijayaraghavanl  @markcowl This has been fixed and should be available within couple of hrs.

**Comment by Vijayaraghavanl** [comment]
@haocs : This will have to reopened. The problem still exists. After I install the Powershell module the "Add" comes back instead of showing as "Installed". Please reopen. Thanks!
