### ISSUE TITLE
Az.Network | New-AzFirewallPolicyApplicationRule does not allow Mssql as the protocol

### ISSUE THREAD

**Issue by v-royavinash** [Azure/azure-powershell#16894]
### Description

Az.Network | New-AzFirewallPolicyApplicationRule does not allow Mssql as the protocol.

On Azure portal there are 3 supported protocols i.e. http, https, mssql.
![image](https://user-images.githubusercontent.com/94480537/150575154-932b1e0b-69d1-45b3-8c30-7a6d35051ad4.png)

### Issue script & Debug output

```PowerShell
New-AzFirewallPolicyApplicationRule -Name AR1 -SourceAddress "192.168.0.0/16" -Protocol "http:80","mssql:1443" -WebCategory "DatingAndPersonals", "Tasteless"
```

### Environment data

```PowerShell
NA
```

### Module versions

```PowerShell
Applicable to all the versions.
```

### Error output

```PowerShell
New-AzFirewallPolicyApplicationRule: Invalid protocol mssql:1443
```

**Comment by SaurabhSharma-MSFT** [comment]
@v-royavinash I could see the same and it looks like this is not supported and redirecting this to service team to provide their inputs. 

Thanks
Saurabh

**Comment by diogomaul** [comment]
Hello team, 

Any updates on this issue? I have a big firewall policy migration and right now this problem is a show stopper.

**Comment by diogomaul** [comment]
Hi @SaurabhSharma-MSFT , Can you assign this issue to me?

I fixed this locally for my own use. I believe I can push it back to you in the next few days.

**Comment by fwsuppgithub** [comment]
Adding @Gustavo ***@***.***> for visibility.

**Comment by DaAntifreeze** [comment]
Has this issue been resolved? I am still experiencing the exact same issue, where New-AzFirewallPolicyApplicationRule does not allow Mssql as the protocol.
