### ISSUE TITLE
Get-AzureRmVirtualNetworkGatewayConnection Error: Missing type map configuration or unsupported mapping.

### ISSUE THREAD

**Issue by RamblingCookieMonster** [Azure/azure-powershell#1812]
Hello!

Can't seem to use Get-AzureRmVirtualNetworkGatewayConnection.

Versions:

* AzureRM module version 1.2.0
* PowerShell version: 4.0
* OS: 2012 R2

Steps to reproduce:

* Created a virtual network gateway connection
* Used it
* Tried to run Get-AzureRmVirtualNetworkGatewayConnection

Output:

```
PS > Get-AzureRmVirtualNetworkGatewayConnection -ResourceGroupName REDACTED
```

```
Get-AzureRmVirtualNetworkGatewayConnection : Missing type map configuration or unsupported mapping.
Mapping types:
Int64 -> UInt64
System.Int64 -> System.UInt64
Destination path:
PSVirtualNetworkGatewayConnection.EgressBytesTransferred.EgressBytesTransferred
Source value:
0
At line:1 char:1
+ Get-AzureRmVirtualNetworkGatewayConnection -ResourceGroupName REDACTED
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmVirt...tewayConnection], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkGatewayConnectionCommand
```

Cheers!

**Comment by markcowl** [comment]
@RamblingCookieMonster How did you install the cmdlets?  It's likely that you have an older version of the Azure module which has some assembly conflicts with the AzureRM.Network module.

The easiest way to fix this would be to install from the installer: https://github.com/Azure/azure-powershell/releases/download/v1.2.1-February2016/azure-powershell.1.2.1.msi 

which will clean up any older versions of Gallery modules

**Comment by jt55401** [comment]
I'm getting the same issue.

**Comment by tbrowningcds** [comment]
I am getting the same error when I use New-AzureRmVirtualNetworkGatewayConnection.

**Comment by Dicoz** [comment]
Same issue on:
OS: 7 64-bit
PS: 4      0      -1     -1
Azure module: 1.0.5

**Comment by cleverguy25** [comment]
Same issue on Get-AzureRmApplicationGateway in AzurePs 1.3.0

**Comment by rwakefie** [comment]
Same issue with New-AzureRmVirtualNetworkGatewayConnection on Azure Module 1.3.0

**Comment by MartinDiewald** [comment]
I cannot create a new Gateway Connection. Same error:
PS C:\WINDOWS\system32> New-AzureRmVirtualNetworkGatewayConnection -Name "osr-sec01-ERConnect" -ResourceGroupName "osr-sec01-network" -Location "West Europe" -VirtualNetworkGateway1 $gw -PeerId $circuit.Id -ConnectionType ExpressRoute

New-AzureRmVirtualNetworkGatewayConnection : 
Mapping types:
UInt64 -> Nullable`1
System.UInt64 -> System.Nullable`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
Destination path:
VirtualNetworkGatewayConnection.EgressBytesTransferred.EgressBytesTransferred
Source value:
0
In Zeile:1 Zeichen:1
+ New-AzureRmVirtualNetworkGatewayConnection -Name "osr-sec01-ERConnect ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVirt...tewayConnection], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionCommand

**Comment by markjbrown** [comment]
Will take a look.

**Comment by markjbrown** [comment]
Hi folks. We have released a hotfix to NRP which should fix this. Please try again and report back.

thanks.

**Comment by andyjballgit** [comment]
this fixed the issue for me , was getting the error with 1.09 , upgraded to 1.10 , now all good thx. 
Andy Ball

**Comment by derekschauland** [comment]
I am still seeing an error when running this cmdlet and the version installed shows 1.0.10 attempts to update the azurerm.network module do not update any files and the latest build of the azurerm modules has been installed.

Not sure what to try next.

**Comment by morgansimonsen** [comment]
Problem seems to have been reintroduced in AzureRM.Network v2.2.0, v2.1.0 works as exptected. Error in 2.2.0:
New-AzureRmVirtualNetworkGatewayConnection :
Mapping types:
UInt64 -> Nullable`1
System.UInt64 -> System.Nullable`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
Destination path:
VirtualNetworkGatewayConnection.EgressBytesTransferred.EgressBytesTransferred
Source value:
0
At line:1 char:9
+ $conn = New-AzureRmVirtualNetworkGatewayConnection -Name $ERConnectio ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVirt...tewayConnection], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionCommand

Morgan

**Comment by mraymond77** [comment]
I get the exact same error as morgansimonsen when attempting to run New-AzureRmVirtualNetworkGatewayConnection

AzureRM Version: 2.1.0

**Comment by wasserja** [comment]
I'm also getting this error with AzureRm.Network 3.0.0

**Comment by jmilczek** [comment]
Experiencing the same issue for Get-AzureRmVirtualNetworkGatewayConnection with version 3.2.0. Anyone working on this?

**Comment by shadewlkr** [comment]
Also on version 3.2.0 for AzureRm and receiving this issue....

**Comment by inghak** [comment]
Same problem. Azure.Rm.Network 3.2.0.

**Comment by markjbrown** [comment]
I will forward this onto our Gateway PM to review.

**Comment by markjbrown** [comment]
Resent this to the dev team to take a look at. Apologies for the slow response. Holidays slow things down a bit. 

Rather than reopen this one you can track this from here, #2873 

Thanks.

**Comment by inghak** [comment]
Hi.
This problem disappeared when installing AzureRm with the msi instead of
the install-module command from the psgallery.

2. jan. 2017 7:14 p.m. skrev "Mark Brown" <notifications@github.com>:

**Comment by Mihai-Mircea** [comment]
Seems that with AzureRM.Network 4.1.0 the issue is solved. 
I got this from [PSGallery here](https://www.powershellgallery.com/packages/AzureRM.Network/4.1.0)
