### ISSUE TITLE
Creating VMSS flex without VM profile doesn't work as expected using New-AzVMSS command

### ISSUE THREAD

**Issue by dennispadia** [Azure/azure-powershell#18217]
### Description

There are two issues when creating VMSS flex without VM profile using PowerShell

*********
ISSUE 1
*********
I can create VMSS flex without VM profile using below method, where I'm creating VmssConfig using New-AzVmssConfig command and passing it as an argument to create VMSS flex without VM profile using New-AzVmss command

$RGName = "dp-vmss"
$VMSSName = "sap-flex"
$Location = "westus2"
$vmssConfig = New-AzVmssConfig -Location $Location -PlatformFaultDomainCount 3
$VMSS = New-AzVmss -ResourceGroupName $RGName -Name $VMSSName -VirtualMachineScaleSet $vmssConfig -Verbose

But when I create VMSS flex without VM profile only using New-AzVmss command where I define -PlatformFaultDomainCount parameter, the behavior is different. It creates VMSS Uniform with VM profile. 

New-AzVmss -ResourceGroupName dp-vmss -Name sap-flex3 -Location westus2 -PlatformFaultDomainCount 3

Expected Outcome: It should create VMSS flex without VM profile just like the one created using vmssConfig as argument. 

*********
ISSUE 2
*********
When I create using VMSS flex without VM profile using below commands, it takes "Flexible" as default orchestration mode for scale set. 

$RGName = "dp-vmss"
$VMSSName = "sap-flex"
$Location = "westus2"
$vmssConfig = New-AzVmssConfig -Location $Location -PlatformFaultDomainCount 3
$VMSS = New-AzVmss -ResourceGroupName $RGName -Name $VMSSName -VirtualMachineScaleSet $vmssConfig -Verbose

But when I create VMSS flex without VM profile only using New-AzVmss command, it takes "Uniform" as default orchestration mode for scale set and create VMSS Uniform with VM profile.

New-AzVmss -ResourceGroupName dp-vmss -Name sap-flex3 -Location westus2 -PlatformFaultDomainCount 3

So I have created scale set with -OrchestrationMode as Flexible, it creates VMSS flex with VM profile (with default VM template). 

New-AzVmss -ResourceGroupName dp-vmss -Name sap-flex1 -Location westus2 -PlatformFaultDomainCount 3 -OrchestrationMode Flexible

Expected Result: The behavior is different of each command mentioned in issue 2. User should be given privilege to set -OrchestrationMode value and based on that it should create scale set (Uniform or Flexible).

### Issue script & Debug output

```PowerShell
NA
```

### Environment data

```PowerShell
NA
```

### Module versions

```PowerShell
NA
```

### Error output

```PowerShell
NA
```

**Comment by Drewm3** [comment]
@avirishuv, could you please look into this.

**Comment by Sandido** [comment]
1. The VM Profile not being created only when a Vmss Config object is used is due to the way the cmdlet is coded.
When a Vmss config object is used, then the direct cmdlet code is used. This only creates a VMProfile if a parameter in a VMProfile is provided.
When only the cmdlet is used without vmconfig, then a VmssStrategy file is used which always creates a VMProfile. 
This may be left over from when we thought Vmss Uniform could never have a VM Profile, and before the OrchestrationMode parameter even existed. 

**If a Vm Profile can be included in a Vmss Flex or not, then we can code this behavior on the PS side. Please verify if this behavior is allowed.** 

2. The discrepancy in the Flex and Uniform value is likely due to an API issue. Unsure why. Need input from the API team about the expected behavior. 
**Is Flexible the default OrchestrationMode value now?**

**Comment by Sandido** [comment]
[ADO item ](https://msazure.visualstudio.com/One/_workitems/edit/15046519)tracking this work.

**Comment by jaylabell** [comment]
This item is still pending for updates

**Comment by jaylabell** [comment]
This item is still in progress

**Comment by grizzlytheodore** [comment]
The issue come from the following:
- By API design, VMSS with (VM Profile == null) defaults to OrchestrationMode: Flexible VMSS. 
VMSS without VM Profile cannot be a Uniform VMSS.  
- VMSS Flex is a relatively new feature, and before you could not create a VMSS without Vm Profile.
- Because of that, all parameter sets of New-AzVmss and New-AzVmssConfig would have default values for VM profile, if none of the properties were provided. 
- However when VMSS Flex feature came out, we went through a breaking change to allow New-AzVmssConfig to create a VMSS object with VMProfile = null, so that users can create VMSS in flex mode. 
- So default parameter set in the above case will default to VMSS flex mode 
- but simple parameter set still always creates VM Profile, defaulting to a value for many properties in VM Profile. So it will create a OrchestrationMode: Uniform by default in the above case.

**Comment by Drewm3** [comment]
We are working through the process on how and/or when to make the changes for this issue. In general, we are looking to move VMSS to defaulting to the Flex mode. So, this change will likely be done as part of a larger breaking change release.

**Comment by mimckitt** [comment]
Confirmed the behavior. Will forward to the engineering team to investigate further.

**Comment by hilaryw29** [comment]
Closing as this is now fixed with the release of default to Flexible orchestration state on PowerShell and CLI. Thanks for raising this!

Announcement: https://techcommunity.microsoft.com/t5/azure-compute-blog/breaking-change-for-vmss-powershell-cli-customers/ba-p/3818295

**Comment by dennispadia** [comment]
Hello, 

The release of the default to Flexible orchestration addresses part of the issue. However, the other aspect of the problem persists, as outlined below (this was initially reported and is not a new issue).

I aim to create a VMSS flex **without** a scaling profile, where I don’t want to define any VM template like VM SKUsize, credentials, disks, OS image etc. Currently, I can create a VMSS flex without a scaling profile in PowerShell by first creating a VMSS config with the command “New-AzVmssConfig” and then passing this config as a value to the -VirtualMachineScaleSet parameter in the “New-AzVmss” command.

$vmssconfig = New-AzVmssConfig -Location westus3 -PlatformFaultDomainCount 1 New-AzVmss -ResourceGroupName dp-mwestus3 -Name sap-flex1 -VirtualMachineScaleSet $vmssconfig

ISSUE:

However, if I attempt to create a flexible scale set without a scaling profile using just the “New-AzVmss” command, it doesn’t create a VMSS flex without a scaling profile. Instead, it creates a scale set with a default VM template and creates 2 VM instances.

New-AzVmss -ResourceGroupName dp-mwestus3 -Name sap-flex2 -Location westus3 -PlatformFaultDomainCount 1

Questions/Concerns:

1. How can I create a scale set without a scaling profile using just the “New-AzVmss” flex command? I don’t want to create a configuration using New-AzVmssConfig. Instead, I want to create a scale set using just one "New-AzVmss" command.

2. With the New-AzVmss command, I haven’t passed any argument. So, I expect it to create just an empty flexible scale set construct. However, it is creating a scale set with a scaling profile with two instance counts. Why is this a default behavior? 

3. If this is the expected behavior, I would expect some information on the page below addressing that to create scale set without scaling profile you need to first create configuration object using "New-AzVmssConfig" and pass it as an argument to "New-AzVmss". 
https://learn.microsoft.com/en-us/powershell/module/az.compute/new-azvmss?view=azps-10.4.1

Let me know if you need more information.

**Comment by grizzlytheodore** [comment]
@dennispadia  Thank you for sharing. 

After you submitted this issue, we had an in-depth conversation about the behavior of the two parameter sets. 

The default parameter sets values for properties in VirtualMachineScaleSetVMProfile to provide a layer of 'convenience' for the customers. 

While we strive to provide similar in experience to customers for different parameter sets, removing the defaulting in default parameter set will bring too much breaking change. So the default parameter set will continue to create the VmssVmProfile.

If you would like to create a VMSS with an empty VmssVmProfile, you will have to continue using the simple parameter set, which requires you to create a VMSS object using New-AzVmssConfig.  

I did update the documentation for New-AzVmss to describe this behavior.  


I will be closing this issue, as we have no plans to change the creation behavior.
