### ISSUE TITLE
New-AzureRmADApplication: Access denied to the specified API version

### ISSUE THREAD

**Issue by winperec** [Azure/azure-powershell#1896]
I created service principal, assign subscription Owner role for it and use Login-AzureRmAccount to authorize to Azure. 
Then when I try to run New-AzureRmADApplication command under my service principal I get the following error:
{"odata.error":{"code":"Authentication_Unauthorized","message":{"lang":"en","value":"Access denied to the specified API version."}}}

In exception i see that request goes to 
https://graph.windows.net/<tenant_id>/me?api-version=1.6-internal

Is it expected behavior?  Is it possible to create AAD application under service principal?
Version of my AzurePS 1.2.1

**Comment by winperec** [comment]
similar issue with azure cli
https://github.com/Azure/azure-xplat-cli/issues/2047

**Comment by markcowl** [comment]
@winperec How have you configured your service principal?  Your service principal needs to have access to the graph API (which you can provide through the portal).

**Comment by winperec** [comment]
I created it through the old portal... 
But OK, will try to assign permissions to Graph API

**Comment by winperec** [comment]
No luck..
I've added permissions to Microsoft Graph 'Read directory' data
http://screencast.com/t/92kp4IkzF 
and assign all relevant roles on subscription for principal
http://screencast.com/t/ffEdrXrd1A

So which permissions I should add to the service principal ? Seems it's AD issue...

**Comment by markcowl** [comment]
@winperec Subscription role assignments aren't used in the graph API.  Your AD application needs to have permission to reqdn and write data in order to create an application / service principal.

**Comment by markcowl** [comment]
@winperec We have reproduced this internally - ths ieeus is that third party applications (service principal) are not allowed to use version 1.6-interna;l of the graph library.  Will need to update the graph library version to enable this scenario

**Comment by daviderickson** [comment]
Between this and https://github.com/Azure/azure-xplat-cli/issues/2709 I literally cannot create a keyvault, it would be nice to get this fixed before June.

**Comment by winperec** [comment]
@markcowl Thanks Mark for response. I hope you will fix that.
because the issue blocks some our automation scenarios.

**Comment by Moozhe** [comment]
Same issue.  Is there any workaround to creating an AD Application as a service principal?

**Comment by markcowl** [comment]
@Moozhe @winperec @daviderickson Unfortunately, this means using a different api-version for these calls, which means a new set of request and response contracts, and right now there is no graph version that returns the data required by the ResourceAuthorization cmdlets  that does not have this same whitelisting issue.  We are looking at some workarounds, but this will likely not be resolved until later in the summer.

Meanwhile there is a partial workaround, in replacing the api-version (1.6.1-preview with 1.6) in a delegating handler, and putting the delegating handler in the pipeline for this request, using https://github.com/Azure/azure-powershell/blob/dev/src/Common/Commands.Common.Authentication/Interfaces/IClientFactory.cs#L47 

This should work for AD cmdlets, but will run into problems with the authorization cmdlets, as that API version dpoes not return the data needed for those cmdlets.

**Comment by cormacpayne** [comment]
Fixed in the dev branch

**Comment by VishalNagarAR** [comment]
Any update on the issue ? As we need to automate the creation of AD application using service principal for key vault.

**Comment by piquet-h** [comment]
Is this actually closed - it appears some people are still having the issue. (Me included)

**Comment by shuagarw** [comment]
@RbacAsk for FYI.
Can you please describe the issue? This should be fixed - if you are logged in with a service principal and if that application has read and write access on directory then you should be able to create another application.

**Comment by xinyiou** [comment]
We are also having a similar issue when calling the cmdlet Get-AzureRmADGroup while logged in as a service principal. We've given the service principal the proper read/write directory permissions for Graph API, but we are still getting the error: "Access denied to the specified api-version" as well as "Insufficient privileges to complete the operation."  Is this related?

**Comment by piquet-h** [comment]
I have a Visual Studio Online account with a release pipeline that creates an automation principal. I've given the VisualStudioSPN owner access to my subscription, but when it tries to create the new Application - I get the error.
`$Application = New-AzureRmADApplication -DisplayName $ApplicationDisplayName -HomePage ("http://" + $ApplicationDisplayName) -IdentifierUris ("http://" + $KeyId) -KeyCredentials $KeyCredential`

Is there something more than giving the SPN Owner role required to provide read/write access to the directory?

**Comment by RBACAsk** [comment]
In this case the confusion seems to stem from the two access control methods involved:

·         Giving the SP “Owner” rights allows the SP access to Azure resources (VMs, Storage accounts etc)

·         The rights to create Applications/Users/Groups are controlled/enforced by Azure Active Directory (as opposed to Azure Resource Manager)

Thus, you would need to give your SP the appropriate rights in the directory. This can be done when you configure the application in the portal.

Stefan

**Comment by Codelnw** [comment]
Any update on this matter ? I'm experiencing the same issue as @xinyiou .

**Comment by bvirkler** [comment]
I am also experiencing this issue using AzureRm.Resources 3.2.0.  Setting `$debugPreference = 'Continue'` shows that it is still hitting the 1.6-internal api version.

**Comment by synesthesia** [comment]
Even when I give the SP the Company Administrator role I get 
```
odata.error":{"code":"Authentication_Unauthorized","message":{"lang":"en","value":"Access denied to the specified API version."}}
```

**Comment by mkarpuk** [comment]
> Thus, you would need to give your SP the appropriate rights in the directory. This can be done when you configure the application in the portal.

Can anyone suggest an idea how to achieve this ('give your SP the appropriate rights in the directory')? 

I want to write a powershell runbook which automates Azure AD application creation. Right now I can't do it with service principal due to the same error (Access denied to the specified API version).

Should I edit manifest, execute some Powershell command, ... ?

Thanks in advance

**Comment by shuagarw** [comment]
@rbacask for FYI 
@mkarpuk  Can you please run fiddler, and find out the url which is giving api version issue. Ensure that you are on azure powershell v2 or above.
Also, The service principal which you are using to login and automate the create of other apps, need to have permission for read/write on directory otherwise it can't perform the operation. If you login to AUX portal (https://manage.windowsazure.com) , go to Active Directory tab, select you App under Applications tab and click on Configure. On the bottom you can configure what permission you want to give to this app, as below. New Ibiza portal (https://ms.portal.azure.com), should also have something equivalent, although I couldn't find. Will post it once I have that.
![image](https://cloud.githubusercontent.com/assets/10227276/21620089/84e19958-d1a7-11e6-9862-fbf6b6c04801.png)

**Comment by mkarpuk** [comment]
I can't run fiddler (at least i have no idea how to run it during runbook execution). Anyway, I don't think that it's API version issue since I was able to implement the runbook using my own credential (subscription admin): 
`$cred = Get-AutomationPSCredential –Name "ADAccess"`
`Add-AzureRmAccount –Credential $cred –SubscriptionName "MySubscription"`

`$principal = Get-AzureRmAdServicePrincipal -SearchString $ApplicationName`
This works.
However attempts to use service principal to achieve the same task are still unsuccessful.
`$sp=Get-AutomationConnection -Name $connectionName`     
`Add-AzureRmAccount  -ServicePrincipal  -TenantId $sp.TenantId -ApplicationId $sp.ApplicationId -CertificateThumbprint $sp.CertificateThumbprint`
`$principal = Get-AzureRmAdServicePrincipal -SearchString $ApplicationName`

The code above causes

> {"odata.error":{"code":"Authentication_Unauthorized","message":{"lang":"en","value":"Access denied to the specified API 
version."}}}

I have added all possible permissions (thanks to @shuagarw to point out where to do this), but result is still the same
![azureapppermissions](https://cloud.githubusercontent.com/assets/360990/21641037/31cc3438-d28a-11e6-980b-c8bacfe82c9c.PNG)

**Comment by dpiessens** [comment]
I'm having the same issues with the permissions above set. I was able to fiddler the call and have posted it below. In this case I was calling the Set-AzureRmADApplication command, but was having the same issue with New-AzureRmADApplication. I did make sure the machine was updated to the December 2016 Azure Powershell Commands.

`
PATCH https://graph.windows.net/b526ac6f-288d-4092-85e4-3dc3869cd1fb/applications/fb0f50a1-f7f1-466e-a0de-a2031134044c?api-version=1.6 HTTP/1.1
x-ms-client-request-id: a0036ad1-fc6f-46eb-8313-3b62674451c3
accept-language: en-US
Authorization: Bearer <token was here>
User-Agent: FxVersion/4.6.1087.0 OSName/Windows_Server_2012_R2_Datacenter OSVersion/6.3.9600 Microsoft.Azure.Graph.RBAC.GraphRbacManagementClient/3.2.0-preview AzurePowershell/v3.3.0.0 PSVersion/v4.0
CommandName: Set-AzureRmADApplication
ParameterSetName: ApplicationObjectIdWithUpdateParamsParameterSet
Content-Type: application/json; charset=utf-8
Host: graph.windows.net
Content-Length: 133
Expect: 100-continue

{
  "availableToOtherTenants": false,
  "homepage": "https://bogus.url/com",
  "replyUrls": [
    "https://bogus.url/com"
  ]
}
`

**Comment by nishanperera** [comment]
Any update on this matter ? I'm experiencing the same issue when I try to run New-AzureRmADApplication

**Comment by SquirrelAssassin** [comment]
Azure Automation: Get-AzureRmRoleAssignment with an normal user account that has read permission on  the subscription.


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://graph.windows.net/0f6687b5-c8f2-4e2e-941a-afe3fe1f2d8e/getObjectsByObjectIds?api-version=1.6-internal

Headers:
x-ms-client-request-id        : 3d1da0fd-19c4-457c-8a14-9b9180cdf707
accept-language               : en-US

Body:
{
  "objectIds": [
    "1d229208-ca3f-4870-9290-e5f41e61d887",
    "35422c2a-f13a-4370-a2b6-18642fda3552",
    "989c4ddd-769a-4d1a-b06a-ce6f9411efc2",
    "653efd79-2a78-461e-a706-cb035723d7bc",
    "0cc99dc3-1946-4571-9ae8-17c0fbdb0a0f",
    "32d312f1-bb16-43cb-be24-e4f1b03dcf6b",
    "e7ffa006-4944-4e32-89fe-3c3e1ef1321f",
    "1dbe2376-4362-4649-b373-192ec8a90324",
    "b8b2ece6-9dbb-4627-8146-d893845be910",
    "11f32180-2f90-48b6-9539-2376e161dae3"
  ],
  "includeDirectoryObjectReferences": true
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Forbidden

Headers:
Pragma                        : no-cache
ocp-aad-diagnostics-server-name: 31iu8AsOAhDJshQmk5pIBaD/QqzZKFnp6shdH6MXn7I=
request-id                    : 70e705ad-eebe-471e-b264-14cc7c9ced3a
client-request-id             : 2883250e-025b-4ad3-b915-b5fe45c94c6b
x-ms-dirapi-data-contract-version: 1.6-internal
ocp-aad-session-key           : mAJiYlODB7r4l74rswijjsT3n11Elp_y9xi1WaQaZZrPKWzvYe-T3tmFcvy9sJm0rqEdhOIV4zmOqBtsMfAml2-puOmKQR843PjHBv8nW-70gCy_skqGo_OWT5SuwPIn.g4Pgen7Wx0AwfEmvAosatg
NapyauX7OiX-ISFLxv_qU
DataServiceVersion            : 3.0;
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Access-Control-Allow-Origin   : *
Duration                      : 550663
Cache-Control                 : no-cache
Server                        : Microsoft-IIS/8.5
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET,ASP.NET
Date                          : Wed, 08 Mar 2017 18:08:19 GMT

Body:
{
  "odata.error": {
    "code": "Authentication_Unauthorized",
    "message": {
      "lang": "en",
      "value": "Access denied to the specified API version."
    },
    "requestId": "70e705ad-eebe-471e-b264-14cc7c9ced3a",
    "date": "2017-03-08T18:08:19"
  }
}

**Comment by RBACAsk** [comment]
+ Daniel

Hi,
Are you running this as a  Service Principal or User Account? This is a  known issue when executing using a Service Principal. We are working on a fix.

Thx
Surabhi

**Comment by RBACAsk** [comment]
+Jean-Marc

From: Surabhi Pandey
Sent: Wednesday, March 8, 2017 6:33 PM
To: Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com>; Daniel Dobalian <dadobali@microsoft.com>
Cc: RBAC Ask <RBACAsk@microsoft.com>; Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-powershell] New-AzureRmADApplication: Access denied to the specified API version (#1896)

+ Daniel

Hi,
Are you running this as a  Service Principal or User Account? This is a  known issue when executing using a Service Principal. We are working on a fix.

Thx
Surabhi

**Comment by RBACAsk** [comment]
Also, did you try if you have the same issue with the AzureAD PowerShell Module (v2.0) instead of the AzureADrm ones?
(In case you are not familiar with them, here is a script using the AzureAD PowerShell module which automates one of our samples: https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential/blob/master/Configure.ps1)

I’m not sure if this will help you but with the AzureAD Powershell module, there are 3 cmdlets to get different types of role assignment

  *   Get-AzureADGroupAppRoleAssignment<https://docs.microsoft.com/en-us/powershell/azuread/v2/get-azureadgroupapproleassignment>
  *   Get-AzureADServiceAppRoleAssignment<https://docs.microsoft.com/en-us/powershell/azuread/v2/get-azureadserviceapproleassignment>
  *   Get-AzureADUserAppRoleAssignment<https://docs.microsoft.com/en-us/powershell/azuread/v2/get-azureaduserapproleassignment>
Regards
Jean-Marc

From: Daniel Dobalian
Sent: 09 March 2017 04:15
To: Surabhi Pandey <Surabhi.Pandey@microsoft.com>; Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com>
Cc: RBAC Ask <RBACAsk@microsoft.com>; Mention <mention@noreply.github.com>; Jean-Marc Prieur <Jean-Marc.Prieur@microsoft.com>
Subject: RE: [Azure/azure-powershell] New-AzureRmADApplication: Access denied to the specified API version (#1896)

+Jean-Marc

From: Surabhi Pandey
Sent: Wednesday, March 8, 2017 6:33 PM
To: Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com<mailto:azure-powershell@noreply.github.com>>; Daniel Dobalian <dadobali@microsoft.com<mailto:dadobali@microsoft.com>>
Cc: RBAC Ask <RBACAsk@microsoft.com<mailto:RBACAsk@microsoft.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [Azure/azure-powershell] New-AzureRmADApplication: Access denied to the specified API version (#1896)

+ Daniel

Hi,
Are you running this as a  Service Principal or User Account? This is a  known issue when executing using a Service Principal. We are working on a fix.

Thx
Surabhi

**Comment by RBACAsk** [comment]
To avoid confusion, the cmdlets below deal with directory application roles. The AzureRmRoleAssignment ones deal with Azure RBAC roles.

From: Jean-Marc Prieur
Sent: Thursday, March 9, 2017 6:31 AM
To: Daniel Dobalian <dadobali@microsoft.com>; Surabhi Pandey <Surabhi.Pandey@microsoft.com>; Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com>
Cc: RBAC Ask <RBACAsk@microsoft.com>; Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-powershell] New-AzureRmADApplication: Access denied to the specified API version (#1896)

Also, did you try if you have the same issue with the AzureAD PowerShell Module (v2.0) instead of the AzureADrm ones?
(In case you are not familiar with them, here is a script using the AzureAD PowerShell module which automates one of our samples: https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential/blob/master/Configure.ps1)

I’m not sure if this will help you but with the AzureAD Powershell module, there are 3 cmdlets to get different types of role assignment

  *   Get-AzureADGroupAppRoleAssignment<https://docs.microsoft.com/en-us/powershell/azuread/v2/get-azureadgroupapproleassignment>
  *   Get-AzureADServiceAppRoleAssignment<https://docs.microsoft.com/en-us/powershell/azuread/v2/get-azureadserviceapproleassignment>
  *   Get-AzureADUserAppRoleAssignment<https://docs.microsoft.com/en-us/powershell/azuread/v2/get-azureaduserapproleassignment>
Regards
Jean-Marc

From: Daniel Dobalian
Sent: 09 March 2017 04:15
To: Surabhi Pandey <Surabhi.Pandey@microsoft.com<mailto:Surabhi.Pandey@microsoft.com>>; Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com<mailto:azure-powershell@noreply.github.com>>
Cc: RBAC Ask <RBACAsk@microsoft.com<mailto:RBACAsk@microsoft.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Jean-Marc Prieur <Jean-Marc.Prieur@microsoft.com<mailto:Jean-Marc.Prieur@microsoft.com>>
Subject: RE: [Azure/azure-powershell] New-AzureRmADApplication: Access denied to the specified API version (#1896)

+Jean-Marc

From: Surabhi Pandey
Sent: Wednesday, March 8, 2017 6:33 PM
To: Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com<mailto:azure-powershell@noreply.github.com>>; Daniel Dobalian <dadobali@microsoft.com<mailto:dadobali@microsoft.com>>
Cc: RBAC Ask <RBACAsk@microsoft.com<mailto:RBACAsk@microsoft.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [Azure/azure-powershell] New-AzureRmADApplication: Access denied to the specified API version (#1896)

+ Daniel

Hi,
Are you running this as a  Service Principal or User Account? This is a  known issue when executing using a Service Principal. We are working on a fix.

Thx
Surabhi

**Comment by sam-cogan** [comment]
> Are you running this as a  Service Principal or User Account? This is a  known issue when executing using a Service Principal. We are working on a fix.

Any update on when we might see a fix for this? We need to be able to create a service principal using a service principal.

**Comment by RBACAsk** [comment]
+Surabhi, Hari

The necessary changes in the AAD Graph service have made it into PPE/Dogfood. Our team is working on updating the Powershell cmdlets.

Stefan

**Comment by sam-cogan** [comment]
Any update on this, really holding back our automated deployments

**Comment by RBACAsk** [comment]
@Haridarshan Hosakere Sudhakar<mailto:hahosake@microsoft.com> – can you provide an update?

**Comment by RBACAsk** [comment]
Hi Stefan,
The Fix has been merged to the azure-powershell repo https://github.com/Azure/azure-powershell/pull/3892.
The PowerShell release with this fix is scheduled for 05/10.

Thanks,
Haridarshan H.S.


From: Stefan Miltchev
Sent: Thursday, May 4, 2017 8:30 AM
To: Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com>; Haridarshan Hosakere Sudhakar <hahosake@microsoft.com>
Cc: RBAC Ask <RBACAsk@microsoft.com>; Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-powershell] New-AzureRmADApplication: Access denied to the specified API version (#1896)

@Haridarshan Hosakere Sudhakar<mailto:hahosake@microsoft.com> – can you provide an update?

**Comment by pearcec** [comment]
Has this been released?

**Comment by SquirrelAssassin** [comment]
Tried PowerShell Module AzureRM.Resources 4.1.0

**hitting:**
Absolute Uri:
https://graph.windows.net/6ac7a1f4-5fb1-4153-bb4f-12d2020a1f7d/getObjectsByObjectIds?api-version=1.6-internal

**with response:**
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Forbidden

Headers:
ocp-aad-diagnostics-server-name: dTyuzoHTAk1uQ73PxYsF8j1mcPD3acpzEJCVTKtA5U8=
request-id                    : 585f32c8-2f0e-4097-91f1
client-request-id             : eda2bfb1-2fed-456a-817c
x-ms-dirapi-data-contract-version: 1.6-internal
ocp-aad-session-key           : Ku
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Access-Control-Allow-Origin   : *
Duration                      : 371687
Cache-Control                 : private
Server                        : Microsoft-IIS/8.5
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET,ASP.NET
Date                          : Fri, 09 Jun 2017 19:40:23 GMT

Body:
{
  "odata.error": {
    "code": "Authentication_Unauthorized",
    "message": {
      "lang": "en",
      "value": "Access denied to the specified API version."
    }
  }
}

**Comment by darshanhs90** [comment]
@SquirrelAssassin Could you let us know the version of azure powershell that you are using.
you can get that by running the following command
Get-Module -ListAvailable -Name Azure -Refresh

**Comment by SquirrelAssassin** [comment]
Azure is 3.8.0.

**Comment by darshanhs90** [comment]
@SquirrelAssassin The invalid API version issue was fixed as apart of the 4.0 version release .
Could you install the latest version from here and let me know in case the issue persists still.
https://github.com/Azure/azure-powershell/releases/tag/v4.1.0-June2017

**Comment by SquirrelAssassin** [comment]
So I updated azure: install-module azure -force as seen below and still get the error.  I had another guy test and got the same thing.  Now I went and had someone else go and download the msi for the latest which installs to his x86 directory which worked.  Thoughts?

    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                                                                        
---------- -------    ----                                ----------------                                                                                                                                        
Script     4.1.0      Azure                               {Get-AzureAutomationCertificate, Get-AzureAutomationConnection, New-AzureAutomationConnection, Remove-AzureAutomationConnection...}                     
Script     3.8.0      Azure                               {Get-AzureAutomationCertificate, Get-AzureAutomationConnection, New-AzureAutomationConnection, Remove-AzureAutomationConnection...}                     
Script     0.2.0      Azure.AnalysisServices              {Add-AzureAnalysisServicesAccount, Restart-AzureAnalysisServicesInstance, Login-AzureAsAccount, Restart-AzureAsInstance}                                
Script     3.1.0      Azure.Storage                       {Get-AzureStorageTable, New-AzureStorageTableSASToken, New-AzureStorageTableStoredAccessPolicy, New-AzureStorageTable...}                               
Script     2.8.0      Azure.Storage                       {Get-AzureStorageTable, New-AzureStorageTableSASToken, New-AzureStorageTableStoredAccessPolicy, New-AzureStorageTable...}                               
Script     0.2.3.8    AzureAutomationAuthoringToolkit     {Get-AutomationVariable, Get-AutomationCertificate, Get-AutomationPSCredential, Get-AutomationConnection...}                                            
Script     3.8.0      AzureRM                             {Get-AzureRmBackupItem, Get-AzureRmSqlDatabaseDataMaskingPolicy, Restart-AzureRmVM, Add-AzureRmVmssAdditionalUnattendContent...}                        
Script     0.2.0      AzureRM.AnalysisServices            {Resume-AzureRmAnalysisServicesServer, Suspend-AzureRmAnalysisServicesServer, Get-AzureRmAnalysisServicesServer, Remove-AzureRmAnalysisServicesServer...
Script     3.6.0      AzureRM.ApiManagement               {Add-AzureRmApiManagementRegion, Get-AzureRmApiManagementSsoToken, New-AzureRmApiManagementHostnameConfiguration, New-AzureRmApiManagementRegion...}    
Script     2.8.0      AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGroup, Get-AzureRmAutomationJobOutputRecord, Import-AzureRmAutomationDscNodeConfiguration, Export-AzureRmAutomation...
Script     2.8.0      AzureRM.Backup                      {Backup-AzureRmBackupItem, Enable-AzureRmBackupContainerReregistration, Get-AzureRmBackupContainer, Register-AzureRmBackupContainer...}                 
Script     2.8.0      AzureRM.Batch                       {Remove-AzureRmBatchAccount, Get-AzureRmBatchAccount, Get-AzureRmBatchAccountKeys, New-AzureRmBatchAccount...}                                          
Script     0.11.0     AzureRM.Billing                     {Get-AzureRmBillingInvoice, Login-AzureRmAccount, Select-AzureRmSubscription}                                                                           
Script     0.1.0      AzureRM.BootStrapper                {Update-AzureRmProfile, Uninstall-AzureRmProfile, Install-AzureRmProfile, Use-AzureRmProfile...}                                                        
Script     2.8.0      AzureRM.Cdn                         {Get-AzureRmCdnProfile, Get-AzureRmCdnProfileSsoUrl, New-AzureRmCdnProfile, Remove-AzureRmCdnProfile...}                                                
Script     0.6.0      AzureRM.CognitiveServices           {Get-AzureRmCognitiveServicesAccount, Get-AzureRmCognitiveServicesAccountKey, Get-AzureRmCognitiveServicesAccountSkus, New-AzureRmCognitiveServicesAc...
Script     2.9.0      AzureRM.Compute                     {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet, New-AzureRmAvailabilitySet, Update-AzureRmAvailabilitySet...}                               
Script     0.1.0      AzureRM.Consumption                 Get-AzureRmConsumptionUsageDetail                                                                                                                       
Script     0.1.0      AzureRM.ContainerRegistry           {New-AzureRmContainerRegistry, Get-AzureRmContainerRegistry, Update-AzureRmContainerRegistry, Remove-AzureRmContainerRegistry...}                       
Script     2.8.0      AzureRM.DataFactories               {Remove-AzureRmDataFactory, Get-AzureRmDataFactoryRun, Get-AzureRmDataFactorySlice, Save-AzureRmDataFactoryLog...}                                      
Script     2.8.0      AzureRM.DataLakeAnalytics           {Get-AzureRmDataLakeAnalyticsDataSource, New-AzureRmDataLakeAnalyticsCatalogCredential, Remove-AzureRmDataLakeAnalyticsCatalogCredential, Remove-Azur...
Script     3.6.0      AzureRM.DataLakeStore               {Get-AzureRmDataLakeStoreTrustedIdProvider, Remove-AzureRmDataLakeStoreTrustedIdProvider, Remove-AzureRmDataLakeStoreFirewallRule, Set-AzureRmDataLak...
Script     2.8.0      AzureRM.DevTestLabs                 {Get-AzureRmDtlAllowedVMSizesPolicy, Get-AzureRmDtlAutoShutdownPolicy, Get-AzureRmDtlAutoStartPolicy, Get-AzureRmDtlVMsPerLabPolicy...}                 
Script     2.8.0      AzureRM.Dns                         {Get-AzureRmDnsRecordSet, New-AzureRmDnsRecordConfig, Remove-AzureRmDnsRecordSet, Set-AzureRmDnsRecordSet...}                                           
Script     0.2.0      AzureRM.EventHub                    {New-AzureRmEventHubKey, Get-AzureRmEventHubNamespace, Get-AzureRmEventHubNamespaceAuthorizationRule, Get-AzureRmEventHubNamespaceKey...}               
Script     2.8.0      AzureRM.HDInsight                   {Get-AzureRmHDInsightJob, New-AzureRmHDInsightSqoopJobDefinition, Wait-AzureRmHDInsightJob, New-AzureRmHDInsightStreamingMapReduceJobDefinition...}     
Script     2.8.0      AzureRM.Insights                    {Get-AzureRmUsage, Get-AzureRmMetricDefinition, Get-AzureRmMetric, Remove-AzureRmLogProfile...}                                                         
Script     1.4.0      AzureRM.IotHub                      {Add-AzureRmIotHubKey, Get-AzureRmIotHubEventHubConsumerGroup, Get-AzureRmIotHubConnectionString, Get-AzureRmIotHubJob...}                              
Script     2.8.0      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Set-AzureKeyVaultCertificateAttribute, Stop-AzureKeyVaultCertificateOperation, Get-AzureKeyVaultCertificateOperation...} 
Script     2.8.0      AzureRM.LogicApp                    {Get-AzureRmIntegrationAccountAgreement, Get-AzureRmIntegrationAccountCallbackUrl, Get-AzureRmIntegrationAccountCertificate, Get-AzureRmIntegrationAc...
Script     0.13.0     AzureRM.MachineLearning             {Move-AzureRmMlCommitmentAssociation, Get-AzureRmMlCommitmentAssociation, Get-AzureRmMlCommitmentPlanUsageHistory, Remove-AzureRmMlCommitmentPlan...}   
Script     0.5.0      AzureRM.Media                       {Sync-AzureRmMediaServiceStorageKeys, Set-AzureRmMediaServiceKey, Get-AzureRmMediaServiceKeys, Get-AzureRmMediaServiceNameAvailability...}              
Script     3.7.0      AzureRM.Network                     {Add-AzureRmApplicationGatewayAuthenticationCertificate, Get-AzureRmApplicationGatewayAuthenticationCertificate, New-AzureRmApplicationGatewayAuthent...
Script     2.8.0      AzureRM.NotificationHubs            {Get-AzureRmNotificationHub, Get-AzureRmNotificationHubAuthorizationRules, Get-AzureRmNotificationHubListKeys, Get-AzureRmNotificationHubPNSCredentia...
Script     2.8.0      AzureRM.OperationalInsights         {New-AzureRmOperationalInsightsAzureActivityLogDataSource, New-AzureRmOperationalInsightsCustomLogDataSource, Disable-AzureRmOperationalInsightsLinux...
Script     2.8.0      AzureRM.PowerBIEmbedded             {Remove-AzureRmPowerBIWorkspaceCollection, Get-AzureRmPowerBIWorkspaceCollection, Get-AzureRmPowerBIWorkspaceCollectionAccessKeys, Get-AzureRmPowerBI...
Script     3.1.0      AzureRM.profile                     {Disable-AzureRmDataCollection, Enable-AzureRmDataCollection, Remove-AzureRmEnvironment, Get-AzureRmEnvironment...}                                     
Script     2.8.0      AzureRM.profile                     {Disable-AzureRmDataCollection, Enable-AzureRmDataCollection, Remove-AzureRmEnvironment, Get-AzureRmEnvironment...}                                     
Script     2.8.0      AzureRM.RecoveryServices            {Get-AzureRmRecoveryServicesBackupProperties, Get-AzureRmRecoveryServicesVault, Get-AzureRmRecoveryServicesVaultSettingsFile, New-AzureRmRecoveryServ...
Script     2.8.0      AzureRM.RecoveryServices.Backup     {Backup-AzureRmRecoveryServicesBackupItem, Get-AzureRmRecoveryServicesBackupManagementServer, Get-AzureRmRecoveryServicesBackupContainer, Unregister-...
Script     2.8.0      AzureRM.RedisCache                  {Remove-AzureRmRedisCachePatchSchedule, New-AzureRmRedisCacheScheduleEntry, Get-AzureRmRedisCachePatchSchedule, New-AzureRmRedisCachePatchSchedule...}  
Script     0.1.0      AzureRM.Relay                       {New-AzureRmRelayNamespace, Get-AzureRmRelayNamespace, Set-AzureRmRelayNamespace, Remove-AzureRmRelayNamespace...}                                      
Script     4.1.0      AzureRM.Resources                   {Get-AzureRmProviderOperation, Remove-AzureRmRoleAssignment, Get-AzureRmRoleAssignment, New-AzureRmRoleAssignment...}                                   
Script     3.8.0      AzureRM.Resources                   {Get-AzureRmProviderOperation, Remove-AzureRmRoleAssignment, Get-AzureRmRoleAssignment, New-AzureRmRoleAssignment...}                                   
Script     0.13.0     AzureRM.Scheduler                   {Disable-AzureRmSchedulerJobCollection, Enable-AzureRmSchedulerJobCollection, Get-AzureRmSchedulerJobCollection, Get-AzureRmSchedulerJob...}            
Script     2.8.0      AzureRM.ServerManagement            {Invoke-AzureRmServerManagementPowerShellCommand, Get-AzureRmServerManagementSession, New-AzureRmServerManagementSession, Remove-AzureRmServerManagem...
Script     0.2.0      AzureRM.ServiceBus                  {Get-AzureRmServiceBusTopic, Get-AzureRmServiceBusTopicAuthorizationRule, Get-AzureRmServiceBusTopicKey, New-AzureRmServiceBusTopic...}                 
Script     0.1.0      AzureRM.ServiceFabric               {Add-AzureRmServiceFabricApplicationCertificate, Add-AzureRmServiceFabricClientCertificate, Add-AzureRmServiceFabricClusterCertificate, Add-AzureRmSe...
Script     4.0.0      AzureRM.SiteRecovery                {Get-AzureRmSiteRecoveryFabric, New-AzureRmSiteRecoveryFabric, Remove-AzureRmSiteRecoveryFabric, Stop-AzureRmSiteRecoveryJob...}                        
Script     3.7.0      AzureRM.SiteRecovery                {Get-AzureRmSiteRecoveryFabric, New-AzureRmSiteRecoveryFabric, Remove-AzureRmSiteRecoveryFabric, Stop-AzureRmSiteRecoveryJob...}                        
Script     2.8.0      AzureRM.Sql                         {Get-AzureRmSqlDatabaseTransparentDataEncryption, Get-AzureRmSqlDatabaseTransparentDataEncryptionActivity, Set-AzureRmSqlDatabaseTransparentDataEncry...
Script     2.8.0      AzureRM.Storage                     {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, New-AzureRmStorageAccount, New-AzureRmStorageAccountKey...}                                   
Script     2.8.0      AzureRM.StreamAnalytics             {Get-AzureRmStreamAnalyticsFunction, Get-AzureRmStreamAnalyticsDefaultFunctionDefinition, New-AzureRmStreamAnalyticsFunction, Remove-AzureRmStreamAna...
Script     2.8.0      AzureRM.Tags                        {Remove-AzureRmTag, Get-AzureRmTag, New-AzureRmTag, Login-AzureRmAccount...}                                                                            
Script     2.8.0      AzureRM.TrafficManager              {Disable-AzureRmTrafficManagerEndpoint, Enable-AzureRmTrafficManagerEndpoint, Set-AzureRmTrafficManagerEndpoint, Get-AzureRmTrafficManagerEndpoint...}  
Script     2.8.0      AzureRM.UsageAggregates             {Get-UsageAggregates, Login-AzureRmAccount, Select-AzureRmSubscription}                                                                                 
Script     2.8.0      AzureRM.Websites                    {Get-AzureRmAppServicePlan, Set-AzureRmAppServicePlan, New-AzureRmAppServicePlan, Remove-AzureRmAppServicePlan...}                                      
Manifest   1.0.0.7    AzureRmStorageTable                 {Add-StorageTableRow, Get-AzureStorageTableRowAll, Get-AzureStorageTableRowByPartitionKey, Get-AzureStorageTableRowByColumnName...}                     
Script     1.0.1      Microsoft.PowerShell.Operation.V... {Get-OperationValidation, Invoke-OperationValidation}                                                                                                   
Script     1.3.3      NuGet                                                                                                                                                                                       
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}                                                                                  
Script     3.4.0      Pester                              {Describe, Context, It, Should...}                                                                                                                      
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}                                                                                            
Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Set-PSReadlineKeyHandler, Remove-PSReadlineKeyHandler, Get-PSReadlineOption...}

**Comment by RBACAsk** [comment]
+ Mark, Abhijeet

This looks like an issue with installing a new version of Azure PowerShell on top of existing one.

One option could be to uninstall the current version and then install the latest version on your machine.

Thx
Surabhi

**Comment by RBACAsk** [comment]
‘Azure’ is the module that contains RDFE cmdlets. ‘AzureRM’ is the module that contains ARM cmdlets (and AD cmdlets).  You want to make sure you have the latest version for the ARM module installed.

You can safely remove the folders under Program Files\WindowsPowerShell\Modules\Azure*  and re-install AzureRM.

From: Surabhi Pandey
Sent: Tuesday, June 13, 2017 10:31 AM
To: Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com>; Mark Cowlishaw <Mark.Cowlishaw@microsoft.com>; Abhijeet Shah <Abhijeet.Shah@microsoft.com>
Cc: RBAC Ask <RBACAsk@microsoft.com>; Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-powershell] New-AzureRmADApplication: Access denied to the specified API version (#1896)

+ Mark, Abhijeet

This looks like an issue with installing a new version of Azure PowerShell on top of existing one.

One option could be to uninstall the current version and then install the latest version on your machine.

Thx
Surabhi

**Comment by SquirrelAssassin** [comment]
Its working now, thanks for the feedback folk!

**Comment by Akshat59** [comment]
> @winperec We have reproduced this internally - ths ieeus is that third party applications (service principal) are not allowed to use version 1.6-interna;l of the graph library. Will need to update the graph library version to enable this scenario

Please clarify how to resolve this issue - Getting error while using Get-AzureRmADApplication
