### ISSUE TITLE
Connect-AzAccount hangs

### ISSUE THREAD

**Issue by ville87** [Azure/azure-powershell#19790]
### Description

I built a script which connects to Azure using the `Connect-AzAccount -TenantID <tenantID>` command. 
However, it often hangs after providing the (valid) credentials in the credential popup...
Sometimes it works, but most often it hangs.
I tried on a freshly installed Windows 11 with all Windows Updates, where I installed the Az module from scratch (from PSGallery) and there the same issue often appears.

### Issue script & Debug output

```PowerShell
PS C:\users\bob> .\testing.ps1 -tenantID $tenantid
DEBUG: connecting with Connect-AzAccount to tenant xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
DEBUG: Sought all Az modules and got latest version 0.0.0
DEBUG: 2:54:55 PM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.
DEBUG: 2:54:55 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 2:54:55 PM - [ConfigManager] Got nothing from [DefaultSubscriptionForLogin], Module = [], Cmdlet = []. Returning default value [].
DEBUG: 2:54:55 PM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 2:54:55 PM - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 2:54:55 PM - Using Autosave scope 'CurrentUser'
```

### Environment data

```PowerShell
PS C:\users\bob> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PS C:\users\bob> Get-Module Az*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.10.1     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}
```

### Error output

```PowerShell
No errors in Resolve-AzError, since the console hangs and has to be restarted.
```

**Comment by dingmeng-xue** [comment]
@ville87 , thanks for your reporting. I suspect there is problem in [Microsoft Authentication Library (MSAL)](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-overview). We just released the new version of Az.Accounts 2.10.2 which includes the new version of MSAL and its dependencies. Could you try that again? 

If issue is still there, please turn on the log via `$DebugPreference = "Continue"` and share us the message. In addition, was Windows 11 installed on local machine? or on cloud?

**Comment by ville87** [comment]
Hi @dingmeng-xue, I installed the new version but same issue still appears :( 
**Debug output**
```
DEBUG: connecting with Connect-AzAccount to tenant ab42bedf-5b05-463e-bb7f-d03b4ea4403d
DEBUG: Sought all Az modules and got latest version 0.0.0
DEBUG: 8:36:57 AM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.
DEBUG: 8:36:57 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 8:36:57 AM - [ConfigManager] Got nothing from [DefaultSubscriptionForLogin], Module = [], Cmdlet = []. Returning default value [].
DEBUG: 8:36:57 AM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 8:36:57 AM - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 8:36:57 AM - Using Autosave scope 'CurrentUser'
```
**Modules**
```
PS C:\Users\bob> get-module -ListAvailable Az*


    Directory: C:\Users\bob\Documents\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.10.2     Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}
Script     3.12.0     Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlDatabaseTransparentDataEncryption, Get-AzS...


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     2.0.2.140  AzureAD                             {Add-AzureADApplicationOwner, Get-AzureADApplication, Get-AzureADApplicationExtensionProperty, Get-AzureADApplicationOwner...}
```
My Windows 11 installation is in a VMWare Workstation VM on my local notebook.

**Comment by ville87** [comment]
I did some more testing and ran ProcMon while doing so. 
It seems, that when I remove the "Az.Sql" module from being imported, it does not hang anymore... 

My code responsible for loading the modules looks as follows:

```
[array]$requiredModules         = @("Az.Accounts","Az.Sql")
[ ... ]
foreach($module in $requiredModules){
            if ($module -notin $installedModules.Name) {
                $missingmodules += $module
                $prerequisites = $false
            }
        }
        if($prerequisites -eq $true){
            foreach($module in $requiredModules){
                Import-Module $module
            }
        }else{
            # Required modules are not installed, informing the user and canceling script
            $listmodules = $missingmodules -join ","
            Write-host "The script cannot continue, because following modules are missing: $listmodules. `r`nPlease install them first and restart the PowerShell console."
            Write-host "The script will exit in 10 seconds..."
            Start-Sleep -Seconds 10
            Exit 2
        }
        
        ################### Connect and get token ###################
        if(($null -eq $tenantID) -or ($tenantID -eq "")){
            $tenantId = Read-host "Please provide the tenant Id"
        }

        Connect-AzAccount -TenantID $tenantId
```

**Comment by dingmeng-xue** [comment]
@ville87 , According to debug log, it seems `Connect-AzAccount` is hanging and waiting browser popping up for interactive login. Browser showing up depends on .NET Framework API. So far, I don't have idea which part blocks this logic. I looked into Sql module but don't find special setting in Az.Sql. Could you try below 2 approaches.

1. Please use `Connect-AzAccount -DeviceCode` to switch logic approach,
2. Could you try PowerShell 7 on your machine?

**Comment by ville87** [comment]
Looks like with the `-DeviceCode` approach, the issue does not appear. I didn't make a lot of test runs though...
You can close this if you want, I have my workaround with importing the Az.Sql later on in the script.
Thanks for your help!

**Comment by dingmeng-xue** [comment]
Thanks @ville87 , this kind of issue normally relates to environment. It's hard to collect more information. I will close it now. 

Please let us know if you meet issue again in other machines.
