### ISSUE TITLE
Search-AzDataProtectionBackupInstanceInAzGraph fails in App Service

### ISSUE THREAD

**Issue by bwarren18** [Azure/azure-powershell#20391]
### Description

Hello, I am trying to use Search-AzDataProtectionBackupInstanceInAzGraph in an App Service WebJob.  
It works fine running in PowerShell 5.1 but not in the App Service.

```
$env:PSModulePath = $null
$modulesPath = 'D:\home\site\wwwroot\Modules\'
$env:PSModulePath = $env:PSModulePath + "$([System.IO.Path]::PathSeparator)$modulesPath"
Import-Module Az.Accounts, Az.DataProtection, Az.ResourceGraph -PassThru

$SubscriptionId = 'xxx-xxx-xxx-xxx-xxx'
Connect-AzAccount -Identity
Set-AzContext -Subscription $SubscriptionId 

$DebugPreference = 'Continue'
Search-AzDataProtectionBackupInstanceInAzGraph -Subscription $SubscriptionId -DatasourceType AzureDisk
```

### Issue script & Debug output

```PowerShell
ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Script     2.10.4     Az.Accounts                         {Add-AzEnvironment...
Script     1.0.1      Az.DataProtection                   {Backup-AzDataProt...
Script     0.13.0     Az.ResourceGraph                    {Search-AzGraph, G...

Environments : {[AzureChinaCloud, AzureChinaCloud], [AzureCloud, AzureCloud], 
               [AzureUSGovernment, AzureUSGovernment]}
Context      : Microsoft.Azure.Commands.Profile.Models.Core.PSAzureContext


Name               : xxx 
                     (xxx) - 
                     xxx - MSI@xxx
Account            : MSI@xxx
Environment        : AzureCloud
Subscription       : xxx
Tenant             : xxx
TokenCache         : 
VersionProfile     : 
ExtendedProperties : {}

Az.ResourceGraph Module must be installed to run this command. Please run 
'Install-Module -Name Az.ResourceGraph' to install and continue.
At D:\home\site\wwwroot\Modules\Az.DataProtection\1.0.1\custom\Helpers\Backupce
nterHelper.ps1:113 char:13
+             throw $message
+             ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Az.ResourceGrap...l and conti 
   nue.:String) [], RuntimeException
    + FullyQualifiedErrorId : Az.ResourceGraph Module must be installed to run 
    this command. Please run 'Install-Module -Name Az.ResourceGraph' to insta  
  ll and continue.
```

### Environment data

```PowerShell
Name                           Value                                           
----                           -----                                           
PSVersion                      5.1.14393.5127                                  
PSEdition                      Desktop                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   10.0.14393.5127                                 
CLRVersion                     4.0.30319.42000                                 
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Script     2.10.4     Az.Accounts                         {Add-AzEnvironment...
Script     1.0.1      Az.DataProtection                   {Backup-AzDataProt...
Script     0.13.0     Az.ResourceGraph                    {Search-AzGraph, G...
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will look into this issue.

**Comment by dingmeng-xue** [comment]
@bwarren18 , Please check output of `Get-InstalledModule | Where-Object { $_.Name -eq "Az.ResourceGraph" }` If script returns null, please install  `Az.ResourceGraph` again on your PowerShell. If result is not null but your script still has problem, please share the output.

**Comment by dingmeng-xue** [comment]
PowerShellGet is the problem. Please upgrade its version. I mark this issue is addressed. Feel free to contact us if there is further issue.

**Comment by bwarren18** [comment]
/unresolve

Hello,
I added the latest PowerShellGet and loaded the module, however the issue is still occurring.

Here is my test code:
```
$env:PSModulePath = $null
$modulesPath = 'D:\home\site\wwwroot\Modules\'
$env:PSModulePath = $env:PSModulePath + "$([System.IO.Path]::PathSeparator)$modulesPath"
	
Get-Command Get-InstalledModule | FT Version,Name,Source
Import-Module Az.Accounts, Az.DataProtection, Az.ResourceGraph, PowerShellGet -PassThru | Select ModuleType,Version,Name
Get-InstalledModule | Where-Object { $_.Name -eq "Az.ResourceGraph" }

$SubscriptionId = 'xxx-xx-xx-xx-xxx'
Connect-AzAccount -Identity
Set-AzContext -Subscription $SubscriptionId

$DebugPreference = 'Continue'
Search-AzDataProtectionBackupInstanceInAzGraph -Subscription $SubscriptionId -DatasourceType AzureDisk
```

Here is the output:
```
Version Name                Source       
------- ----                ------       
2.2.5   Get-InstalledModule PowerShellGet



ModuleType Version Name             
---------- ------- ----             
    Script 2.10.4  Az.Accounts      
    Script 1.0.1   Az.DataProtection
    Script 0.13.0  Az.ResourceGraph 
    Script 2.2.5   PowerShellGet    




Environments : {[AzureChinaCloud, AzureChinaCloud], [AzureCloud, AzureCloud], 
               [AzureUSGovernment, AzureUSGovernment]}
Context      : Microsoft.Azure.Commands.Profile.Models.Core.PSAzureContext





Name               : xxx
                     (xxx-xxx-xxx-xxx-xxx) - 
                     xxx-xxx-xxx-xxx-xxx- MSI@xxx
Account            : MSI@xxx
Environment        : AzureCloud
Subscription       : xxx-xxx-xxx-xxx-xxx
Tenant             : xxx-xxx-xxx-xxx-xxx
TokenCache         : 
VersionProfile     : 
ExtendedProperties : {}



Az.ResourceGraph Module must be installed to run this command. Please run 
'Install-Module -Name Az.ResourceGraph' to install and continue.
At D:\home\site\wwwroot\Modules\Az.DataProtection\1.0.1\custom\Helpers\Backupce
nterHelper.ps1:113 char:13
+             throw $message
+             ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Az.ResourceGrap...l and conti 
   nue.:String) [], RuntimeException
    + FullyQualifiedErrorId : Az.ResourceGraph Module must be installed to run 
    this command. Please run 'Install-Module -Name Az.ResourceGraph' to insta  
  ll and continue.
 
```

**Comment by AnatoliB** [comment]
Azure Functions are also impacted. However, https://github.com/Azure/azure-powershell/pull/20786 most likely fixes the issue, as it replaces `Get-InstalledModule` with `Get-Module -ListAvailable`.

**Comment by hiaga** [comment]
@bwarren18, @AnatoliB - Ack, we're looking into this

**Comment by hiaga** [comment]
@dingmeng-xue :  like suggested before we are using `Get-Module -ListAvailable | Where-Object { $_.Name -eq "Az.ResourceGraph" }` to check if the module is installed instead of Get-InstalledModule. Can you please guide further

**Comment by hiaga** [comment]
@AnatoliB We had made a fix for this. Can you please check if this issue is occurring now or if we can close this.

**Comment by Daya-Patil** [comment]
Closing as have not received update and we have fixed the issue

**Comment by Daya-Patil** [comment]
Closing as have not received update and we have fixed the issue

**Comment by bwarren18** [comment]
Hello, this appears to be fixed.  
I tested with Az 11.2.0 and it ran without the error in the AppService WebJob.
Thank you.
