### ISSUE TITLE
The output object type of this cmdlet will be modified in a future release.

### ISSUE THREAD

**Issue by ckarras** [Azure/azure-powershell#2206]
I'm running a script that uses several Azure PowerShell commands (for example Get-AzureRmResourceGroup) which display this warning: "The output object type of this cmdlet will be modified in a future release.". This warning is not useful, it's only suggesting that there will be new breaking changes at an undetermined time but does not say what changes I can do to avoid these breaking changes.

The warnings have been added in https://github.com/Azure/azure-powershell/commit/80ca021a1a3cec1840574dc1e0651c5b68335e3d

**Comment by markcowl** [comment]
@ckarras Sorry you didn't find that helpful.  Our release cadence is on the first Wednesday of each month, and since we use semantic versioning, you should be able to avoid consuming breaking changes using version dependencies.

**Comment by ckarras** [comment]
Do you have any references on what kind of changes are planned for these commands?

How should I enforce version dependencies? Is there a standard way to declare a script's dependencies and declare that any version >= 1.3.0 < 2.0 should be used? How can multiple versions of Azure Powershell be deployed side-by-side? (According to https://azure.microsoft.com/en-us/documentation/articles/powershell-install-configure/, " If you have Azure PowerShell 0.9.x installed, version 0.9.x will be uninstalled as part of the upgrade. ")

More generally, I don't think this message should be reported as a warning. A warning should usually be for something for which an action can be done to resolve the warning. Otherwise it tends to cause a proliferation of ignored warnings. Is there an alternate set of commands I should be using? If there is, the warning should state the alternative. If there is not, the warning should be introduced once the alternative is available. Breaking changes (removal of obsolete features) should then be done only if the major version number increases, but for a major technology like Azure, there needs to be some transition period - modifying all scripts for all incompatibilities is not something that can be done all at once. This becomes worse once we start depending on other scripts that themselves depend on older versions of Azure Powershell. For example Azure IoT Suite's script only recently became compatible with version 1.x.

**Comment by gregjhogan** [comment]
@markcowl please explain the desired effect of introducing this warning (what do you want people to do when they see it?).  Thanks!

**Comment by lawrencegripper** [comment]
@markcowl I second this can you provide some reference to docs on what will change? The output object is core to a release pipeline I use. 

It's running in Release Manager in VSTS and there doesn't appear to be anyway to set the Azure Powershell task to use a specific version of the AzureRM cmdlets so semantic version doesn't help me :(

**Comment by ravbhatnagar** [comment]
@lawrencegripper @ckarras  - This particular change is for the Resource Group and Resource Group Deployment cmdlets where the output object will change to the standard PSObject from the current type which is a custom object (PSResourceGroup and PSResourceGroupDeployment respectively). 

I understand that although the current warning lets customers know about an upcoming breaking change, it doesn't help them understand what the change will be, when will it be done and how they can prepare for the change. If we need to make any such breaking changes in future, we will handle it better in future and keep in mind the above feedback. 

If there is any other feedback around this, please share. Apologize for any inconvenience this has caused.

**Comment by ravbhatnagar** [comment]
This has been addressed. Going forward we have stricter criteria to control shipping breaking changes and also limit the frequency of breaking changes for PowerShell releases. 

In case there are going to be breaking changes, we will give better information about the upcoming breaking changes. We have already started providing migration guides for breaking changes - https://github.com/Azure/azure-powershell/tree/dev/documentation/release-notes 

Please let us know if you have more feedback on this.

**Comment by ckarras** [comment]
In PowerShell on the Azure portal, I still get this warning using some commands, for example New-AzureRmNetworkInterface

**Comment by smharishbabu** [comment]
I got warning for New-AzureRmPublicIpAddress and few other commands
