### ISSUE TITLE
Get-AzVMRunCommand and Get-AzVmssVMRunCommand without -RunCommandName parameter fails to return list of RunCommands on VM

### ISSUE THREAD

**Issue by vivlingaiah** [Azure/azure-powershell#22403]
### Description

-Get-AzVMRunCommand without -RunCommandName parameter fails to return list of RunCommands on VM
- Looks like this is a regression. This used to work

### Issue script & Debug output

```PowerShell
PS C:\> Get-AzVMRunCommand -ResourceGroupName VivRG0 -VMName VivL
Get-AzVMRunCommand : Unable to cast object of type 'Microsoft.Azure.Management.Compute.Models.PSVirtualMachineRunCommand' to type
'Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineRunCommandList'.
At line:1 char:1
+ Get-AzVMRunCommand -ResourceGroupName VivRG0 -VMName VivL
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzVMRunCommand], InvalidCastException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.GetAzureVmRunCommand

PS C:\> Get-AzVmssVMRunCommand -ResourceGroupName VivRG0 -VMScaleSetName VivVMSS -InstanceId 0
Get-AzVmssVMRunCommand : Unable to cast object of type 'Microsoft.Azure.Management.Compute.Models.PSVirtualMachineRunCommand' to type
'Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineRunCommandList'.
At line:1 char:1
+ Get-AzVmssVMRunCommand -ResourceGroupName VivRG0 -VMScaleSetName VivV ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzVmssVMRunCommand], InvalidCastException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.GetAzureVmssVMRunCommand
```

### Environment data

```PowerShell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22000.2003
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.2003
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
10.0.1
```

### Error output

```PowerShell
PS C:\> Get-AzVMRunCommand -ResourceGroupName VivRG0 -VMName VivL
Get-AzVMRunCommand : Unable to cast object of type 'Microsoft.Azure.Management.Compute.Models.PSVirtualMachineRunCommand' to type
'Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineRunCommandList'.
At line:1 char:1
+ Get-AzVMRunCommand -ResourceGroupName VivRG0 -VMName VivL
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzVMRunCommand], InvalidCastException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.GetAzureVmRunCommand

PS C:\> Get-AzVmssVMRunCommand -ResourceGroupName VivRG0 -VMScaleSetName VivVMSS -InstanceId 0
Get-AzVmssVMRunCommand : Unable to cast object of type 'Microsoft.Azure.Management.Compute.Models.PSVirtualMachineRunCommand' to type
'Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineRunCommandList'.
At line:1 char:1
+ Get-AzVmssVMRunCommand -ResourceGroupName VivRG0 -VMScaleSetName VivV ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzVmssVMRunCommand], InvalidCastException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.GetAzureVmssVMRunCommand
```

**Comment by Chris-Sanford** [comment]
Terminating existing PowerShell sessions and starting a new PowerShell process seems to be an effective workaround for this bug. Tested in the latest PowerShell Core and Az Module versions.

**Comment by TravisCragg-MSFT** [comment]
assigning to @nikhilpatel909

**Comment by nikhilpatel909** [comment]
@grizzlytheodore was this bug fixed?

**Comment by GabstaMSFT** [comment]
@grizzlytheodore checking if issue is now resolved for you?

**Comment by grizzlytheodore** [comment]
@nikhilpatel909  @GabstaMSFT  hello. this bug was resolved so I will close this issue

**Comment by RobertMochnacky** [comment]
Good morning,

I'm still experiencing the same issue to get the list of VM AzVMRunCommands without specifying RunCommandName parameter when the code runs as part of the powershell function in a function app.  It works on occasional basis but not bale to identify a pattern when it works and when not. The most of the time it fails with the following message:

Code:
===========================================================================================================================================================================
param($Timer)

Set-AzContext -SubscriptionId $env:APPSETTING_SubscriptionId
$timeout = 30
$VMs = Get-AzVM -Status | Where-Object {$_.Tags['solution'] -eq 'SolutionName' -and $_.PowerState -eq "VM running"} # Get All Running VMs in the selected subscription which match solution:SolutionName Tag
Start-Sleep 5

if ($VMs -eq $null) {
    Write-Error "No VMs have been found. Please check whether the proper tag solution:SolutionName is present on the workload(s)"
    exit
}
foreach ($VM in $VMs) {
    Write-Information "Loading existing AzVMRunCommands for $($VM.Name)..."
    $existingCMDs = Get-AzVMRunCommand -ResourceGroupName $($VM.ResourceGroupName) -VMName $($VM.Name)
    if ($?) {
        Write-Information "Existing AzVMRunCommands for $($VM.Name) loaded sucessfuly."
    }
    else {
        Write-Error "Loading AzVMRunCommands for $($VM.Name) failed. Error: $Error[0].Exception.Message"
        exit
    }
}
===========================================================================================================================================================================

Output:
===========================================================================================================================================================================
ERROR: Unable to cast object of type 'Microsoft.Azure.Management.Compute.Models.PSVirtualMachineRunCommand' to type 'Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineRunCommandList'. Exception : Type : System.InvalidCastException TargetSite : Name : ChkCast_Helper DeclaringType : System.Runtime.CompilerServices.CastHelpers, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e MemberType : Method Module : System.Private.CoreLib.dll Message : Unable to cast object of type 'Microsoft.Azure.Management.Compute.Models.PSVirtualMachineRunCommand' to type 'Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineRunCommandList'. Source : System.Private.CoreLib HResult : -2147467262 StackTrace : at lambda_method6013(Closure , VirtualMachineRunCommand , PSVirtualMachineRunCommandList , ResolutionContext ) at AutoMapper.Mapper.AutoMapper.IMapper.Map[TSource,TDestination](TSource source) at Microsoft.Azure.Commands.Compute.Automation.GetAzureVmRunCommand.<ExecuteCmdlet>b__16_0() at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action) at Microsoft.Azure.Commands.Compute.Automation.GetAzureVmRunCommand.ExecuteCmdlet() at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c) at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor) at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet) at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord() CategoryInfo : CloseError: (:) [Get-AzVMRunCommand], InvalidCastException FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.GetAzureVmRunCommand InvocationInfo : MyCommand : Get-AzVMRunCommand ScriptLineNumber : 18 OffsetInLine : 21 HistoryId : 1 ScriptName : C:\home\site\wwwroot\CarloAzVmRunCommand_Cleanup\run.ps1 Line : $existingCMDs = Get-AzVMRunCommand -ResourceGroupName $($CarloVM.ResourceGroupName) -VMName $($CarloVM.Name) PositionMessage : At C:\home\site\wwwroot\CarloAzVmRunCommand_Cleanup\run.ps1:18 char:21 + … stingCMDs = Get-AzVMRunCommand -ResourceGroupName $($CarloVM.Resource … + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\CarloAzVmRunCommand_Cleanup PSCommandPath : C:\home\site\wwwroot\CarloAzVmRunCommand_Cleanup\run.ps1 InvocationName : Get-AzVMRunCommand CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\CarloAzVmRunCommand_Cleanup\run.ps1: line 18 PipelineIterationInfo :

===========================================================================================================================================================================

Settings:

Function app settings:
PowerShell Core Version: 7.2
Platform: 32bit
Runtime version: ~4

Hosts.json:
{
  "version": "2.0",
  "managedDependency": {
    "Enabled": true
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.*, 5.0.0)"
  }
}

requirements.psd1:
'Az' = '10.*'

Thank you in advance.

**Comment by grizzlytheodore** [comment]
I am able to retrieve a list of RunCommands: 
![image](https://github.com/Azure/azure-powershell/assets/10857691/1657b699-d897-4844-bd81-1021e4e5ea71)

**Comment by grizzlytheodore** [comment]
@RobertMochnacky, could you make sure you are running the latest version by running "update-module az" ? 
then you will need to start a new powershell session to use the latest package

**Comment by RobertMochnacky** [comment]
Hello guys,
The command works well in the powershell session but the problem I reported occurs as part of the Powershell Function in a Function app.
I have also changed the module definition in the function app from 10.* to 11.* but still got the error mentioned earlier now and then.

**Comment by grizzlytheodore** [comment]
@nikhilpatel909  could we get the above issue routed to ps functions?

**Comment by RobertMochnacky** [comment]
Addition based on the recent findings: 
I have two PowerShell Functions:
1. The function to find all VMs with as specific tag and Set the AzVMRunCommand for each VM, It waits 2 minutes or until the provisioning status of the Set-AzVMRunCommand is "Succeeded" then Remove AzVMRunCommand. This is schedule to run every 5 minutes. Each AzRUnCommand has its own name with start time tag in it. It sometimes happens that the removal of the command does not succeed and the AzVMRunCommand stays there. In order to avoid hitting the maximum nr. of AzVMRunCommand per VM (25) there is another function...

2. The function finds the AzVMRunCommands for each VM and checks the timestamp in the AzVMRunCommand name. If it is older than 30 minutes, the run command gets deleted by the function.

 The problem I've described in the previous posts only happens when the 1st and 2nd function is in the same Function App. As soon as I move the 2nd Function to a separate function app it works all the time.
