### ISSUE TITLE
Unable to get the list of patches while running Invoke-AzVMPatchAssessment

### ISSUE THREAD

**Issue by subhendu-de** [Azure/azure-powershell#25123]
### Description

I'm using [Invoke-AzVMPatchAssessment](https://learn.microsoft.com/en-us/powershell/module/az.compute/invoke-azvmpatchassessment?view=azps-12.0.0) to retrieve the list of pending patches in an Azure VM. As per the documentation, it returns [PSVirtualMachinePatchAssessmentResult](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.compute.automation.models.psvirtualmachinepatchassessmentresult?view=az-ps-latest)  containing a [Patches ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.compute.automation.models.psvirtualmachinepatchassessmentresult.patches?view=az-ps-latest#microsoft-azure-commands-compute-automation-models-psvirtualmachinepatchassessmentresult-patches) property. 

However running the Invoke-AzVMPatchAssessment returns empty/null Patches property while CriticalAndSecurityPatchCount is more than 1.

![image](https://github.com/Azure/azure-powershell/assets/13384157/2d3487b7-ad21-43fd-8448-3d26d49ff062)

Shouldn't it return a list of pending patches in the Patches property?

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
12.0.0               Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This module is c…
```

**Comment by Drewm3** [comment]
@hilaryw29, could you please work with Maulik to debug this issue?

**Comment by maulikshah23** [comment]
This seems to be an issue with PowerShell, as the API is returning the Patch information. I'll escalate this to the PS team.

**Comment by hilaryw29** [comment]
Hi @haagha, just checking on the pull request linked #25714 . Do you know if there's any updates? Or if this issue is already resolved? Thanks!

**Comment by MohSayed1** [comment]
Hello Team, the issues still exists in my side. 
Is there any progress for this bug?
