### ISSUE TITLE
[Doc]: Need help in updating the powershell command - https://learn.microsoft.com/en-us/powershell/module/az.network/set-azprivatelinkservice?view=azps-12.1.0#example-1-creates-a-private-link-service-and-update-its

### ISSUE THREAD

**Issue by Ravi2305** [Azure/azure-powershell#25661]
### Type of issue

Code doesn't work

### Feedback

Ask:
This document [Set-AzPrivateLinkService (Az.Network) | Microsoft Learn](https://learn.microsoft.com/en-us/powershell/module/az.network/set-azprivatelinkservice?view=azps-12.1.0) has mention of an example where private link service is created and its ipconfig is updated. In this example command to get public IP is incorrect, its highlighted in screenshot below
 
 
Command - $publicip = Get-AzPublicIpAddress -ResourceGroupName "myresourcegroup"
This command is fetching all public IP addresses present in resource group, due to which when we associate to frontend of Load Balancer, it throws an error -
 
 
Correct Command - **$publicip = **Get-AzPublicIpAddress -Name myPublicIp1 -ResourceGroupName "myresourcegroup"****
 
 
So, modifications need to be done from **$publicip = Get-AzPublicIpAddress -ResourceGroupName "myresourcegroup"** to _**Get-AzPublicIpAddress -Name myPublicIp1 -ResourceGroupName "myresourcegroup"**_

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.network/set-azprivatelinkservice?view=azps-12.1.0

### Content source URL

https://learn.microsoft.com/en-us/powershell/module/az.network/set-azprivatelinkservice?view=azps-12.1.0#example-1-creates-a-private-link-service-and-update-its

**Comment by Ravi2305** [comment]
**Reference error messages**

![image](https://github.com/user-attachments/assets/a34e7204-91e5-4ad1-9bd9-965541d6db57)

![image](https://github.com/user-attachments/assets/e9fe4c3f-02b5-4d91-be3b-733a4776e5ce)

![image](https://github.com/user-attachments/assets/eb2be80e-15d2-4f77-981f-e113bf50a65c)

**Comment by duongau** [comment]
Hello @Ravi2305 This has been resolved. #please-close

**Comment by Ravi2305** [comment]
[heart]         Ravi Kumar Krishnamurthy reacted to your message:
________________________________

**Comment by Ravi2305** [comment]
@duongau the document is still not updated with the correct command, could you please recheck? $publicip = Get-AzPublicIpAddress -ResourceGroupName "myresourcegroup" 

Correct Command Is- $publicip = Get-AzPublicIpAddress -Name myPublicIp1 -ResourceGroupName "myresourcegroup"

**Comment by duongau** [comment]
Hi Ravi, if you click on the pencil on the top right, you'll see that it has been updated in GitHub: 
![image](https://github.com/user-attachments/assets/d45ab853-0349-4440-a774-e372abee6f36)
I will need to check with the PS team to understand why it hasn't reflect on the live website.

**Comment by duongau** [comment]
#please-close
