### ISSUE TITLE
Fix concurrency issues with DelegatingHandlers and Actions in ClientFactory

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2701]
### Description
The Client Factory uses unsychronized data structures to hold DeleagtingHandlers and ClientActions used in creating clients, and, since this is a static class, these may be added to and removed from by multiple threads, producing Null Reference, ArgumentOurfRange exceptions, or Eunmeration exceptions.

Since the collections are too complex to use the framework-provided concurrent collections, use lightweight reader-writer locks to ensure exclusive locks for writing and shared locks for reading data

- [x] Stress test that finds the appropriate issues
- [x] Implement Reader/Writer locks

### Cost: 4

**Comment by markcowl** [comment]
Candidate fix is here: https://github.com/markcowl/azure-powershell/commit/9996fab154c8aea9f71c3e5ddb5bf158a0cb3f37

**Comment by markcowl** [comment]
Fixed

**Comment by raandree** [comment]
I am still having this issue. When invoking Get-AzureRmVM there are two issues:

- Index was out of range. Must be non-negative and less than the size of the collection.
- The entity was not found.

This happens when calling Get-AzureRmVM -Status after removing a resource group that has VMs.

**Comment by ward0** [comment]
Having same problem still, but not every day.. very hard to debug..

**Comment by raandree** [comment]
You can reproduce this when deleting a resource group with VMs and in parallel create new ones. We faced this when testing [AutomatedLab](https://github.com/AutomatedLab/AutomatedLab).
