### ISSUE TITLE
Unable to import module AzureRM.ServiceBus in 3.4.0 but it works in 3.3.0

### ISSUE THREAD

**Issue by wangzq** [Azure/azure-powershell#3443]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by markcowl** [comment]
@wangzq What failure output do you see when attempting this?

**Comment by wangzq** [comment]
```
PS C:\Users\wangzq> Import-Module AzureRM.ServiceBus
Import-Module : The member 'FormatsToProcess' in the module manifest is not valid: Cannot find path 'C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.ServiceBus\.\Microsoft.Azure.Commands.ServiceBus.format.ps1xml' because it does not exist.. Verify that a valid value
is specified for this field in the 'C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.ServiceBus\AzureRM.ServiceBus.psd1' file.
At line:1 char:1
+ Import-Module AzureRM.ServiceBus
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Program File...ServiceBus.psd1:String) [Import-Module], ArgumentException
    + FullyQualifiedErrorId : Modules_InvalidManifest,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by RDalziel** [comment]
Getting the same, Service Bus seems to be missing following an update from the web platform installer.

**Comment by RDalziel** [comment]
Fixed by getting the latest RM from the gallery

https://www.powershellgallery.com/packages/AzureRM/3.4.0

**Comment by cormacpayne** [comment]
@wangzq Hey Walter, are you still seeing this issue in the latest Azure PowerShell (3.6.0) release?

**Comment by wangzq** [comment]
Just tried it, after installing azure-powershell.3.6.0.msi Get-Module still shows Azure as 3.5.0, and Import-Module AzureRM.ServiceBus still has the error:
```
Import-Module : The member 'FormatsToProcess' in the module manifest is not valid: Cannot find path 'C:\Program Files (x86)\Microsoft
SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.ServiceBus\.\Microsoft.Azure.Commands.ServiceBus.format.ps1xml' because it does not exist.. Verify that a valid value is
specified for this field in the 'C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.ServiceBus\AzureRM.ServiceBus.psd1' file.
At line:1 char:1
+ Import-Module AzureRM.ServiceBus
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Program File...ServiceBus.psd1:String) [Import-Module], ArgumentException
    + FullyQualifiedErrorId : Modules_InvalidManifest,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by cormacpayne** [comment]
@wangzq the `Azure` module will be 3.5.0, but the `AzureRM` module is 3.6.0, correlating to the release version.

@v-Ajnava can you take a look?

**Comment by venky085** [comment]
I'm too facing same issue. If I install azure powershell using powershell, New-AzureRmServiceBusNamespace works but Login-AzureRmAccount doesn't. If I install azure powershell using web platform installer or MSI, Login-AzureRmAccount works but New-AzureRmServiceBusNamespace doesn't.

**Comment by v-Ajnava** [comment]
The issue is fixed in March Release - MSI:  https://github.com/Azure/azure-powershell/releases/tag/v3.7.0-March2017 . 

The Web platform installer is not updated after Feb. we will work on fixing it in web platform installer.
