### ISSUE TITLE
Set-AzureRmVMDiskEncryptionExtension fails on single VM with managed disks, works for others

### ISSUE THREAD

**Issue by cob999** [Azure/azure-powershell#3945]
### Cmdlet(s)
Set-AzureRmVMDiskEncryptionExtension

### PowerShell Version
5.1.15063.296

### Module Version
3.8.0      AzureRM
2.9.0      AzureRM.Compute
2.8.0      AzureRM.profile

### OS Version
10.0.15063.296

### Description
Following the steps in the following page https://docs.microsoft.com/en-us/azure/security-center/security-center-disk-encryption I create all the prerequisites for disk encryption and successfully run Set-AzureRmVMDiskEncryptionExtension for 3 VMs. When I try Set-AzureRmVMDiskEncryptionExtension for the final VM in the resource group it fails with the error `The underlying connection was closed: An unexpected error occurred on a send` full output below. It fails consistently every time I run the command.

There not a lot of differences between the VMs that succeeded and the one which failed. One possible root of the cause is that the VM that has failed uses managed disks, although another VM with managed disks has encrypted successfully with the same Set-AzureRmVMDiskEncryptionExtension command

### Debug Output
Lots of sensitive data in the debug output so just showing the normal output, I can supply any pieces needed...

```
Set-AzureRmVMDiskEncryptionExtension : Long running operation failed with status 'Failed'.
ErrorCode: VMExtensionProvisioningError
ErrorMessage: VM has reported a failure when processing extension 'AzureDiskEncryption'. Error message: "Failed to
configure bitlocker as expected. Exception: An error occurred while sending the request., InnerException:
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. --->
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed
by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote
host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar), stack trace:    at
Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.UploadBekToKeyVault(EncryptableVolume
vol, String protectorId, Boolean saveKeyToBekVolume)
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.GenerateAndUploadProtectorForVolume(
EncryptableVolume vol, Boolean saveKeyToBekVolume)
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.GenerateAndUploadOsVolumeProtector()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.EnableEncryption()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.HandleEncryptionOperations()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.OnEnable()".
StartTime: 11/05/2017 09:32:01
EndTime: 11/05/2017 09:32:54
OperationID: de0ccfe5-a008-4768-9600-f0deb9000cb0
Status: Failed
At line:1 char:1
+ Set-AzureRmVMDiskEncryptionExtension -ResourceGroupName $resourceGrou ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmVMDiskEncryptionExtension], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Extension.AzureDiskEncryption.SetAzureDiskEncryptionExt
   ensionCommand

```

### Script/Steps for Reproduction

```
Set-AzureRmVMDiskEncryptionExtension -ResourceGroupName $resourceGroupName -VMName $vmName -AadClientID $aadClientID -AadClientSecret $aadClientSecret -DiskEncryptionKeyVaultUrl $diskEncryptionKeyVaultUrl -DiskEncryptionKeyVaultId $keyVaultResourceId -VolumeType All
```

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue?

**Comment by cob999** [comment]
should I open a support query for this? it's something we do need to get resolved and just wondering the best way to progress this. there's a 2nd issue I've encountered when trying to encrypt VMs that have TLS 1.0 & 1.1 disabled, but I'll get this one resolved first before opening that

**Comment by singhkays** [comment]
@cob999 Sure, looks like something failed in the VM. This needs deeper investigation of the platform logs. Closing as it does not look like a PowerShell issue. Feel free to reopen if support determines something wrong with PS cmdlets.

**Comment by kaevans** [comment]
The Azure Disk Encryption extension is built using .NET 4.5. If you look at the logs in `C:\WindowsAzure\Logs\Plugins\Microsoft.Azure.Security.AzureDiskEncryption\1.1.0.4` on the VM, you should see an error indicating a fatal exception in BitlockerExtension::OnEnable. 

```
2018-08-12T12:02:16.5735559Z	[Fatal]:	BitlockerExtension::OnEnable hit exception An error occurred while sending the request., inner exception System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar), stack trace:    at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.UploadBekToKeyVault(EncryptableVolume vol, String protectorId, Boolean saveKeyToBekVolume)
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.GenerateAndUploadProtectorForVolume(EncryptableVolume vol, Boolean saveKeyToBekVolume)
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.GenerateAndUploadOsVolumeProtector()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.EnableEncryption()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.HandleEncryptionOperations()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.OnEnable()
```

If TLS 1.0 client was disabled on the VM, add the following registry entries to the virtual machine prior to enabling Azure Disk Encryption.

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001
```

For more information, see [Transport Layer Security (TLS) best practices with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls).

**Comment by Kundan9** [comment]
Above registry key are fixed the issue, but still my extension is showing failed on portal. But when i am checking internally it is showing the C drive encryption is in progress., Basically i am facing this issue on my all file server cluster VMs only. Is anybody has idea about this issue?

**Comment by kaevans** [comment]
The portal shows an error for the template deployment.  Fixing the registry entries in the VM does not fix the deployment failure. If you re-deploy in incremental mode it should succeed. To automate setting the registry entries during deployment, See the following example that uses PowerShell DSC to set the needed registry entries. Setting the registry entries needs to complete before your template applies disk encryption.

https://github.com/kaevans/tls-demo
