### ISSUE TITLE
Set-AzureRMStorageAccount Pipeline broken in 3.1.0

### ISSUE THREAD

**Issue by arcotek-ltd** [Azure/azure-powershell#4106]
### Cmdlet(s)
Set-AzureRMStorageAccount

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

PS C:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  117     

### Module Version
AzureRm.Storage 3.1.0 (and 3.0.0)
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
Windows 7 64-bit, Enterprise

### Description
Was working in AzureRm.Storage 2.1.0. Cannot pipe get-AzureRmStorageAccount into Set-AzureRmStorageAccount.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

Can't give you all the debug output as there is far to much information that I assume will be in the public domain, however the error is:
Set-AzureRmStorageAccount : ParameterBinderStrings
At line:23 char:8
+ $oSa | Set-AzureRmStorageAccount
+        ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (:PSObject) [Set-AzureRmStorageAccount], ParameterBindingParameterDefaultValueException
    + FullyQualifiedErrorId : GetDefaultValueFailed,Microsoft.Azure.Commands.Management.Storage.SetAzureStorageAccountComm

and debug:

DEBUG: 11:16:05 - GetAzureStorageAccountCommand begin processing with ParameterSet 'AccountNameParameterSet'.
DEBUG: 11:16:05 - using account id 'someaccountid'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'anaccount', environment: 'AzureCloud', tenant: 'atenant'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/09/2017 10:16:05: someguid - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/anotherguid/
	Resource: https://management.core.windows.net/
	ClientId: clientID
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (3 items)
	Authentication Target: Client
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/09/2017 10:16:05:  - TokenCache: Deserialized 3 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 06/09/2017 10:16:05: aGUID - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/09/2017 10:16:05: aGUID - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 06/09/2017 10:16:05: aGUID - TokenCache: 12.8026054966667 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/09/2017 10:16:05: aGUID - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/09/2017 10:16:05: aGUID - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: TOKENHASH=
	Refresh Token Hash: [No Refresh Token]
	Expiration Time: 06/09/2017 10:28:53 +00:00
	User Hash: null
	

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xyz/resourceGroups/Storage-Resources/providers/Microsoft.Storage/storageAccounts/somestorageaccount?api-version=2017-06-01

Headers:
x-ms-client-request-id        : 85265a86-0ec1-4074-b125-d423388b2e43
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : f416e06e-7c1f-40f7-a388-275c268b98b8
Cache-Control                 : no-cache
Server                        : Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 14996
x-ms-correlation-request-id   : f416e06e-7c1f-40f7-a388-275c268b98b8
x-ms-routing-request-id       : WESTEUROPE:20170609T101606Z:f416e06e-7c1f-40f7-a388-275c268b98b8
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Date                          : Fri, 09 Jun 2017 10:16:05 GMT

Body:
{
  "id": "/subscriptions/38c8bf69-6c5c-43f7-812b-3780c11bd6b3/resourceGroups/storage-resources/providers/Microsoft.Storage/storageAccounts/somestorageaccount",
  "kind": "Storage",
  "location": "westus",
  "name": "somestorageaccount",
  "properties": {
    "creationTime": "2016-06-08T13:02:03.1739134Z",
    "encryption": {
      "keySource": "Microsoft.Storage",
      "services": {
        "blob": {
          "enabled": true,
          "lastEnabledTime": "2017-05-22T17:54:07.6440985Z"
        }
      }
    },
    "primaryEndpoints": {
      "blob": "https://somestorageaccount.blob.core.windows.net/",
      "file": "https://somestorageaccount.file.core.windows.net/",
      "queue": "https://somestorageaccount.queue.core.windows.net/",
      "table": "https://somestorageaccount.table.core.windows.net/"
    },
    "primaryLocation": "westus",
    "provisioningState": "Succeeded",
    "statusOfPrimary": "available",
    "supportsHttpsTrafficOnly": false
  },
  "sku": {
    "name": "Standard_LRS",
    "tier": "Standard"
  },
  "tags": {},
  "type": "Microsoft.Storage/storageAccounts"
}

DEBUG: 11:16:06 - GetAzureStorageAccountCommand end processing.
DEBUG: 11:16:06 - GetAzureStorageAccountCommand end processing.
DEBUG: 11:16:06 - SetAzureStorageAccountCommand begin processing with ParameterSet 'StorageEncryption'.
DEBUG: 11:16:06 - using account id 'someaccountid'...

### Script/Steps for Reproduction
$StorageAccount = "somestorageaccount"
$SAResourceGroup = "Storage-Resources"

$oSa = Get-AzureRmStorageAccount -ResourceGroupName $SAResourceGroup -Name $StorageAccount

$oSa | Set-AzureRmStorageAccount

**Comment by arcotek-ltd** [comment]
I have now found that if I do:
```
$StorageAccount = "hexcelgeneralstdlrswus01"
$AAresourceGroupName = "RG-S01-UWC-S-DEV-002"

$oSa = Get-AzureRmStorageAccount -ResourceGroupName $SAResourceGroup -Name $StorageAccount

Set-AzureRmStorageAccount -ResourceGroupName $oSa.ResourceGroupName -Name $oSa.StorageAccountName
```

I get a further error that doesn't pertain to the available parameters or the documentation:

```
Set-AzureRmStorageAccount : Request must specify an account property to update.
At line:23 char:1
+ Set-AzureRmStorageAccount -ResourceGroupName $oSa.ResourceGroupName - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmStorageAccount], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.SetAzureStorageAccountCommand
```

**Comment by cormacpayne** [comment]
@blueww Hey Wei, would you mind taking a look at this issue?

**Comment by blueww** [comment]
@arcotek-ltd 
Set-AzureRmStorageAccount is to change the property of a Storage Account. 
But if your script, you don't set any property to change, so nothing to change with this cmdlet, then the cmdlet report error: "Request must specify an account property to update" You can specify any property to change (e.g. - SkuName) then you will not see this error.

If you just want to set the account as the default account of current PowerShell Console (then you can run storage data plane cmdlet like "Get-AzureStorageContainer" without context), you can use the following script:
`Get-AzureRMStorageAccount -ResourceGroupName $resourceGroupName -Name $accountName | Set-AzureRmCurrentStorageAccount`

**Comment by woter324** [comment]
@blueww 
I am following an [MS article](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-powershell-sas-token) for creating a SAS token on the fly, under the section "Provide SAS token during deployment".

It was working in a previous version of AzureRM.Storage (2.1.0), but it is not working in 3.1.0.
The script broke, trying to do exactly what you prescribe:


```
$oSa = Get-AzureRmStorageAccount -ResourceGroupName $SAResourceGroup -Name $StorageAccount
$SaBlobBaseUri = $oSa.PrimaryEndpoints.Blob.ToString()

# Gernerate SAS
$currentSA = $oSa | Set-AzureRmStorageAccount
$TemplateSas = New-AzureStorageAccountSASToken -Service Blob -ResourceType object -Permission r -ExpiryTime (Get-Date).AddHours(3.0)
$Sas = (ConvertTo-SecureString -string $TemplateSas -AsPlainText -Force)
```

No I'm not. Sorry. I'll change `Set-AzureRmStorageAccount` to `Set-AzureRmCURRENTStorageAccount`.

(Left in the above, so it may help others). Although, something has still changed in the different releases.

Thanks for your help.

**Comment by blueww** [comment]
@arcotek-ltd 
After review [MS article ](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-powershell-sas-token), I see you really want to use Set-AzureRmCurrentStorageAccount .
So the issue is resolved and I will close it.

Feel free to open it if you have any other comments.

**Comment by siebeh** [comment]
This issie isn't solved yet. 
When receiving the Microsoft.Azure.Commands.Management.Storage.Models.PSStorageAccount object through a pipeline the command cannot be processed.

```
PS C:\Users\x\OneDrive\Powershell\AzureTest> Get-AzureRmStorageAccount -ResourceGroupName:$RGName

StorageAccountName ResourceGroupName    Location   SkuName     Kind    AccessTier CreationTime       ProvisioningState EnableHttpsTrafficOnly
------------------ -----------------    --------   -------     ----    ---------- ------------       ----------------- ----------------------
xxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxx westeurope StandardLRS Storage            9-12-2018 16:19:27 Succeeded         False


PS C:\Users\x\OneDrive\Powershell\AzureTest> Get-AzureRmStorageAccount -ResourceGroupName:$RGName | Set-AzureRmStorageAccount -UpgradeToStorageV2
Set-AzureRmStorageAccount : ParameterBinderStrings
At line:1 char:56
+ ... urceGroupName:$RGName | Set-AzureRmStorageAccount -UpgradeToStorageV2
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (:PSObject) [Set-AzureRmStorageAccount], ParameterBindingParameterDefaultValueException
    + FullyQualifiedErrorId : GetDefaultValueFailed,Microsoft.Azure.Commands.Management.Storage.SetAzureStorageAccountCommand

PS C:\Users\x\OneDrive\Powershell\AzureTest> Set-AzureRmStorageAccount -ResourceGroupName:$RGName -AccountName:$storageAccountName -UpgradeToStorageV2

StorageAccountName ResourceGroupName    Location   SkuName     Kind      AccessTier CreationTime       ProvisioningState EnableHttpsTrafficOnly
------------------ -----------------    --------   -------     ----      ---------- ------------       ----------------- ----------------------
xxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxx westeurope StandardLRS StorageV2 Hot        9-12-2018 16:19:27 Succeeded         False


```

**Comment by blueww** [comment]
@siebeh 
Your error is different with the before issue. The cause and the error message are different.

If you just get 1 account, the issue won't happen. 
To get mutiple accounts, you can add parenthesis  to overcome this issue as below. 
Following command works on my side with AzureRm.Storage 5.2.0.

`(Get-AzureRmStorageAccount -ResourceGroupName $RGName) | Set-AzureRmStorageAccount -UpgradeToStorageV2`

**Comment by blueww** [comment]
@siebeh 
I have raised a PR to fix this issue. But before this is fixed, add `-EnableHttpsTrafficOnly` parameter can workaround the issue.

**Comment by blueww** [comment]
A new issue is opened https://github.com/Azure/azure-powershell/issues/8060, will continue follow it in https://github.com/Azure/azure-powershell/issues/8060
