### ISSUE TITLE
Remove-AzureRmRoleAssignment results in Invalid API error in Azure Automation

### ISSUE THREAD

**Issue by nahalf** [Azure/azure-powershell#4420]
### Cmdlet(s)
Remove-AzureRmRoleAssignment

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### Module Version
4.2.1

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.15063.502 

### Description
I am able to successfully use Remove-AzureRmRoleAssignment in Powershell ISE, but when used in a runbook in Azure Automation, I receive an error that the API version is incorrect.

All the modules in the Automation Account have been updated, the versions of AzureRM on my machine and in the Automation Account are the same, and the job was executed on Azure, not a hybrid runbook worker group.
Any ideas what could be causing this?

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

![image](https://user-images.githubusercontent.com/18647532/29040919-b39c7bec-7b65-11e7-813c-f8fb8cb05350.png)

### Script/Steps for Reproduction

Remove-AzureRmRoleAssignment -ObjectID <$objectID> -RoleDefinitionName <$roleDefinitionName> -Scope <$scope>

**Comment by darshanhs90** [comment]
@nahalf could you run the command with $DebugPreference="Continue" and provide the debug output.
It helps in figuring out the issue causing this error .

**Comment by nahalf** [comment]
$DebugPreference was already set to Continue when I provided the previous output.

**Comment by darshanhs90** [comment]
@nahalf $DebugPreference="Continue"
the quotes matter  in the above statement.
After setting it,you should get something like[for example] 
> $DebugPreference="Continue"
>Get-AzureRmRoleDefinition -Name "Reader"
DEBUG: 11:36:23 AM - GetAzureRoleDefinitionCommand begin processing with ParameterSet 'RoleDefinitionNameParameterSet'.

**Comment by darshanhs90** [comment]
@nahalf I heard from Ming that the issue got resolved with the new version i.e. 4.3.0
Let us know if it happened in the new version also.

**Comment by nahalf** [comment]
Yes but 4.3.0 was pulled back so not sure when it's going to be released again. So for all intents and purposes, the issue is not resolved while 4.2.1 is currently the latest version.

**Comment by darshanhs90** [comment]
Closing this since the new version has been released
