### ISSUE TITLE
Fix re-authentication issue with Token parameter set in Add-AzureRmAccount

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#4656]
### Description

Primary authentication usign the token parameter set is working, but reauthentication with renewed tokens semes to fail

- [ ] Determine if this scenario can be covered by a mock test
- [ ] Enable token renewal in add-azurermaccount
- [ ] Validate using live tokens for RM, Graph, KeyVault, and verify renewal tokens are used

**Comment by markcowl** [comment]
- Note: the root cause here is that we are likely not updating the context details if we find that a context already exists - the credentials are stored as a proeprty of the 'Account'.  In general, we shoudl fix this so the interface method TrySetContext will coalesce the proeprties of the input context witht he existing context (after finding it).

**Comment by markcowl** [comment]
Fixed.

**Comment by 47th** [comment]
The issue doesn't appear to be fixed at the moment. Azure RM commandlets constantly stop working after some time and I have to restart the Azure console.

**Comment by prafulbusa** [comment]
Still getting error for VIrtual Network, NIC, PublicIP etc...The issue is still not resolved yet.
