### ISSUE TITLE
Get-AzureRmRoleAssignment : Sequence contains more than one matching element

### ISSUE THREAD

**Issue by MilanNXT** [Azure/azure-powershell#5295]
### Cmdlet(s)
Get-AzureRMRoleAssignment

### PowerShell Version
PSVersion                      5.1.15063.786                                                                                                                                                       
PSEdition                      Desktop                                                                                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                             
BuildVersion                   10.0.15063.786                                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                                     
WSManStackVersion              3.0                                                                                                                                                                 
PSRemotingProtocolVersion      2.3                                                                                                                                                                 
SerializationVersion           1.1.0.1                                                                                                                                                             

### Module Version
 4.0.2      Azure.Storage
5.1.1      AzureRm                                                                                                                                                                      
4.1.1      AzureRM.Profile             

### OS Version
BuildVersion                   10.0.15063.786

### Description
While trying to get list of assigned users from **Custom** build Role.  Cmdlet drop the following error.

```
Get-AzureRmRoleAssignment : Sequence contains more than one matching element
At line:22 char:22
+ ... ecs_users = Get-AzureRmRoleAssignment -Scope "/subscriptions/$sid" -R ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmRoleAssignment], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand

```
I have multiple subscriptions where the command work but one particular subscription it always drop Error. Interestingly Azure CLI works without issue (az role assignment list --role 52673e47-41de-4f17-b5ab-9e14f4c30c72 --query [*].[properties.principalId] --out table).

### Debug Output
attached is debug output. Just removed values and data.

[output.txt](https://github.com/Azure/azure-powershell/files/1642690/output.txt)

### Script/Steps for Reproduction
Get-AzureRmRoleAssignment -Scope "/subscriptions/7310ab5b-d0c3-41a7-8e91-220ed8d784ab" -RoleDefinitionName 'ECS Contact Microsoft Support'

**Comment by cormacpayne** [comment]
@darshanhs90 Hey Haridarshan, would you mind taking a look at this issue?

**Comment by darshanhs90** [comment]
Looking into this

**Comment by darshanhs90** [comment]
@MilanNXT could you share if there i anything special that is as part of this subscription?
Since I am unable to repro the error

**Comment by MilanNXT** [comment]
Haridarshan,

apologize for delay. I was able to achieve results by using Azure CLI. I am closing this issue.

**Comment by maddieclayton** [comment]
Fixed in powershell

**Comment by MilanNXT** [comment]
Thank you

**Comment by csanchez09** [comment]
Hello Everyone

I am facing the same exact issue, I have tried to follow the link to the solution https://github.com/Azure/azure-powershell/pull/5595, however I am unable to understand the solution, it is possible someone can provide me some assistance to understand what is the solution to the issue

Thank you in advance

**Comment by maddieclayton** [comment]
@csanchez09 The fix for the issue above is not in the current release, but will be in the release this coming Tuesday - please update to the newest version on Tuesday at 10am to get this fix.

**Comment by csanchez09** [comment]
Thank you for your reply @maddieclayton, I much appreciate it, what should I upgrade, the version of the module AzureRM or the version of PowerShell ?

**Comment by maddieclayton** [comment]
@csanchez09 Just updating the AzureRM module will be enough to pick up the change.

**Comment by csanchez09** [comment]
@maddieclayton Thank you for help, I really appreciate it, I will give an update next week to confirm that the issue have been addressed

**Comment by VahidJ66** [comment]
Hello i have the exact same issue. There are several subscriptions that the command works with but 2 that return this error. I have updated Azure and AzureRM modules which didn't fix the issue.
PSVersion                           5.1.16299.431 
Azure module version        5.2.0 
AzureRM module version   6.1.0

I believe this is the latest AzureRM version. Do you have any idea how to fix this?

**Comment by maddieclayton** [comment]
@VahidJ66 Can you open a new issue with all of the information asked for in the issue template? I will redirect it to the correct team.
