### ISSUE TITLE
Get-AzureRmSubscription repeats subscription per tenantid when using AccessToken connection

### ISSUE THREAD

**Issue by tylerd** [Azure/azure-powershell#6521]
### Description 

Executing `Get-AzureRmSubscription` results in repeat subscriptions per Tenant.

Interestingly, the Subscriptions listed are only under the Microsoft Tenant. There are other subscriptions under the other Tenants that are not listed (even though the TenantIds are listed)

### Script/Steps for Reproduction 

Generate Access Token to access Azure Management API.
Get all Subscriptions

```powershell
Import-Module AzureRM -Global
Import-Module Microsoft.ADAL.PowerShell -Global

$azEnv = Get-AzureRmEnvironment -Name "AzureCloud"
$clientId = [Microsoft.Azure.Commands.Common.Authentication.AdalConfiguration]::PowerShellClientId
$redirectUri = [Microsoft.Azure.Commands.Common.Authentication.AdalConfiguration]::PowerShellRedirectUri

$token = Get-ADALAccessToken -AuthorityName $MSFT -ClientId $clientId -ResourceId $azEnv.ActiveDirectoryServiceEndpointResourceId -RedirectUri $redirectUri

Connect-AzureRmAccount -AccessToken $token -AccountId $AccountId -TenantId $MSFT

# Done Login

Get-AzureRmSubscription | select Name,TenantId

```

### Module Version

```powershell
C:\Users\tylerd\DesktopGet-Module -Name AzureRM -ListAvailable


    Directory: C:\Users\tylerd\Documents\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.3.0      AzureRM
Script     6.2.0      AzureRM


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.7.0      AzureRM
```

### Environment Data

```powershell
C:\Users\tylerd\Desktop$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.112
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.112
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

Full Debug Output Attached:
[debugoutput.txt](https://github.com/Azure/azure-powershell/files/2128968/debugoutput.txt)

```
Name                          TenantId
----                          --------
IAAS                          b747b1a6-9639-44ab-82bf-db0805e29468
PCL                           b747b1a6-9639-44ab-82bf-db0805e29468
W                             b747b1a6-9639-44ab-82bf-db0805e29468
MSFT                          b747b1a6-9639-44ab-82bf-db0805e29468
BC                            b747b1a6-9639-44ab-82bf-db0805e29468
ML                            b747b1a6-9639-44ab-82bf-db0805e29468
IQ                            b747b1a6-9639-44ab-82bf-db0805e29468
MS1                           b747b1a6-9639-44ab-82bf-db0805e29468
MSDN                          b747b1a6-9639-44ab-82bf-db0805e29468
MO                            b747b1a6-9639-44ab-82bf-db0805e29468
Agile-BI-Azure-Subscription-2 b747b1a6-9639-44ab-82bf-db0805e29468
Visual Studio Enterprise      b747b1a6-9639-44ab-82bf-db0805e29468
ASC DEMO                      b747b1a6-9639-44ab-82bf-db0805e29468
Contoso IT - demo             b747b1a6-9639-44ab-82bf-db0805e29468
TORMTC                        b747b1a6-9639-44ab-82bf-db0805e29468
IAAS                          72f988bf-86f1-41af-91ab-2d7cd011db47
PCL                           72f988bf-86f1-41af-91ab-2d7cd011db47
W                             72f988bf-86f1-41af-91ab-2d7cd011db47
MSFT                          72f988bf-86f1-41af-91ab-2d7cd011db47
BC                            72f988bf-86f1-41af-91ab-2d7cd011db47
ML                            72f988bf-86f1-41af-91ab-2d7cd011db47
IQ                            72f988bf-86f1-41af-91ab-2d7cd011db47
MS1                           72f988bf-86f1-41af-91ab-2d7cd011db47
MSDN                          72f988bf-86f1-41af-91ab-2d7cd011db47
MO                            72f988bf-86f1-41af-91ab-2d7cd011db47
Agile-BI-Azure-Subscription-2 72f988bf-86f1-41af-91ab-2d7cd011db47
Visual Studio Enterprise      72f988bf-86f1-41af-91ab-2d7cd011db47
ASC DEMO                      72f988bf-86f1-41af-91ab-2d7cd011db47
Contoso IT - demo             72f988bf-86f1-41af-91ab-2d7cd011db47
TORMTC                        72f988bf-86f1-41af-91ab-2d7cd011db47
IAAS                          1604a336-abfc-4ffe-a7e7-bf277ec36f51
PCL                           1604a336-abfc-4ffe-a7e7-bf277ec36f51
W                             1604a336-abfc-4ffe-a7e7-bf277ec36f51
MSFT                          1604a336-abfc-4ffe-a7e7-bf277ec36f51
BC                            1604a336-abfc-4ffe-a7e7-bf277ec36f51
ML                            1604a336-abfc-4ffe-a7e7-bf277ec36f51
IQ                            1604a336-abfc-4ffe-a7e7-bf277ec36f51
MS1                           1604a336-abfc-4ffe-a7e7-bf277ec36f51
MSDN                          1604a336-abfc-4ffe-a7e7-bf277ec36f51
MO                            1604a336-abfc-4ffe-a7e7-bf277ec36f51
Agile-BI-Azure-Subscription-2 1604a336-abfc-4ffe-a7e7-bf277ec36f51
Visual Studio Enterprise      1604a336-abfc-4ffe-a7e7-bf277ec36f51
ASC DEMO                      1604a336-abfc-4ffe-a7e7-bf277ec36f51
Contoso IT - demo             1604a336-abfc-4ffe-a7e7-bf277ec36f51
TORMTC                        1604a336-abfc-4ffe-a7e7-bf277ec36f51
IAAS                          31f660a5-192a-4db3-92ba-ca424f1b259e
PCL                           31f660a5-192a-4db3-92ba-ca424f1b259e
W                             31f660a5-192a-4db3-92ba-ca424f1b259e
MSFT                          31f660a5-192a-4db3-92ba-ca424f1b259e
BC                            31f660a5-192a-4db3-92ba-ca424f1b259e
ML                            31f660a5-192a-4db3-92ba-ca424f1b259e
IQ                            31f660a5-192a-4db3-92ba-ca424f1b259e
MS1                           31f660a5-192a-4db3-92ba-ca424f1b259e
MSDN                          31f660a5-192a-4db3-92ba-ca424f1b259e
MO                            31f660a5-192a-4db3-92ba-ca424f1b259e
Agile-BI-Azure-Subscription-2 31f660a5-192a-4db3-92ba-ca424f1b259e
Visual Studio Enterprise      31f660a5-192a-4db3-92ba-ca424f1b259e
ASC DEMO                      31f660a5-192a-4db3-92ba-ca424f1b259e
Contoso IT - demo             31f660a5-192a-4db3-92ba-ca424f1b259e
TORMTC                        31f660a5-192a-4db3-92ba-ca424f1b259e
IAAS                          434e9d2b-d8d3-4bd9-bd27-03b20a16d863
PCL                           434e9d2b-d8d3-4bd9-bd27-03b20a16d863
W                             434e9d2b-d8d3-4bd9-bd27-03b20a16d863
MSFT                          434e9d2b-d8d3-4bd9-bd27-03b20a16d863
BC                            434e9d2b-d8d3-4bd9-bd27-03b20a16d863
ML                            434e9d2b-d8d3-4bd9-bd27-03b20a16d863
IQ                            434e9d2b-d8d3-4bd9-bd27-03b20a16d863
MS1                           434e9d2b-d8d3-4bd9-bd27-03b20a16d863
MSDN                          434e9d2b-d8d3-4bd9-bd27-03b20a16d863
MO                            434e9d2b-d8d3-4bd9-bd27-03b20a16d863
Agile-BI-Azure-Subscription-2 434e9d2b-d8d3-4bd9-bd27-03b20a16d863
Visual Studio Enterprise      434e9d2b-d8d3-4bd9-bd27-03b20a16d863
ASC DEMO                      434e9d2b-d8d3-4bd9-bd27-03b20a16d863
Contoso IT - demo             434e9d2b-d8d3-4bd9-bd27-03b20a16d863
TORMTC                        434e9d2b-d8d3-4bd9-bd27-03b20a16d863
IAAS                          4b30439b-26ef-4016-aa9b-a1dc19acbb8f
PCL                           4b30439b-26ef-4016-aa9b-a1dc19acbb8f
W                             4b30439b-26ef-4016-aa9b-a1dc19acbb8f
MSFT                          4b30439b-26ef-4016-aa9b-a1dc19acbb8f
BC                            4b30439b-26ef-4016-aa9b-a1dc19acbb8f
ML                            4b30439b-26ef-4016-aa9b-a1dc19acbb8f
IQ                            4b30439b-26ef-4016-aa9b-a1dc19acbb8f
MS1                           4b30439b-26ef-4016-aa9b-a1dc19acbb8f
MSDN                          4b30439b-26ef-4016-aa9b-a1dc19acbb8f
MO                            4b30439b-26ef-4016-aa9b-a1dc19acbb8f
Agile-BI-Azure-Subscription-2 4b30439b-26ef-4016-aa9b-a1dc19acbb8f
Visual Studio Enterprise      4b30439b-26ef-4016-aa9b-a1dc19acbb8f
ASC DEMO                      4b30439b-26ef-4016-aa9b-a1dc19acbb8f
Contoso IT - demo             4b30439b-26ef-4016-aa9b-a1dc19acbb8f
TORMTC                        4b30439b-26ef-4016-aa9b-a1dc19acbb8f
IAAS                          633f3069-d670-4419-9fee-2ab4251c88ee
PCL                           633f3069-d670-4419-9fee-2ab4251c88ee
W                             633f3069-d670-4419-9fee-2ab4251c88ee
MSFT                          633f3069-d670-4419-9fee-2ab4251c88ee
BC                            633f3069-d670-4419-9fee-2ab4251c88ee
ML                            633f3069-d670-4419-9fee-2ab4251c88ee
IQ                            633f3069-d670-4419-9fee-2ab4251c88ee
MS1                           633f3069-d670-4419-9fee-2ab4251c88ee
MSDN                          633f3069-d670-4419-9fee-2ab4251c88ee
MO                            633f3069-d670-4419-9fee-2ab4251c88ee
Agile-BI-Azure-Subscription-2 633f3069-d670-4419-9fee-2ab4251c88ee
Visual Studio Enterprise      633f3069-d670-4419-9fee-2ab4251c88ee
ASC DEMO                      633f3069-d670-4419-9fee-2ab4251c88ee
Contoso IT - demo             633f3069-d670-4419-9fee-2ab4251c88ee
TORMTC                        633f3069-d670-4419-9fee-2ab4251c88ee
IAAS                          94c40a73-c82f-47f0-8244-aed167ae33a0
PCL                           94c40a73-c82f-47f0-8244-aed167ae33a0
W                             94c40a73-c82f-47f0-8244-aed167ae33a0
MSFT                          94c40a73-c82f-47f0-8244-aed167ae33a0
BC                            94c40a73-c82f-47f0-8244-aed167ae33a0
ML                            94c40a73-c82f-47f0-8244-aed167ae33a0
IQ                            94c40a73-c82f-47f0-8244-aed167ae33a0
MS1                           94c40a73-c82f-47f0-8244-aed167ae33a0
MSDN                          94c40a73-c82f-47f0-8244-aed167ae33a0
MO                            94c40a73-c82f-47f0-8244-aed167ae33a0
Agile-BI-Azure-Subscription-2 94c40a73-c82f-47f0-8244-aed167ae33a0
Visual Studio Enterprise      94c40a73-c82f-47f0-8244-aed167ae33a0
ASC DEMO                      94c40a73-c82f-47f0-8244-aed167ae33a0
Contoso IT - demo             94c40a73-c82f-47f0-8244-aed167ae33a0
TORMTC                        94c40a73-c82f-47f0-8244-aed167ae33a0
IAAS                          a8d84f34-161b-4927-998e-1a9cafc0444f
PCL                           a8d84f34-161b-4927-998e-1a9cafc0444f
W                             a8d84f34-161b-4927-998e-1a9cafc0444f
MSFT                          a8d84f34-161b-4927-998e-1a9cafc0444f
BC                            a8d84f34-161b-4927-998e-1a9cafc0444f
ML                            a8d84f34-161b-4927-998e-1a9cafc0444f
IQ                            a8d84f34-161b-4927-998e-1a9cafc0444f
MS1                           a8d84f34-161b-4927-998e-1a9cafc0444f
MSDN                          a8d84f34-161b-4927-998e-1a9cafc0444f
MO                            a8d84f34-161b-4927-998e-1a9cafc0444f
Agile-BI-Azure-Subscription-2 a8d84f34-161b-4927-998e-1a9cafc0444f
Visual Studio Enterprise      a8d84f34-161b-4927-998e-1a9cafc0444f
ASC DEMO                      a8d84f34-161b-4927-998e-1a9cafc0444f
Contoso IT - demo             a8d84f34-161b-4927-998e-1a9cafc0444f
TORMTC                        a8d84f34-161b-4927-998e-1a9cafc0444f
IAAS                          b4e19cf5-ed91-44d3-81ce-70c848fa6841
PCL                           b4e19cf5-ed91-44d3-81ce-70c848fa6841
W                             b4e19cf5-ed91-44d3-81ce-70c848fa6841
MSFT                          b4e19cf5-ed91-44d3-81ce-70c848fa6841
BC                            b4e19cf5-ed91-44d3-81ce-70c848fa6841
ML                            b4e19cf5-ed91-44d3-81ce-70c848fa6841
IQ                            b4e19cf5-ed91-44d3-81ce-70c848fa6841
MS1                           b4e19cf5-ed91-44d3-81ce-70c848fa6841
MSDN                          b4e19cf5-ed91-44d3-81ce-70c848fa6841
MO                            b4e19cf5-ed91-44d3-81ce-70c848fa6841
Agile-BI-Azure-Subscription-2 b4e19cf5-ed91-44d3-81ce-70c848fa6841
Visual Studio Enterprise      b4e19cf5-ed91-44d3-81ce-70c848fa6841
ASC DEMO                      b4e19cf5-ed91-44d3-81ce-70c848fa6841
Contoso IT - demo             b4e19cf5-ed91-44d3-81ce-70c848fa6841
TORMTC                        b4e19cf5-ed91-44d3-81ce-70c848fa6841
IAAS                          bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
PCL                           bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
W                             bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
MSFT                          bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
BC                            bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
ML                            bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
IQ                            bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
MS1                           bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
MSDN                          bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
MO                            bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
Agile-BI-Azure-Subscription-2 bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
Visual Studio Enterprise      bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
ASC DEMO                      bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
Contoso IT - demo             bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
TORMTC                        bb99324c-2b39-4c9f-8cc4-e4d7c9f1877d
```

**Comment by tylerd** [comment]
FYI for anyone that can't wait for the resolution to this, the workaround is:

`Get-AzureRmSubscription -TenantId $yourTenantGuid`

Also this issue somehow breaks `Select-AzureRmSubscription` where it does not actually change subscriptions for some reason. Also the workaround here is `Select-AzureRmSubscription "name" -TenantId $yourTenantGuid`

**Comment by tylerd** [comment]
After debugging the code, the key issue here is that there are multiple places that the code iterates the list of Tenants that the user has access to and re-uses a single Access Token to call the management API for each of the tenants. Which results in repeated values for each tenant.

Access Tokens are inherently Tenant Specific -- If you login using an Access Token, the code should only use the TenantId associated with that Access Token (either through a required parameter, or embedded in the Access Token JWT tid claim)

**Comment by vladimir-shcherbakov** [comment]
@tylerd 
What did you put into the ```$MSFT``` variable?

**Comment by tylerd** [comment]
The TenantId GUID for "microsoft.onmicrosoft.com"

**Comment by vladimir-shcherbakov** [comment]
I got the [error](https://github.com/Azure/azure-powershell/issues/6410) when I run the command:
```Powershell
Connect-AzureRmAccount -AccessToken $token -AccountId $AccountId -TenantId <GUID>
```

**Comment by tylerd** [comment]
`$MSFT = "72f988bf-86f1-41af-91ab-2d7cd011db47"`

**Comment by vladimir-shcherbakov** [comment]
@tylerd 
On my side the cmdlet
```Powershell
Connect-AzureRmAccount -AccessToken $token -AccountId $AccountId -TenantId $tenantId
```
works if
 ```Powershell
$authorityName =microsoft.onmicrosoft.com 
$tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47
``` 
and  [errors](https://github.com/Azure/azure-powershell/issues/6410) if 
```Powershell
$authorityName =<tenantName>.onmicrosoft.com 
$tenantId=<tenantGUID>
```

**Comment by tylerd** [comment]
Where are you using `$authorityName`? I don't see the reference to that veriable anywhere.

Also, it looks like you were able to run `Connect-AzureRmAccount` but the bug was with `Get-AzureRmSubscription`

**Comment by vladimir-shcherbakov** [comment]
```Powershell
$token = Get-ADALAccessToken -AuthorityName$authorityName -ClientId $clientId -ResourceId $azEnv.ActiveDirectoryServiceEndpointResourceId -RedirectUri $redirectUri
```

**Comment by tylerd** [comment]
Ok … that does not really address the issue of the Access Token being re-used for Tenants other than the one generating the token.

**Comment by vladimir-shcherbakov** [comment]
Sorry, clicked the wrong button and closes.

**Comment by vladimir-shcherbakov** [comment]
Did you try Clear-AzureRmContext -Scope CurrentUser?

**Comment by tylerd** [comment]
Yes

**Comment by vladimir-shcherbakov** [comment]
@tylerd 
I got the repro. Possibly, after I used ```Clear-AzureRmContext -Scope CurrentUser```
Thanks.

**Comment by tylerd** [comment]
Just realized. This causes an issue in the Cloud Shell also.
```
PS Azure:\> Get-Command Get-AzureRmSubscription

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-AzureRmSubscription                            0.12.0     AzureRM.Profile.Netcore
```

**Comment by tylerd** [comment]
@vladimir-shcherbakov do you want me to just send a pull request for this? I have some cycles this afternoon

**Comment by vladimir-shcherbakov** [comment]
A PR has been opened #6621

**Comment by markcowl** [comment]
So, I think the root cause here was a clash in keys in the context, which was fixed in the last release.  That is, if you log in with one set of credentials that have access to a particular subscription, then log in with a different user (or a different mechanism), the default context is unchanged.

For example, if you log out before logging in with access token credentials, you would not see this, I don't think.  Remember that CloudShell automatically logs you in with MSI credentials.

To be sure can you: (1) try this with the latest version (0.13.1 was just released to CloudSHell); (2) if you do see recurrence, please execute with ```$DebugPreference="Continue"```.  This will allow us to see the client and server responses and additional logging info.

**Comment by tylerd** [comment]
I will send a full debug output tomorrow but I did verify this bug still exists on cloud shell. I could verify it on my Android phone ??

Simply by opening Cloud PowerShell Shell and executing Get-AzureRMSubscription

Keep in mind this is an issue when the AAD user exists in multiple AAD Directories (using AAD B2B)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tylerd** [comment]
Debug Output using AzureRM 6.5.0
[psoutput1.txt](https://github.com/Azure/azure-powershell/files/2236175/psoutput1.txt)

**Comment by maddieclayton** [comment]
Linking the relevant PR here: https://github.com/Azure/azure-powershell/pull/6621.  Once we are finished with the NetStandard conversion we will revisit this issue and assign it to a milestone.

**Comment by tylerd** [comment]
Tested release 6.8.1 -- no longer an issue
