### ISSUE TITLE
Get-help does not work well on release 6.1.1

### ISSUE THREAD

**Issue by bingbing8** [Azure/azure-powershell#7968]
### Script/Steps for Reproduction

```powershell
get-help New-AzureRmAutomationSourceControl -Online
get-help : The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help
topic is not specified in the command code or in the help file for the command.
At line:1 char:1
+ get-help New-AzureRmAutomationSourceControl -Online
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-Help], PSInvalidOperationException
+ FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.GetHelpCommand


get-help Get-AzureRmAutomationSourceControl -example
 
NAME
    Get-AzureRmAutomationSourceControl
 
ALIASES
    None

```

### Module Version

```powershell
PS C:\git\azure-powershell\src> get-module AzureRm.Automation
 
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.1.1      AzureRM.Automation                  {Export-AzureRmAutomationDscConfiguration, Export-AzureRmA...

```

### Environment Data

```powershell
PS C:\Users\yawang> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```

```

**Comment by cormacpayne** [comment]
@bingbing8 Hey Yanbing, it looks like this issue is resolved in our new `Az.Automation` module (as a part of the `Az` roll-up module). I'm not sure why, but the name of the `dll-Help.xml` file that contains the missing information is different than what PowerShell was expecting for `AzureRM.Automation`, but this has been resolved for `Az.Automation`.

**Comment by bingbing8** [comment]
@cormacpayne, how do i get the fix? I still see the same issue on my machine.

```powershell
PS C:\SC cmdlets> get-help New-AzureRmAutomationSourceControl

NAME
    New-AzureRmAutomationSourceControl

SYNTAX
    New-AzureRmAutomationSourceControl [-ResourceGroupName] <string> [-AutomationAccountName] <string> -Name <string>
    -RepoUrl <uri> -SourceType {GitHub | VsoGit | VsoTfvc} -AccessToken <securestring> -FolderPath <string> [-Branch
    <string>] [-Description <string>] [-EnableAutoSync] [-DoNotPublishRunbook] [-DefaultProfile
    <IAzureContextContainer>] [-WhatIf] [-Confirm]  [<CommonParameters>]


ALIASES
    None


REMARKS
    None



PS C:\SC cmdlets> get-help New-AzureRmAutomationSourceControl -Online
get-help : The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help
topic is not specified in the command code or in the help file for the command.
At line:1 char:1
+ get-help New-AzureRmAutomationSourceControl -Online
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-Help], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.GetHelpCommand

PS C:\SC cmdlets> get-help New-AzureRmAutomationSourceControl -Examples

NAME
    New-AzureRmAutomationSourceControl

ALIASES
    None


REMARKS
    None
```
