### ISSUE TITLE
Get-AzWebApp and Set-AzWebApp not returning/saving some properties

### ISSUE THREAD

**Issue by vinhent** [Azure/azure-powershell#9168]
## Description

When using Get-AzWebApp, properties FtpsState and Http20Enabled are not returned.
When using Set-AzWebApp, properties FtpsState, Http20Enabled, and ClientAffinityEnabled are not saved.

I didn't try with Get-AzWebAppSlot and Set-AzWebAppSlot, but I expect it could have the same issue.

## Steps to reproduce

```powershell
$resourceGroupName = "myresourcegroup"
$appName = "mywebapp"

$webApp = Get-AzWebApp -ResourceGroupName $resourceGroupName -Name $appName -ErrorAction Stop

# ClientAffinityEnabled was $true, setting it to $false
$webApp.ClientAffinityEnabled = $false 
# FtpsState was $null, setting it to "Disabled"
$webApp.SiteConfig.FtpsState = "Disabled"
# Http20Enabled was $null, setting it to $true
$webApp.SiteConfig.Http20Enabled = $true 

# Saving my new configuration
$webApp = Set-AzWebApp -WebApp $webApp -ErrorAction Stop

# Changes are not applied to my web app and also
$webApp.ClientAffinityEnabled # Returned $true
$webApp.SiteConfig.FtpsState # Returned $null
$webApp.SiteConfig.Http20Enabled # Returned $null
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.5.2      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     1.2.1      Az.Websites                         {Edit-AzWebAppBackupConfiguration, Enter-AzWebAppContainerPSSession, Get-AzAppServicePlan, Get-AzAppServicePlanMetric...}
```

## Debug output

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest?api-version=2018-02-01

Headers:
x-ms-client-request-id        : 26013467-3873-4e87-9783-7933c2f1907b
accept-language               : en-US

Body:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 92641049-0098-421f-9a17-c6574ca67e3f
x-ms-ratelimit-remaining-subscription-reads: 11989
x-ms-correlation-request-id   : 23767f43-bb9c-454e-b97f-375b4841c4bb
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T210708Z:23767f43-bb9c-454e-b97f-375b4841c4bb
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:07:08 GMT
ETag                          : "1D50A98646246CB"
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest",
  "name": "mywebapptest",
  "type": "Microsoft.Web/sites",
  "kind": "app",
  "location": "Central US",
  "tags": {},
  "properties": {
    "name": "mywebapptest",
    "state": "Running",
    "hostNames": [
      "mywebapptest.azurewebsites.net"
    ],
    "webSpace": "xxxx-xxxx-xx-CentralUSwebspace",
    "selfLink": "https://waws-prod-dm1-103.api.azurewebsites.windows.net:454/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/webspaces/xxxx-xxxx-xx-CentralUSwebspace/sites/mywebapptest",
    "repositorySiteName": "mywebapptest",
    "owner": null,
    "usageState": "Normal",
    "enabled": true,
    "adminEnabled": true,
    "enabledHostNames": [
      "mywebapptest.azurewebsites.net",
      "mywebapptest.scm.azurewebsites.net"
    ],
    "siteProperties": {
      "metadata": null,
      "properties": [
        {
          "name": "LinuxFxVersion",
          "value": ""
        },
        {
          "name": "WindowsFxVersion",
          "value": null
        }
      ],
      "appSettings": null
    },
    "availabilityState": "Normal",
    "sslCertificates": null,
    "csrs": [],
    "cers": null,
    "siteMode": null,
    "hostNameSslStates": [
      {
        "name": "mywebapptest.azurewebsites.net",
        "sslState": "Disabled",
        "ipBasedSslResult": null,
        "virtualIP": null,
        "thumbprint": null,
        "toUpdate": null,
        "toUpdateIpBasedSsl": null,
        "ipBasedSslState": "NotConfigured",
        "hostType": "Standard"
      },
      {
        "name": "mywebapptest.scm.azurewebsites.net",
        "sslState": "Disabled",
        "ipBasedSslResult": null,
        "virtualIP": null,
        "thumbprint": null,
        "toUpdate": null,
        "toUpdateIpBasedSsl": null,
        "ipBasedSslState": "NotConfigured",
        "hostType": "Repository"
      }
    ],
    "computeMode": null,
    "serverFarm": null,
    "serverFarmId": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/serverfarms/myplantest",
    "reserved": false,
    "isXenon": false,
    "hyperV": false,
    "lastModifiedTimeUtc": "2019-05-14T21:02:51.2766667",
    "storageRecoveryDefaultState": "Running",
    "contentAvailabilityState": "Normal",
    "runtimeAvailabilityState": "Normal",
    "siteConfig": null,
    "deploymentId": "mywebapptest",
    "trafficManagerHostNames": null,
    "sku": "PremiumV2",
    "scmSiteAlsoStopped": false,
    "targetSwapSlot": null,
    "hostingEnvironment": null,
    "hostingEnvironmentProfile": null,
    "clientAffinityEnabled": true,
    "clientCertEnabled": false,
    "clientCertExclusionPaths": null,
    "hostNamesDisabled": false,
    "domainVerificationIdentifiers": null,
    "kind": "app",
    "outboundIpAddresses": "xxx.xxx.xxx.xxx",
    "possibleOutboundIpAddresses": "xxx.xxx.xxx.xxx",
    "containerSize": 0,
    "dailyMemoryTimeQuota": 0,
    "suspendedTill": null,
    "siteDisabledReason": 0,
    "functionExecutionUnitsCache": null,
    "maxNumberOfWorkers": null,
    "homeStamp": "waws-prod-dm1-103",
    "cloningInfo": null,
    "hostingEnvironmentId": null,
    "tags": {},
    "resourceGroup": "xxxx-xxxx-xx",
    "defaultHostName": "mywebapptest.azurewebsites.net",
    "slotSwapStatus": null,
    "httpsOnly": false,
    "redundancyMode": "None",
    "inProgressOperationId": null,
    "geoDistributions": null
  },
  "identity": {
    "type": "SystemAssigned",
    "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
    "principalId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"
  }
}
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/web?api-version=2018-02-01

Headers:
x-ms-client-request-id        : 800713e2-052c-4180-b168-3c45b0326697
accept-language               : en-US

Body:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : be512c21-958e-4d9e-b6df-ef205d8729f6
x-ms-ratelimit-remaining-subscription-reads: 11988
x-ms-correlation-request-id   : 5202c588-a799-4664-8978-1b18e2aabd55
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T210709Z:5202c588-a799-4664-8978-1b18e2aabd55
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:07:08 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/web",
  "name": "mywebapptest",
  "type": "Microsoft.Web/sites/config",
  "location": "Central US",
  "tags": {},
  "properties": {
    "numberOfWorkers": 1,
    "defaultDocuments": [
      "Default.htm",
      "Default.html",
      "Default.asp",
      "index.htm",
      "index.html",
      "iisstart.htm",
      "default.aspx",
      "index.php",
      "hostingstart.html"
    ],
    "netFrameworkVersion": "v4.0",
    "phpVersion": "5.6",
    "pythonVersion": "",
    "nodeVersion": "",
    "linuxFxVersion": "",
    "windowsFxVersion": null,
    "requestTracingEnabled": false,
    "remoteDebuggingEnabled": false,
    "remoteDebuggingVersion": "VS2017",
    "httpLoggingEnabled": false,
    "logsDirectorySizeLimit": 35,
    "detailedErrorLoggingEnabled": false,
    "publishingUsername": "$mywebapptest",
    "publishingPassword": null,
    "appSettings": null,
    "metadata": null,
    "connectionStrings": null,
    "machineKey": null,
    "handlerMappings": null,
    "documentRoot": null,
    "scmType": "None",
    "use32BitWorkerProcess": false,
    "webSocketsEnabled": false,
    "alwaysOn": true,
    "javaVersion": null,
    "javaContainer": null,
    "javaContainerVersion": null,
    "appCommandLine": "",
    "managedPipelineMode": "Integrated",
    "virtualApplications": [
      {
        "virtualPath": "/",
        "physicalPath": "site\\wwwroot",
        "preloadEnabled": true,
        "virtualDirectories": null
      }
    ],
    "winAuthAdminState": 0,
    "winAuthTenantState": 0,
    "customAppPoolIdentityAdminState": false,
    "customAppPoolIdentityTenantState": false,
    "runtimeADUser": null,
    "runtimeADUserPassword": null,
    "loadBalancing": "LeastRequests",
    "routingRules": [],
    "experiments": {
      "rampUpRules": []
    },
    "limits": null,
    "autoHealEnabled": true,
    "autoHealRules": null,
    "tracingOptions": null,
    "vnetName": "",
    "siteAuthEnabled": false,
    "siteAuthSettings": {
      "enabled": null,
      "unauthenticatedClientAction": null,
      "tokenStoreEnabled": null,
      "allowedExternalRedirectUrls": null,
      "defaultProvider": null,
      "clientId": null,
      "clientSecret": null,
      "clientSecretCertificateThumbprint": null,
      "issuer": null,
      "allowedAudiences": null,
      "additionalLoginParams": null,
      "isAadAutoProvisioned": false,
      "googleClientId": null,
      "googleClientSecret": null,
      "googleOAuthScopes": null,
      "facebookAppId": null,
      "facebookAppSecret": null,
      "facebookOAuthScopes": null,
      "twitterConsumerKey": null,
      "twitterConsumerSecret": null,
      "microsoftAccountClientId": null,
      "microsoftAccountClientSecret": null,
      "microsoftAccountOAuthScopes": null
    },
    "cors": null,
    "push": null,
    "apiDefinition": null,
    "apiManagementConfig": null,
    "autoSwapSlotName": null,
    "localMySqlEnabled": false,
    "managedServiceIdentityId": 22064,
    "xManagedServiceIdentityId": null,
    "ipSecurityRestrictions": null,
    "scmIpSecurityRestrictions": null,
    "scmIpSecurityRestrictionsUseMain": false,
    "http20Enabled": false,
    "minTlsVersion": "1.2",
    "ftpsState": "AllAllowed",
    "reservedInstanceCount": 0,
    "preWarmedInstanceCount": null
  }
}
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/appsettings/list?api-version=2018-02-01

Headers:
x-ms-client-request-id        : 8a7a274b-c826-499b-b767-6b0daa53f14d
accept-language               : en-US

Body:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 31299c22-7a49-438b-b900-c509d494b68a
x-ms-ratelimit-remaining-subscription-resource-requests: 11993
x-ms-correlation-request-id   : d0a0650c-fcfb-4ce6-834b-05c63b1dbd59
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T210709Z:d0a0650c-fcfb-4ce6-834b-05c63b1dbd59
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:07:09 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/appsettings",
  "name": "appsettings",
  "type": "Microsoft.Web/sites/config",
  "location": "Central US",
  "tags": {},
  "properties": {
    "APPINSIGHTS_INSTRUMENTATIONKEY": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "APPINSIGHTS_PROFILERFEATURE_VERSION": "disabled",
    "APPINSIGHTS_SNAPSHOTFEATURE_VERSION": "disabled",
    "ApplicationInsightsAgent_EXTENSION_VERSION": "~2",
    "DiagnosticServices_EXTENSION_VERSION": "disabled",
    "InstrumentationEngine_EXTENSION_VERSION": "~1",
    "SnapshotDebugger_EXTENSION_VERSION": "disabled",
    "WEBSITE_NODE_DEFAULT_VERSION": "6.9.1",
    "XDT_MicrosoftApplicationInsights_BaseExtensions": "~1",
    "XDT_MicrosoftApplicationInsights_Mode": "recommended"
  }
}
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/connectionstrings/list?api-version=2018-02-01

Headers:
x-ms-client-request-id        : 26973619-49a7-4154-9c60-5e153254f3d2
accept-language               : en-US

Body:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : bf9b2da1-67e1-4315-96d0-b3585e397f2e
x-ms-ratelimit-remaining-subscription-resource-requests: 11992
x-ms-correlation-request-id   : 4d9ec2dd-be51-489a-a1ee-c65b6d8dfa8d
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T210709Z:4d9ec2dd-be51-489a-a1ee-c65b6d8dfa8d
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:07:09 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/connectionstrings",
  "name": "connectionstrings",
  "type": "Microsoft.Web/sites/config",
  "location": "Central US",
  "tags": {},
  "properties": {}
}
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/azurestorageaccounts/list?api-version=2018-02-01

Headers:
x-ms-client-request-id        : 847ed50e-2f56-415d-9719-15eef3fd6037
accept-language               : en-US

Body:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 530975be-aaaf-409d-970a-e16de494ec4a
x-ms-ratelimit-remaining-subscription-resource-requests: 11991
x-ms-correlation-request-id   : 22024c2d-da59-4934-8b6a-0a09eaec4497
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T210709Z:22024c2d-da59-4934-8b6a-0a09eaec4497
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:07:09 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/appsettings",
  "name": "azurestorageaccounts",
  "type": "Microsoft.Web/sites/config",
  "location": "Central US",
  "tags": {},
  "properties": {}
}
DEBUG: AzureQoSEvent: CommandName - Get-AzWebApp; IsSuccess - True; Duration - 00:00:01.3444881; Exception - ;
DEBUG: Finish sending metric.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/web?api-version=2018-02-01

Headers:
x-ms-client-request-id        : 50c6d97d-ab37-4adc-8031-67a170cac9d5
accept-language               : en-US

Body:
{
  "properties": {
    "numberOfWorkers": 1,
    "defaultDocuments": [
      "Default.htm",
      "Default.html",
      "Default.asp",
      "index.htm",
      "index.html",
      "iisstart.htm",
      "default.aspx",
      "index.php",
      "hostingstart.html"
    ],
    "netFrameworkVersion": "v4.0",
    "phpVersion": "5.6",
    "pythonVersion": "",
    "nodeVersion": "",
    "linuxFxVersion": "",
    "requestTracingEnabled": false,
    "remoteDebuggingEnabled": false,
    "remoteDebuggingVersion": "VS2017",
    "httpLoggingEnabled": false,
    "logsDirectorySizeLimit": 35,
    "detailedErrorLoggingEnabled": false,
    "publishingUsername": "$mywebapptest",
    "appSettings": [
      {
        "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
        "value": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"
      },
      {
        "name": "APPINSIGHTS_PROFILERFEATURE_VERSION",
        "value": "disabled"
      },
      {
        "name": "APPINSIGHTS_SNAPSHOTFEATURE_VERSION",
        "value": "disabled"
      },
      {
        "name": "ApplicationInsightsAgent_EXTENSION_VERSION",
        "value": "~2"
      },
      {
        "name": "DiagnosticServices_EXTENSION_VERSION",
        "value": "disabled"
      },
      {
        "name": "InstrumentationEngine_EXTENSION_VERSION",
        "value": "~1"
      },
      {
        "name": "SnapshotDebugger_EXTENSION_VERSION",
        "value": "disabled"
      },
      {
        "name": "WEBSITE_NODE_DEFAULT_VERSION",
        "value": "6.9.1"
      },
      {
        "name": "XDT_MicrosoftApplicationInsights_BaseExtensions",
        "value": "~1"
      },
      {
        "name": "XDT_MicrosoftApplicationInsights_Mode",
        "value": "recommended"
      }
    ],
    "connectionStrings": [],
    "scmType": "None",
    "use32BitWorkerProcess": false,
    "webSocketsEnabled": false,
    "alwaysOn": true,
    "appCommandLine": "",
    "managedPipelineMode": "Integrated",
    "virtualApplications": [
      {
        "virtualPath": "/",
        "physicalPath": "site\\wwwroot",
        "preloadEnabled": true
      }
    ],
    "loadBalancing": "LeastRequests",
    "experiments": {
      "rampUpRules": []
    },
    "autoHealEnabled": true,
    "vnetName": "",
    "localMySqlEnabled": false
  }
}
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 743114e6-d684-45f0-a1bb-a05c92b693e7
x-ms-ratelimit-remaining-subscription-writes: 1198
x-ms-correlation-request-id   : 6c36245f-4e08-4393-94db-d9bf05e59202
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T211827Z:6c36245f-4e08-4393-94db-d9bf05e59202
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:18:26 GMT
ETag                          : "1D50A98646246CB"
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest",
  "name": "mywebapptest",
  "type": "Microsoft.Web/sites",
  "location": "Central US",
  "tags": {},
  "properties": {
    "numberOfWorkers": 1,
    "defaultDocuments": [
      "Default.htm",
      "Default.html",
      "Default.asp",
      "index.htm",
      "index.html",
      "iisstart.htm",
      "default.aspx",
      "index.php",
      "hostingstart.html"
    ],
    "netFrameworkVersion": "v4.0",
    "phpVersion": "5.6",
    "pythonVersion": "",
    "nodeVersion": "",
    "linuxFxVersion": "",
    "windowsFxVersion": null,
    "requestTracingEnabled": false,
    "remoteDebuggingEnabled": false,
    "remoteDebuggingVersion": "VS2017",
    "httpLoggingEnabled": false,
    "logsDirectorySizeLimit": 35,
    "detailedErrorLoggingEnabled": false,
    "publishingUsername": "$mywebapptest",
    "publishingPassword": null,
    "appSettings": null,
    "metadata": null,
    "connectionStrings": null,
    "machineKey": null,
    "handlerMappings": null,
    "documentRoot": null,
    "scmType": "None",
    "use32BitWorkerProcess": false,
    "webSocketsEnabled": false,
    "alwaysOn": true,
    "javaVersion": null,
    "javaContainer": null,
    "javaContainerVersion": null,
    "appCommandLine": "",
    "managedPipelineMode": "Integrated",
    "virtualApplications": [
      {
        "virtualPath": "/",
        "physicalPath": "site\\wwwroot",
        "preloadEnabled": true,
        "virtualDirectories": null
      }
    ],
    "winAuthAdminState": 0,
    "winAuthTenantState": 0,
    "customAppPoolIdentityAdminState": false,
    "customAppPoolIdentityTenantState": false,
    "runtimeADUser": null,
    "runtimeADUserPassword": null,
    "loadBalancing": "LeastRequests",
    "routingRules": [],
    "experiments": {
      "rampUpRules": []
    },
    "limits": null,
    "autoHealEnabled": true,
    "autoHealRules": null,
    "tracingOptions": null,
    "vnetName": "",
    "siteAuthEnabled": false,
    "siteAuthSettings": {
      "enabled": null,
      "unauthenticatedClientAction": null,
      "tokenStoreEnabled": null,
      "allowedExternalRedirectUrls": null,
      "defaultProvider": null,
      "clientId": null,
      "clientSecret": null,
      "clientSecretCertificateThumbprint": null,
      "issuer": null,
      "allowedAudiences": null,
      "additionalLoginParams": null,
      "isAadAutoProvisioned": false,
      "googleClientId": null,
      "googleClientSecret": null,
      "googleOAuthScopes": null,
      "facebookAppId": null,
      "facebookAppSecret": null,
      "facebookOAuthScopes": null,
      "twitterConsumerKey": null,
      "twitterConsumerSecret": null,
      "microsoftAccountClientId": null,
      "microsoftAccountClientSecret": null,
      "microsoftAccountOAuthScopes": null
    },
    "cors": null,
    "push": null,
    "apiDefinition": null,
    "apiManagementConfig": null,
    "autoSwapSlotName": null,
    "localMySqlEnabled": false,
    "managedServiceIdentityId": 22064,
    "xManagedServiceIdentityId": null,
    "ipSecurityRestrictions": null,
    "scmIpSecurityRestrictions": null,
    "scmIpSecurityRestrictionsUseMain": false,
    "http20Enabled": false,
    "minTlsVersion": "1.2",
    "ftpsState": "AllAllowed",
    "reservedInstanceCount": 0,
    "preWarmedInstanceCount": null
  }
}
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/appsettings?api-version=2018-02-01

Headers:
x-ms-client-request-id        : 4f1afe8b-790c-4e0a-a37d-17c3522df83a
accept-language               : en-US

Body:
{
  "properties": {
    "APPINSIGHTS_INSTRUMENTATIONKEY": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
    "APPINSIGHTS_PROFILERFEATURE_VERSION": "disabled",
    "APPINSIGHTS_SNAPSHOTFEATURE_VERSION": "disabled",
    "ApplicationInsightsAgent_EXTENSION_VERSION": "~2",
    "DiagnosticServices_EXTENSION_VERSION": "disabled",
    "InstrumentationEngine_EXTENSION_VERSION": "~1",
    "SnapshotDebugger_EXTENSION_VERSION": "disabled",
    "WEBSITE_NODE_DEFAULT_VERSION": "6.9.1",
    "XDT_MicrosoftApplicationInsights_BaseExtensions": "~1",
    "XDT_MicrosoftApplicationInsights_Mode": "recommended"
  }
}
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 0a82ca72-6128-49f7-bc6c-46a504fe5cca
x-ms-ratelimit-remaining-subscription-writes: 1197
x-ms-correlation-request-id   : 0e6dca74-a2a1-4177-a01a-def0a9cd8a15
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T211828Z:0e6dca74-a2a1-4177-a01a-def0a9cd8a15
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:18:27 GMT
ETag                          : "1D50A9A92A51CB5"
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/appsettings",
  "name": "appsettings",
  "type": "Microsoft.Web/sites/config",
  "location": "Central US",
  "tags": {},
  "properties": {
    "APPINSIGHTS_INSTRUMENTATIONKEY": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
    "APPINSIGHTS_PROFILERFEATURE_VERSION": "disabled",
    "APPINSIGHTS_SNAPSHOTFEATURE_VERSION": "disabled",
    "ApplicationInsightsAgent_EXTENSION_VERSION": "~2",
    "DiagnosticServices_EXTENSION_VERSION": "disabled",
    "InstrumentationEngine_EXTENSION_VERSION": "~1",
    "SnapshotDebugger_EXTENSION_VERSION": "disabled",
    "WEBSITE_NODE_DEFAULT_VERSION": "6.9.1",
    "XDT_MicrosoftApplicationInsights_BaseExtensions": "~1",
    "XDT_MicrosoftApplicationInsights_Mode": "recommended"
  }
}
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/connectionstrings?api-version=2018-02-01

Headers:
x-ms-client-request-id        : be1af39e-4913-4162-8ac0-00bc216bbf05
accept-language               : en-US

Body:
{
  "properties": {}
}
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 79667ae8-237b-4d80-9b57-2b0e4edbce43
x-ms-ratelimit-remaining-subscription-writes: 1196
x-ms-correlation-request-id   : 6b946f2a-995d-413f-af30-18d559849373
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T211828Z:6b946f2a-995d-413f-af30-18d559849373
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:18:27 GMT
ETag                          : "1D50A9A92EDD880"
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/connectionstrings",
  "name": "connectionstrings",
  "type": "Microsoft.Web/sites/config",
  "location": "Central US",
  "tags": {},
  "properties": {}
}
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest?api-version=2018-02-01

Headers:
x-ms-client-request-id        : 057f9230-83ed-4182-bca2-33b54da909f8
accept-language               : en-US

Body:
{
  "properties": {
    "serverFarmId": "myplantest"
  },
  "location": "Central US"
}
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 1d617957-f45a-4ef0-81bb-4349f3966e0a
x-ms-ratelimit-remaining-subscription-resource-requests: 499
x-ms-correlation-request-id   : c943a5e1-4f8f-4dc6-9fdc-4e16ffbf2818
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T211831Z:c943a5e1-4f8f-4dc6-9fdc-4e16ffbf2818
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:18:30 GMT
ETag                          : "1D50A9A92EDD880"
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest",
  "name": "mywebapptest",
  "type": "Microsoft.Web/sites",
  "kind": "app",
  "location": "Central US",
  "properties": {
    "name": "mywebapptest",
    "state": "Running",
    "hostNames": [
      "mywebapptest.azurewebsites.net"
    ],
    "webSpace": "xxxx-xxxx-xx-CentralUSwebspace",
    "selfLink": "https://waws-prod-dm1-103.api.azurewebsites.windows.net:454/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/webspaces/xxxx-xxxx-xx-CentralUSwebspace/sites/mywebapptest",
    "repositorySiteName": "mywebapptest",
    "owner": null,
    "usageState": "Normal",
    "enabled": true,
    "adminEnabled": true,
    "enabledHostNames": [
      "mywebapptest.azurewebsites.net",
      "mywebapptest.scm.azurewebsites.net"
    ],
    "siteProperties": {
      "metadata": null,
      "properties": [
        {
          "name": "LinuxFxVersion",
          "value": ""
        },
        {
          "name": "WindowsFxVersion",
          "value": null
        }
      ],
      "appSettings": null
    },
    "availabilityState": "Normal",
    "sslCertificates": null,
    "csrs": [],
    "cers": null,
    "siteMode": null,
    "hostNameSslStates": [
      {
        "name": "mywebapptest.azurewebsites.net",
        "sslState": "Disabled",
        "ipBasedSslResult": null,
        "virtualIP": null,
        "thumbprint": null,
        "toUpdate": null,
        "toUpdateIpBasedSsl": null,
        "ipBasedSslState": "NotConfigured",
        "hostType": "Standard"
      },
      {
        "name": "mywebapptest.scm.azurewebsites.net",
        "sslState": "Disabled",
        "ipBasedSslResult": null,
        "virtualIP": null,
        "thumbprint": null,
        "toUpdate": null,
        "toUpdateIpBasedSsl": null,
        "ipBasedSslState": "NotConfigured",
        "hostType": "Repository"
      }
    ],
    "computeMode": null,
    "serverFarm": null,
    "serverFarmId": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/serverfarms/myplantest",
    "reserved": false,
    "isXenon": false,
    "hyperV": false,
    "lastModifiedTimeUtc": "2019-05-14T21:18:30.1",
    "storageRecoveryDefaultState": "Running",
    "contentAvailabilityState": "Normal",
    "runtimeAvailabilityState": "Normal",
    "siteConfig": null,
    "deploymentId": "mywebapptest",
    "trafficManagerHostNames": null,
    "sku": "PremiumV2",
    "scmSiteAlsoStopped": false,
    "targetSwapSlot": null,
    "hostingEnvironment": null,
    "hostingEnvironmentProfile": null,
    "clientAffinityEnabled": true,
    "clientCertEnabled": false,
    "clientCertExclusionPaths": null,
    "hostNamesDisabled": false,
    "domainVerificationIdentifiers": null,
    "kind": "app",
    "outboundIpAddresses": "xxx.xxx.xxx.xxx",
    "possibleOutboundIpAddresses": "xxx.xxx.xxx.xxx",
    "containerSize": 0,
    "dailyMemoryTimeQuota": 0,
    "suspendedTill": null,
    "siteDisabledReason": 0,
    "functionExecutionUnitsCache": null,
    "maxNumberOfWorkers": null,
    "homeStamp": "waws-prod-dm1-103",
    "cloningInfo": null,
    "hostingEnvironmentId": null,
    "tags": null,
    "resourceGroup": "xxxx-xxxx-xx",
    "defaultHostName": "mywebapptest.azurewebsites.net",
    "slotSwapStatus": null,
    "httpsOnly": false,
    "redundancyMode": "None",
    "inProgressOperationId": null,
    "geoDistributions": null
  },
  "identity": {
    "type": "SystemAssigned",
    "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
    "principalId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"
  }
}
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest?api-version=2018-02-01

Headers:
x-ms-client-request-id        : 75dfd9e2-be9a-41e6-87d6-b9d8b64bf144
accept-language               : en-US

Body:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 023d62c8-f37b-41e4-9f34-a6598736dfb0
x-ms-ratelimit-remaining-subscription-reads: 11975
x-ms-correlation-request-id   : 5dffa247-0a11-4d76-b38c-e6b3a96a8ebe
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T211831Z:5dffa247-0a11-4d76-b38c-e6b3a96a8ebe
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:18:30 GMT
ETag                          : "1D50A9A93F75940"
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest",
  "name": "mywebapptest",
  "type": "Microsoft.Web/sites",
  "kind": "app",
  "location": "Central US",
  "properties": {
    "name": "mywebapptest",
    "state": "Running",
    "hostNames": [
      "mywebapptest.azurewebsites.net"
    ],
    "webSpace": "xxxx-xxxx-xx-CentralUSwebspace",
    "selfLink": "https://waws-prod-dm1-103.api.azurewebsites.windows.net:454/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/webspaces/xxxx-xxxx-xx-CentralUSwebspace/sites/mywebapptest",
    "repositorySiteName": "mywebapptest",
    "owner": null,
    "usageState": "Normal",
    "enabled": true,
    "adminEnabled": true,
    "enabledHostNames": [
      "mywebapptest.azurewebsites.net",
      "mywebapptest.scm.azurewebsites.net"
    ],
    "siteProperties": {
      "metadata": null,
      "properties": [
        {
          "name": "LinuxFxVersion",
          "value": ""
        },
        {
          "name": "WindowsFxVersion",
          "value": null
        }
      ],
      "appSettings": null
    },
    "availabilityState": "Normal",
    "sslCertificates": null,
    "csrs": [],
    "cers": null,
    "siteMode": null,
    "hostNameSslStates": [
      {
        "name": "mywebapptest.azurewebsites.net",
        "sslState": "Disabled",
        "ipBasedSslResult": null,
        "virtualIP": null,
        "thumbprint": null,
        "toUpdate": null,
        "toUpdateIpBasedSsl": null,
        "ipBasedSslState": "NotConfigured",
        "hostType": "Standard"
      },
      {
        "name": "mywebapptest.scm.azurewebsites.net",
        "sslState": "Disabled",
        "ipBasedSslResult": null,
        "virtualIP": null,
        "thumbprint": null,
        "toUpdate": null,
        "toUpdateIpBasedSsl": null,
        "ipBasedSslState": "NotConfigured",
        "hostType": "Repository"
      }
    ],
    "computeMode": null,
    "serverFarm": null,
    "serverFarmId": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/serverfarms/myplantest",
    "reserved": false,
    "isXenon": false,
    "hyperV": false,
    "lastModifiedTimeUtc": "2019-05-14T21:18:30.1",
    "storageRecoveryDefaultState": "Running",
    "contentAvailabilityState": "Normal",
    "runtimeAvailabilityState": "Normal",
    "siteConfig": null,
    "deploymentId": "mywebapptest",
    "trafficManagerHostNames": null,
    "sku": "PremiumV2",
    "scmSiteAlsoStopped": false,
    "targetSwapSlot": null,
    "hostingEnvironment": null,
    "hostingEnvironmentProfile": null,
    "clientAffinityEnabled": true,
    "clientCertEnabled": false,
    "clientCertExclusionPaths": null,
    "hostNamesDisabled": false,
    "domainVerificationIdentifiers": null,
    "kind": "app",
    "outboundIpAddresses": "xxx.xxx.xxx.xxx",
    "possibleOutboundIpAddresses": "xxx.xxx.xxx.xxx",
    "containerSize": 0,
    "dailyMemoryTimeQuota": 0,
    "suspendedTill": null,
    "siteDisabledReason": 0,
    "functionExecutionUnitsCache": null,
    "maxNumberOfWorkers": null,
    "homeStamp": "waws-prod-dm1-103",
    "cloningInfo": null,
    "hostingEnvironmentId": null,
    "tags": null,
    "resourceGroup": "xxxx-xxxx-xx",
    "defaultHostName": "mywebapptest.azurewebsites.net",
    "slotSwapStatus": null,
    "httpsOnly": false,
    "redundancyMode": "None",
    "inProgressOperationId": null,
    "geoDistributions": null
  },
  "identity": {
    "type": "SystemAssigned",
    "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
    "principalId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"
  }
}
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest?api-version=2018-02-01

Headers:
x-ms-client-request-id        : 8dcf3707-8ca6-44a0-ac32-50b5e4b2c657
accept-language               : en-US

Body:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 9ef02d42-5f25-4447-8a6e-bcfb08e58163
x-ms-ratelimit-remaining-subscription-reads: 11974
x-ms-correlation-request-id   : 0a4b59f7-df6d-4efc-8026-8ffaf9d85e25
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T211832Z:0a4b59f7-df6d-4efc-8026-8ffaf9d85e25
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:18:31 GMT
ETag                          : "1D50A9A93F75940"
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest",
  "name": "mywebapptest",
  "type": "Microsoft.Web/sites",
  "kind": "app",
  "location": "Central US",
  "properties": {
    "name": "mywebapptest",
    "state": "Running",
    "hostNames": [
      "mywebapptest.azurewebsites.net"
    ],
    "webSpace": "xxxx-xxxx-xx-CentralUSwebspace",
    "selfLink": "https://waws-prod-dm1-103.api.azurewebsites.windows.net:454/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/webspaces/xxxx-xxxx-xx-CentralUSwebspace/sites/mywebapptest",
    "repositorySiteName": "mywebapptest",
    "owner": null,
    "usageState": "Normal",
    "enabled": true,
    "adminEnabled": true,
    "enabledHostNames": [
      "mywebapptest.azurewebsites.net",
      "mywebapptest.scm.azurewebsites.net"
    ],
    "siteProperties": {
      "metadata": null,
      "properties": [
        {
          "name": "LinuxFxVersion",
          "value": ""
        },
        {
          "name": "WindowsFxVersion",
          "value": null
        }
      ],
      "appSettings": null
    },
    "availabilityState": "Normal",
    "sslCertificates": null,
    "csrs": [],
    "cers": null,
    "siteMode": null,
    "hostNameSslStates": [
      {
        "name": "mywebapptest.azurewebsites.net",
        "sslState": "Disabled",
        "ipBasedSslResult": null,
        "virtualIP": null,
        "thumbprint": null,
        "toUpdate": null,
        "toUpdateIpBasedSsl": null,
        "ipBasedSslState": "NotConfigured",
        "hostType": "Standard"
      },
      {
        "name": "mywebapptest.scm.azurewebsites.net",
        "sslState": "Disabled",
        "ipBasedSslResult": null,
        "virtualIP": null,
        "thumbprint": null,
        "toUpdate": null,
        "toUpdateIpBasedSsl": null,
        "ipBasedSslState": "NotConfigured",
        "hostType": "Repository"
      }
    ],
    "computeMode": null,
    "serverFarm": null,
    "serverFarmId": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/serverfarms/myplantest",
    "reserved": false,
    "isXenon": false,
    "hyperV": false,
    "lastModifiedTimeUtc": "2019-05-14T21:18:30.1",
    "storageRecoveryDefaultState": "Running",
    "contentAvailabilityState": "Normal",
    "runtimeAvailabilityState": "Normal",
    "siteConfig": null,
    "deploymentId": "mywebapptest",
    "trafficManagerHostNames": null,
    "sku": "PremiumV2",
    "scmSiteAlsoStopped": false,
    "targetSwapSlot": null,
    "hostingEnvironment": null,
    "hostingEnvironmentProfile": null,
    "clientAffinityEnabled": true,
    "clientCertEnabled": false,
    "clientCertExclusionPaths": null,
    "hostNamesDisabled": false,
    "domainVerificationIdentifiers": null,
    "kind": "app",
    "outboundIpAddresses": "xxx.xxx.xxx.xxx",
    "possibleOutboundIpAddresses": "xxx.xxx.xxx.xxx",
    "containerSize": 0,
    "dailyMemoryTimeQuota": 0,
    "suspendedTill": null,
    "siteDisabledReason": 0,
    "functionExecutionUnitsCache": null,
    "maxNumberOfWorkers": null,
    "homeStamp": "waws-prod-dm1-103",
    "cloningInfo": null,
    "hostingEnvironmentId": null,
    "tags": null,
    "resourceGroup": "xxxx-xxxx-xx",
    "defaultHostName": "mywebapptest.azurewebsites.net",
    "slotSwapStatus": null,
    "httpsOnly": false,
    "redundancyMode": "None",
    "inProgressOperationId": null,
    "geoDistributions": null
  },
  "identity": {
    "type": "SystemAssigned",
    "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
    "principalId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"
  }
}
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/web?api-version=2018-02-01

Headers:
x-ms-client-request-id        : 8c326453-83a1-4640-b485-4bbc1f81f260
accept-language               : en-US

Body:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 4a553962-df3f-428f-b0f4-150c0d12c4a4
x-ms-ratelimit-remaining-subscription-reads: 11973
x-ms-correlation-request-id   : 5314a2a0-1049-40d5-b07c-f8d599bebb18
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T211832Z:5314a2a0-1049-40d5-b07c-f8d599bebb18
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:18:31 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/web",
  "name": "mywebapptest",
  "type": "Microsoft.Web/sites/config",
  "location": "Central US",
  "properties": {
    "numberOfWorkers": 1,
    "defaultDocuments": [
      "Default.htm",
      "Default.html",
      "Default.asp",
      "index.htm",
      "index.html",
      "iisstart.htm",
      "default.aspx",
      "index.php",
      "hostingstart.html"
    ],
    "netFrameworkVersion": "v4.0",
    "phpVersion": "5.6",
    "pythonVersion": "",
    "nodeVersion": "",
    "linuxFxVersion": "",
    "windowsFxVersion": null,
    "requestTracingEnabled": false,
    "remoteDebuggingEnabled": false,
    "remoteDebuggingVersion": "VS2017",
    "httpLoggingEnabled": false,
    "logsDirectorySizeLimit": 35,
    "detailedErrorLoggingEnabled": false,
    "publishingUsername": "$mywebapptest",
    "publishingPassword": null,
    "appSettings": null,
    "metadata": null,
    "connectionStrings": null,
    "machineKey": null,
    "handlerMappings": null,
    "documentRoot": null,
    "scmType": "None",
    "use32BitWorkerProcess": false,
    "webSocketsEnabled": false,
    "alwaysOn": true,
    "javaVersion": null,
    "javaContainer": null,
    "javaContainerVersion": null,
    "appCommandLine": "",
    "managedPipelineMode": "Integrated",
    "virtualApplications": [
      {
        "virtualPath": "/",
        "physicalPath": "site\\wwwroot",
        "preloadEnabled": true,
        "virtualDirectories": null
      }
    ],
    "winAuthAdminState": 0,
    "winAuthTenantState": 0,
    "customAppPoolIdentityAdminState": false,
    "customAppPoolIdentityTenantState": false,
    "runtimeADUser": null,
    "runtimeADUserPassword": null,
    "loadBalancing": "LeastRequests",
    "routingRules": [],
    "experiments": {
      "rampUpRules": []
    },
    "limits": null,
    "autoHealEnabled": true,
    "autoHealRules": null,
    "tracingOptions": null,
    "vnetName": "",
    "siteAuthEnabled": false,
    "siteAuthSettings": {
      "enabled": null,
      "unauthenticatedClientAction": null,
      "tokenStoreEnabled": null,
      "allowedExternalRedirectUrls": null,
      "defaultProvider": null,
      "clientId": null,
      "clientSecret": null,
      "clientSecretCertificateThumbprint": null,
      "issuer": null,
      "allowedAudiences": null,
      "additionalLoginParams": null,
      "isAadAutoProvisioned": false,
      "googleClientId": null,
      "googleClientSecret": null,
      "googleOAuthScopes": null,
      "facebookAppId": null,
      "facebookAppSecret": null,
      "facebookOAuthScopes": null,
      "twitterConsumerKey": null,
      "twitterConsumerSecret": null,
      "microsoftAccountClientId": null,
      "microsoftAccountClientSecret": null,
      "microsoftAccountOAuthScopes": null
    },
    "cors": null,
    "push": null,
    "apiDefinition": null,
    "apiManagementConfig": null,
    "autoSwapSlotName": null,
    "localMySqlEnabled": false,
    "managedServiceIdentityId": 22064,
    "xManagedServiceIdentityId": null,
    "ipSecurityRestrictions": null,
    "scmIpSecurityRestrictions": null,
    "scmIpSecurityRestrictionsUseMain": false,
    "http20Enabled": false,
    "minTlsVersion": "1.2",
    "ftpsState": "AllAllowed",
    "reservedInstanceCount": 0,
    "preWarmedInstanceCount": null
  }
}
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/appsettings/list?api-version=2018-02-01

Headers:
x-ms-client-request-id        : ed327020-f2c6-437b-935a-4af8257d847c
accept-language               : en-US

Body:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 8b767637-ad18-4786-ae22-b0ee0f04b952
x-ms-ratelimit-remaining-subscription-resource-requests: 11984
x-ms-correlation-request-id   : 7cea8366-0336-4323-b8c0-9b34dcf4321e
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T211832Z:7cea8366-0336-4323-b8c0-9b34dcf4321e
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:18:31 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/appsettings",
  "name": "appsettings",
  "type": "Microsoft.Web/sites/config",
  "location": "Central US",
  "properties": {
    "APPINSIGHTS_INSTRUMENTATIONKEY": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
    "APPINSIGHTS_PROFILERFEATURE_VERSION": "disabled",
    "APPINSIGHTS_SNAPSHOTFEATURE_VERSION": "disabled",
    "ApplicationInsightsAgent_EXTENSION_VERSION": "~2",
    "DiagnosticServices_EXTENSION_VERSION": "disabled",
    "InstrumentationEngine_EXTENSION_VERSION": "~1",
    "SnapshotDebugger_EXTENSION_VERSION": "disabled",
    "WEBSITE_NODE_DEFAULT_VERSION": "6.9.1",
    "XDT_MicrosoftApplicationInsights_BaseExtensions": "~1",
    "XDT_MicrosoftApplicationInsights_Mode": "recommended"
  }
}
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/connectionstrings/list?api-version=2018-02-01

Headers:
x-ms-client-request-id        : 823efb2b-b094-4250-b39b-830a8d844170
accept-language               : en-US

Body:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 7f3b9f2b-e048-4f90-8bb4-f899928d95b5
x-ms-ratelimit-remaining-subscription-resource-requests: 11983
x-ms-correlation-request-id   : e2f5e578-cb55-4efa-b437-c905de3be235
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T211833Z:e2f5e578-cb55-4efa-b437-c905de3be235
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:18:32 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/connectionstrings",
  "name": "connectionstrings",
  "type": "Microsoft.Web/sites/config",
  "location": "Central US",
  "properties": {}
}
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/azurestorageaccounts/list?api-version=2018-02-01

Headers:
x-ms-client-request-id        : 270493a7-df3f-4a54-b1c5-28b73393944c
accept-language               : en-US

Body:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : dcc5e516-1353-4907-b5d6-fc0f14f5cfe8
x-ms-ratelimit-remaining-subscription-resource-requests: 11982
x-ms-correlation-request-id   : b8d56008-d657-40e9-a5d5-da886bec6bfe
x-ms-routing-request-id       : NORTHCENTRALUS:20190514T211833Z:b8d56008-d657-40e9-a5d5-da886bec6bfe
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 14 May 2019 21:18:32 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-xxxx-xx/providers/Microsoft.Web/sites/mywebapptest/config/appsettings",
  "name": "azurestorageaccounts",
  "type": "Microsoft.Web/sites/config",
  "location": "Central US",
  "properties": {}
}
DEBUG: AzureQoSEvent: CommandName - Set-AzWebApp; IsSuccess - True; Duration - 00:00:09.6287511; Exception - ;
DEBUG: Finish sending metric.
```

## Error output

```

```

**Comment by markcowl** [comment]
@vinhent Can you please provide debug stream output when attempting to save / retrieve these values?

To do this, set ```$DebugPreference="Continue"``` and then run the cmdlet.

Once done, you can turn off debug logging using ```$DebugPreference="SilentlyContinue"```

**Comment by vinhent** [comment]
@markcowl Thanks for the reply, the post was updated with debug output.

**Comment by markcowl** [comment]
@panchagnula @NKing92 Can you take  alook?

**Comment by panchagnula** [comment]
@vinhent we believe this should be fixed - can you check with the latest Az command version & confirm. Thank you.

**Comment by vinhent** [comment]
I installed Az 2.4.0 and tested with this cmdlet:

`$webApp = Get-AzWebApp -ResourceGroupName $resourceGroupName -Name $appName -ErrorAction Stop`

I'm still getting `$null` in `$webApp.SiteConfig.FtpsState` and `$webApp.SiteConfig.Http20Enabled` whatever their real values are.

**Comment by vinhent** [comment]
Can we reopen this issue?

**Comment by panchagnula** [comment]
@vinhent we have a fix for this in the dev branch - will be go out with our next release

**Comment by nomie788** [comment]
when do we expect the next release?

**Comment by vinhent** [comment]
@panchagnula Alright thank you!

**Comment by panchagnula** [comment]
> when do we expect the next release?

@nomie788 i believe this is the next release https://github.com/Azure/azure-powershell/milestone/76

**Comment by HQJaTu** [comment]
Does that release also add handling to updated `ipSecurityRestrictions`?

Restricting for IPv6 and VNet/subnet has been added to API and Portal, but any attempts to modify a modern-restricted App Service with Az-library fail miserably.

**Comment by lana-white** [comment]
I finally figured this out. I did not find any solutions online anywhere!!
You have to set the ClientArrAffinity on the resource, rather than the web app, using the Set-AzResource command. 
For example: 

`Set-AzResource -ResourceGroupName $rgName -Name $appName -ResourceType $resourceType -Properties @{ClientAffinityEnabled = $false} -force`
