### ISSUE TITLE
Deployment of Pipeline with parameter value NULL fails via Set-AzureRmDataFactoryV2Pipeline

### ISSUE THREAD

**Issue by oppemaniac** [Azure/azure-powershell#9297]
Cannot deploy JSON definition file when parameter is NULL for type "SqlServerStoredProcedure": 'Value' cannot be null.

I used the cmdlet `Set-AzureRmDataFactoryV2Pipeline `

Setting the value to empty string creates the ADF Object, but then option TREAT AS NULL is unchecked and we cannot run the pipeline out of the box.

I explained the behavior on SO [here](https://stackoverflow.com/questions/56238024/deployment-of-pipeline-with-parameter-value-null-fails-via-set-azurermdatafactor)

This is related to this issue #5004

Downloading the template of the pipeline itself contains `"value": null` for SqlServerStoredProcedures but cannot be deployed from powershell.

**Comment by markcowl** [comment]
@hvermis can you take a look?

**Comment by hvermis** [comment]
@zhangyd2015 can you help to reassign to the owner?

**Comment by zhangyd2015** [comment]
Assigned to @Yiliu-microsoft

**Comment by hvermis** [comment]
This is fixed, will be available in July 30 release of Powershell.

**Comment by datasharkNL** [comment]
Still have this issue with creating a pipeline with PowerShell
`Set-AzureRmDataFactoryV2Pipeline : 'Value' cannot be null`

![image](https://user-images.githubusercontent.com/54980443/73142758-b425cb00-4092-11ea-8d78-a27336a25fac.png)

**Comment by blacklabnz** [comment]
hi Team, we are facing this issue again using Set-AzureRmDataFactoryV2Pipeline, cmdlet does not throw, but the "treat as null" is not set in adf. 
Could you please help and have a look ?

**Comment by shawnxzq** [comment]
@blacklabnz Please use the latest Az module instead, the AzureRm Module is deprecate and we won't add any new feature in it, thx!
