### ISSUE TITLE
webapp:User assigned managed identity does not work in Azure Functions

### ISSUE THREAD

**Issue by eamonoreilly** [Azure/azure-powershell#9479]
When using user managed identity in a function app, the client id does not seem to be used and is required when using managed identity.

Example: The following works correctly as the clientid parameter is added to the query.

```powershell
$tokenAuthURI = $env:MSI_ENDPOINT + "?resource=https://management.azure.com/&clientid=3c9a8f3e-9f2c-42e0-a809-727323733352&api-version=2017-09-01"
$tokenResponse = Invoke-RestMethod -Method Get -Headers @{"Secret"="$env:MSI_SECRET"} -Uri $tokenAuthURI
```

If you however run `Connect-AzAccount -AccountId "3c9a8f3e-9f2c-42e0-a809-727323733352" -Identity -debug -confirm:$false`

you get the below error and it looks like the clientid is not passed in from the -AccountId parameter.

```
2019-06-20T19:18:51.574 [Information] Executing 'Functions.HttpTrigger1' (Reason='This function was programmatically called via the host APIs.', Id=b90ddd73-d184-4780-a641-93ce1a30568e)
2019-06-20T19:19:00.004 [Debug] DEBUG: 7:18:59 PM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'ManagedServiceLogin'.
2019-06-20T19:19:00.004 [Debug] DEBUG: 7:18:59 PM - Autosave setting from startup session: 'Process'
2019-06-20T19:19:00.004 [Debug] DEBUG: 7:18:59 PM - No autosave setting detected in environment variable 'AzContextAutoSave'.
2019-06-20T19:19:00.005 [Debug] DEBUG: 7:18:59 PM - Using Autosave scope 'Process'
2019-06-20T19:19:00.099 [Debug] DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
2019-06-20T19:19:00.100 [Debug] DEBUG: [HttpClientOperations]: Adding Header 'Metadata'
2019-06-20T19:19:00.101 [Debug] DEBUG: [HttpClientOperations]: Adding Header 'Secret'
2019-06-20T19:19:00.101 [Debug] DEBUG: Checking Cache request http://127.0.0.1:41668/MSI/token/?resource=https://management.azure.com/&api-version=2017-09-01
2019-06-20T19:19:00.109 [Debug] DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
http://127.0.0.1:41668/MSI/token/?resource=https://management.azure.com/&api-version=2017-09-01

Headers:
Secret                        : F5E214099FCC43A1BC4DA32F54C5AABCA
Metadata                      : true

Body:
2019-06-20T19:19:00.109 [Debug] DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Transfer-Encoding             : chunked
Date                          : Thu, 20 Jun 2019 19:18:59 GMT

Body:
2019-06-20T19:19:00.109 [Debug] DEBUG: Checking Cache request http://localhost:50342/oauth2/token?resource=https://management.azure.com/&api-version=2017-09-01
2019-06-20T19:19:00.110 [Debug] DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
http://localhost:50342/oauth2/token?resource=https://management.azure.com/&api-version=2017-09-01

Headers:
Secret                        : F5E214099FCC43A1BC4DA32F54C5760A
Metadata                      : true

Body:
2019-06-20T19:19:00.500 [Error] ERROR: An attempt was made to access a socket in a way forbidden by its access permissions
Microsoft.Azure.WebJobs.Script.Rpc.RpcException : Result: ERROR: An attempt was made to access a socket in a way forbidden by its access permissions
Exception: An attempt was made to access a socket in a way forbidden by its access permissions
Stack:    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientWithRetry.SendAsync(HttpRequestMessage request, CancellationToken token)
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.SafeSendRequestAsync(HttpRequestMessage request, CancellationToken token)
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.GetAsync(String requestUri, CancellationToken token)
   at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessTokenBase`1.GetOrRenewAuthentication()
   at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessTokenBase`1.get_AccessToken()
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass94_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileClient client)
   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2019-06-20T19:19:00.543 [Debug] DEBUG: AzureQoSEvent: CommandName - Connect-AzAccount; IsSuccess - False; Duration - 00:00:00.3658887; Exception - System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientWithRetry.SendAsync(HttpRequestMessage request, CancellationToken token)
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.SafeSendRequestAsync(HttpRequestMessage request, CancellationToken token)
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.GetAsync(String requestUri, CancellationToken token)
   at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessTokenBase`1.GetOrRenewAuthentication()
   at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessTokenBase`1.get_AccessToken()
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass94_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileClient client)
   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
2019-06-20T19:19:00.733 [Debug] DEBUG: Finish sending metric.
2019-06-20T19:19:00.733 [Debug] DEBUG: 7:19:00 PM - ConnectAzureRmAccountCommand end processing.
2019-06-20T19:19:00.734 [Debug] DEBUG: 7:19:00 PM - ConnectAzureRmAccountCommand end processing.
2019-06-20T19:19:00.776 [Information] Executed 'Functions.HttpTrigger1' (Succeeded, Id=b90ddd73-d184-4780-a641-93ce1a30568e)
2019-06-20T19:20:17  No new trace in the past 1 min(s).
2019-06-20T19:21:17  No new trace in the past 2 min(s).
```

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by ahmedelnably** [comment]
This is an issue with the Azure powershell sdk,

**Comment by IanKemp** [comment]
Is this perhaps going to be fixed sometime this millennium?

**Comment by markcowl** [comment]
### Description
For user-assigned identity support, PowerShell allows the user to input clientId, ObjectId, or resource when specifying the account.  Each of these uses a slightly different query string in the MSI Uri - we simply need to check the account setting in the AppService MSI implementation, and use the equivalent strings from the parallel VM AppService MSI class.

- [ ] Update AppService MSI to check and update URI query string based on Account setting
- [ ] Add unit tests to verify correct URI generation for user-defined MSI
- [ ] Test end-to-end with Functions

### Cost: 6

**Comment by markcowl** [comment]
General MSI information: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview
AppService MSI: https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity

**Comment by markcowl** [comment]
Fixed and released.

**Comment by eugeneniemand** [comment]
@markcowl can this be reopened as I'm still experiencing issues mentioned above?
